### ISSUE TITLE
Note about browser support?

### ISSUE THREAD

**Issue by butsjoh** [GetmeUK/ContentTools#1]
Would be nice to know which browser you tested it on. Also to explain with underlying web api you are using (contenteditable, ...) and if there are needs for polyfills.

**Comment by anthonyjb** [comment]
You're right that's something I need to add to the repo READMEs and the API docs. To help answer your question ahead of that:

**Browser support**
The current aim is for all the libraries to support IE9+, Chrome and Firefox. Test suites are complete for all the libraries accept ContentTools and I'm using [Jasmine](http://jasmine.github.io/) to check that the tests pass in those browsers.

There will be some visual differences for ContentTools in IE9 as I use CSS animations for some of the UI feedback.

My current development priority is to complete the test suite for ContentTools.

**Underlying API**

So whenever text is being edited then the `contenteditable` attribute is appended to the element (or a wrapper element in the case of table dimensions and list items - thank you IE for that doosy). Even so the output of the `contenteditable` element is heavily marshalled using the HTMLParser library to ensure that the content output is consistent and not browser specific. 

As for polyfills the only one I can think of is:

**Comment by dburrows** [comment]
I had the same question and this is a great explanation, think you can just add the two paras above to the README with a quick edit

**Comment by butsjoh** [comment]
I agree with @dburrows :+1:

**Comment by anthonyjb** [comment]
Thanks for the feedback @butsjoh and @dburrows.
