### ISSUE TITLE
Icomoon project .json file

### ISSUE THREAD

**Issue by shvetsovdm** [GetmeUK/ContentTools#100]
When I create new font in the icomoon app character codes do not match those in ContentTools CSS. I have to manually change character codes to match those that in your css. Icomoon allow to download JSON config file of font project. Do you have icomoon JSON file for ContentTools font? Can you share it?

**Comment by anthonyjb** [comment]
I've downloaded the JSON config file and added it to the repo here: https://github.com/GetmeUK/ContentTools/tree/master/external

**Comment by shvetsovdm** [comment]
@anthonyjb awesome, thank you.

**Comment by l2aelba** [comment]
+ 1, You should add this on tut : http://getcontenttools.com/tutorials/adding-new-tools

**Comment by anthonyjb** [comment]
@l2aelba agreed and will do.

**Comment by anthonyjb** [comment]
I've now added a not referencing the config file in the tutorial.
