### ISSUE TITLE
Easing the Line Break behaviour

### ISSUE THREAD

**Issue by dirkjacobs** [GetmeUK/ContentTools#101]
I would like to enhance the 'line-break' experience (currently only through palette) by pressing the Shift-Return as is done in a lot of editors.

Any idea how to implement this ?

**Comment by anthonyjb** [comment]
So on pressing shift return/enter we'd insert a br instead of a paragraph? I think this is a great idea and I'm happy to implement the change in the next few days if that's it?

If you want to do it soon than that you need to look to modify the behaviour in of `ContentEdit.Text._keyReturn` in the ContentEdit code base (https://github.com/GetmeUK/ContentEdit).

**Comment by dirkjacobs** [comment]
Hi Ant,

that's exactly what I would experience, from a user point of view, as a 
big improvement  : pressing shift return/enter inserting a <br> instead 
of creating a new paragraph.
Not sure if i'm able to modify the code myself, but glad to hear you're 
in for the change in the next few days.

Tx

**Comment by dirkjacobs** [comment]
Hi, checked it out with different bowsers and I have the impression there is a small issue.
The first time you hit SHIFT-RETURN it seems that the 'real cursor' has move to the next line, but the visual experience is different. The 'blinking cursor' stays on the current location (not on the next line) and the 'edit-box' with the yellow background doesn't grow.

For a user this gives the impression it didn't worked and the user will hit SHIFT-RETURN again and starts typing the same info.

**Comment by anthonyjb** [comment]
Can you let me know which browsers?

**Comment by dirkjacobs** [comment]
Firefox 43.0.4
Chrome 47
Edge

**Comment by anthonyjb** [comment]
Can you send me a screenshot of what you're seeing as I might be misunderstanding, niether Chromium or Firefox are displaying this issue for me.

**Comment by anthonyjb** [comment]
I don't generate a visual cursor (we use the system text cursor) so it wont be that they're moving independently although cursor. Can I ask are you doing this at the end of the line or part way through the text and does it make a difference which - I remember having issues with multiple `br` tags at the end of a line displaying oddly before.

**Comment by anthonyjb** [comment]
OK I can confirm I'm definitely getting an issue with this when the cursor is at the end of the line on different browsers - will flag as a bug.

**Comment by dirkjacobs** [comment]
![step-1](https://cloud.githubusercontent.com/assets/15648092/12480123/5228ebb6-c040-11e5-960f-4ffd2476c6ad.PNG)
![step-2-after-pressing-shift-retuen](https://cloud.githubusercontent.com/assets/15648092/12480124/522c7006-c040-11e5-8487-b74416af40e7.PNG)
![step-3-typed dirk](https://cloud.githubusercontent.com/assets/15648092/12480129/523e5244-c040-11e5-8a2e-a1741a2abcc2.PNG)
![step-4-pressed-shift-return-again](https://cloud.githubusercontent.com/assets/15648092/12480125/522ea042-c040-11e5-99d9-7d8b5da9bed7.PNG)
![step-5-typed-anthony](https://cloud.githubusercontent.com/assets/15648092/12480126/5233cffe-c040-11e5-9e17-6a82eed37c45.PNG)
![step-6-pressed-shift-return-2times](https://cloud.githubusercontent.com/assets/15648092/12480127/523478b4-c040-11e5-9b4b-455074a9e24e.PNG)

**Comment by dirkjacobs** [comment]
Tried to add my 'workflow'

**Comment by anthonyjb** [comment]
@dirkjacobs thanks for your help - I pushed a fix that behaves as I would expect on FF and Chrome now, though it's not the nicest of hacks I have to admit (https://github.com/GetmeUK/ContentEdit/blob/f82846d335b5b38e2e4b9c5c95a41ec216c3d19f/src/scripts/text.coffee#L317).

**Comment by dirkjacobs** [comment]
But works great !

Tx,
D.
