### ISSUE TITLE
Hashtag/Token Plugin

### ISSUE THREAD

**Issue by KI-G** [GetmeUK/ContentTools#103]
Hi, I'm loving how ContentTools feels for End Users. I was looking for a RTE who is also displaying the structure / nodes of the text in an easy to understand manner... and CT does that just perfect (yes, i am a bit excited ;-)).

I'd need to implement a Token Plugin: when a user presses the @ or # Key, a new element for choosing the right hashtag have to show up at exactly the same position. Where would you start to implement this or is anything like this already in the makings?

**Comment by anthonyjb** [comment]
Hi @KI-G - thank you for the nice comments :)

So there are 2 things to consider:

1. Detecting when the user has entered the `@` or `#` tag into the content.
2. Popping up an auto-complete of some sort to allow the user to select from predefined options.

To monitor for changes to content I'd recommend monitoring key down events against the document when the editor is live, for example:

```coffeescript

# Listen for key events against the document
document.addEventListener 'keydown', (ev) ->

    # Get the currently focused element
    element = ContentEdit.Root.get().focused()
   
    # Check an element is selected and it supports content
    if not element or not element.content 
        return

    # Check the element contains a # or @ character
    text = element.content.text()
    text = element.domElement().textContent # Likely to be a lot more efficient
    ...

    # Get the position of the caret/text cursor and determine if the user requires a typeahead
    selection = ContentSelect.Range.query(element.domElement())
    ...

```

Next you'll need to open a popup at the position of the caret/text cursor, for this I recommend you look to use the [AnchoredDialog](https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/dialogs/dialogs.coffee#L1) as a basis for the popup and to get the position you use the `ContentSelect.Range.rect()` method against your `selection` ([referenced here](http://getcontenttools.com/api/content-select#reference)), you can see an example of this usage in the [LinkTool](https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/tools.coffee#L209).

Hope that helps get you under way and shout if I can help out further.

**Comment by KI-G** [comment]
Hi @anthonyjb This is much more information I hoped for and the LinkTool is a good starting point. It could anyway be a good practice to build the tokens as anchor tags...

Very kind of you, thanks!
