### ISSUE TITLE
IMAGE_UPLOADER function

### ISSUE THREAD

**Issue by cesarve77** [GetmeUK/ContentTools#105]
I develop a just JS solution for ContentTools.IMAGE_UPLOADER

You can check it in:
https://gist.github.com/cesarve77/fdbdee02e0caed71ac35

may be this can be include as default

**Comment by anthonyjb** [comment]
Hi @cesarve77 thanks for contributing this - I'd be happy to consider adding a more complete base image uploader example to the library and a native JavaScript one would be popular with the community I'm sure.

In it's current form however I wouldn't be able to consider the code for the core library without the following additions:

- Comments to make it easy for a user new to the code to pick it up and use it in their own application.
- Test specifications that can be run using `grunt jasmine` against the code to ensure any changes made to it or the ContentTools core library do not break its function. (I'm still completing the test specifications for ContentTools currently and I'm trying to ensure that like all the other libraries (ContentEdit, ContentSelect, FSM and HTMLString) there is a comprehensive test specification for the library).
- Consistent formatting of the cod,e in particular the use of white space.

**Comment by cesarve77** [comment]
Perfect I will be glad to contribute, but in this moment i don't have time.
I hope have it in 2 month then i will do my job..
While I hope  this gist can help someone

Thanks and congrats for this excellent tool

+sorry for my english

2016-01-25 16:06 GMT-04:30 Anthony Blackshaw <notifications@github.com>:

> Hi @cesarve77 <https://github.com/cesarve77> thanks for contributing this
> - I'd be happy to consider adding a more complete base image uploader
> example to the library and a native JavaScript one would be popular with
> the community I'm sure.
>
> In it's current form however I wouldn't be able to consider the code for
> the core library without the following additions:
>
>    - Comments to make it easy for a user new to the code to pick it up
>    and use it in their own application.
>    - Test specifications that can be run using grunt jasmine against the
>    code to ensure any changes made to it or the ContentTools core library do
>    not break its function. (I'm still completing the test specifications for
>    ContentTools currently and I'm trying to ensure that like all the other
>    libraries (ContentEdit, ContentSelect, FSM and HTMLString) there is a
>    comprehensive test specification for the library).
>    - Consistent formatting of the cod,e in particular the use of white
>    space.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GetmeUK/ContentTools/issues/105#issuecomment-174654739>
> .
>



-- 


César Ramos
Av. Romúlo Gallegos
Centro Gerencial los Andes.
Ofc 6D. Boleita. Caracas
04141400601
02129352802

**Comment by anthonyjb** [comment]
Thanks for the kind comments and contributing the gist - I'm sure people will find it useful in the meantime :+1:
