### ISSUE TITLE
Add image by link

### ISSUE THREAD

**Issue by Eeliya** [GetmeUK/ContentTools#106]
It would be nice that we have tool to add image by link :)

If I want to add this feature to the current image tool so user can choose between uploading the image or specifying a link to image, what would be the best way to implement it?

**Comment by anthonyjb** [comment]
I agree this would be a nice addition to the library :+1:

Are you looking to contribute the feature back to the CT core library? I would be happy to have this option for users. If so then I would suggest we look first at how we can best integrate the new functionality into the existing UI, e.g the ImageDialog?

If it's for a separate project then I'll happily provide a run down of what steps I believe are required.

**Comment by Eeliya** [comment]
Unfortunately I made a lot of changes, which are not compatible with ContetnTools. I'm also using vanilla js :D instead of coffee script.

Actually I created completely a new project called ContentStrike (inspired by counter-strike) which is using ContentTools with many changes.

I can create it and convert it to coffee script and email it to you, then you can check it and if it was good enough, you could included in your next push :)

**Comment by anthonyjb** [comment]
No problem, so my advice would be as follows:

- You need to change the ContentTools.ImageDialog class to support a URL `input` field and a 'Fetch' button. These additional DOM elements should be added in the [`mount`](https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/dialogs/image.coffee#L88) method. There should be examples of doing this in the existing code
- You'll then need to listen for either the the `Fetch` button to be pressed, this code should go in the [`_addDOMEventListeners`](https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/dialogs/image.coffee#L277) method. You might also want to consider monitoring the input box (using the `input` event) to check it's content is valid and only enable the 'Fetch' if it is.
- When a user uploads an image the associated image handler class will receive the `imageUploader.fileReady` event, we'll need something similar in place for the URL fetch, for example on the user pressing the 'Fetch' button consider triggering the event `imageUploader.fetchURL` against the image handler and parsing it the contents of the URL input field, e.g:

```coffeescript
    @_domFetchButton.addEventListener 'click', (ev) =>
        url = @_domURLInput.value
        @trigger('imageUploader.fetchURL', url)
```

- In turn you'll then need to listen for that event within you're image handler, how you fetch the image will depend on your implementation but I would imagine you'll submit the URL as an AJAX request (similar to how you would submit and image file) and wait for details of the image to be returned before populating the dialog.

Hope that all makes sense shout if you want me to expand on any of it.

**Comment by Eeliya** [comment]
[image.zip](https://github.com/GetmeUK/ContentTools/files/104724/image.zip)



I attached my dialogs/image.js. It is written in javascript. Sadly online js to coffee converters do not convert it properly to needed coffee.

I also changed the following css to put the upload button at the center
```css
.ct-widget .ct-control--upload {
  overflow: hidden;
  position: absolute;
  top: 60%;
  left: 50%;
  margin: -16px -50px;
}

/* hide button when image is populated or an image is being uploaded */
.ct-widget.ct-image-dialog--uploading .ct-control--fetch {
  display: none
}

.ct-widget.ct-image-dialog--populated .ct-control--fetch {
  display: none
}
```

I hope you will like it and use it :)

![image](https://cloud.githubusercontent.com/assets/8050688/12577334/05ac16ae-c41a-11e5-818b-e65abd5d0b2f.png)

**Comment by anthonyjb** [comment]
Thanks @Eeliya that's a really nice UI solution :+1:

**Comment by iamryandrake** [comment]
Hey @Eeliya, I'm using part of your code but I don't see the code working for "Insert" button? Is that present?

**Comment by iamryandrake** [comment]
@anthonyjb Anthony, do you have an approach as to how you'd tackle inserting the HTML image into the editor on clicking the button?

Thanks!

**Comment by anthonyjb** [comment]
Hi @iamryandrake - I'm not 100% sure what you're asking sorry - the existing insert button would I imagine work the same as it does now? 

Once you hit the **fetch** button you're image manager would be responsible for contacting the server and requesting that image (see my previous comment above regarding this). As with uploading an image file on fetch the server should return a URL and image dimensions that can be used to insert the image (or potentially to contact the server again and manipulate the image).

**Comment by Eeliya** [comment]
Hi @iamryandrake, 

I just tested the insert functionality and it works fine for me

**Comment by iamryandrake** [comment]
Hi @Eeliya + @anthonyjb ,

With the latest code, I didn't have insert working at all for me, so I've just added this:
