### ISSUE TITLE
Moving the edit/save/cancel buttons to toolbox?

### ISSUE THREAD

**Issue by tmikaeld** [GetmeUK/ContentTools#108]
Is there a built-in way to do this? I looked through the code but it was not straightforward to grasp.

**Comment by anthonyjb** [comment]
There's no built in way to do this and the toolbox isn't visible by default until you start editing so in all honesty I hadn't previously considered adding this as a feature. One option is to customize the start/stop process which numerous people have done to date, there is some advice here on the subject:

http://stackoverflow.com/questions/34645700/customise-edit-button-for-contenttools/34660462#34660462

And some related questions here:

- https://github.com/GetmeUK/ContentTools/issues/77
- https://github.com/GetmeUK/ContentTools/issues/78

Hope will get you started, and if you decided to take the customize route and need a hand do let me know.

**Comment by tmikaeld** [comment]
Thanks, this worked great and i can manually trigger a save.
