### ISSUE TITLE
Q: Is it possible to select all content by pressing Ctrl+A (Cmd+A) and then delete it?

### ISSUE THREAD

**Issue by MalyshevDmitry** [GetmeUK/ContentTools#11]
Is it possible to select all content by pressing Ctrl+A (Cmd+A) and then delete it? I can't do it.

**Comment by anthonyjb** [comment]
@MalyshevDmitry I'm afraid not :( It's a drawback of the approach I'm using which is that at any one point only a small section of the content of the page is actually `contenteditable`, all the other elements on the page are just in there native state. 

You can drag content blocks to new locations and delete them using the `delete` tool, but if your looking to select all the content on the page and the delete it then that isn't possible (though a short cut tool to delete all content in a reigion or all regions would be easy to add), a similar limitation is that it's not possible to select across two separate content blocks either. 

In practice I haven't found this a significant drawback (well I haven't really noticed it for example whilst putting the site content together), but that's just my experience.

If you wanted to just select all content on the page you can while the editor is not active of course.
