### ISSUE TITLE
Attributes with quotation marks in the value get busted on attributesToString

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#111]
For example if you have a background image in the style attribute:

    elem.attr( 'style', 'background-image: url("http://somepath.to/image.jpg")' );

or even without the quotes since they get added when you get the attribute:

    elem.attr( 'style', 'background-image: url(http://somepath.to/image.jpg)' );

Upon saving, the quotes breaks the output of the function `attributesToString` into

    style="background-image: url(&quot;&quot;);" http:="" somepath.to="" image.jpg=""

Here's my fix:

	(function() {
		var proxied = window.ContentEdit.attributesToString;
		window.ContentEdit.attributesToString = function( attributes ) {
			for ( var i in attributes ) {
				if ( typeof attributes[ i ] === 'string' ) {
					attributes[ i ] = attributes[ i ].replace( /\"/g, '\'' );
				}
			}
			return proxied.call( this, attributes );
		};
	})();

**Comment by anthonyjb** [comment]
@bfintal hey bud I'm not getting this exact error I'm getting a different one. I don't believe there should be an issue with replacing `"` with `&quot;` within HTML attributes but at the moment the editor isn't escaping attributes - so setting a background image as per your first example causes the editor to output the HTML with attributes that are unescaped e.g `style="background-image: url("http://somepath.to/image.jpg")"`. At least that's what I'm seeing output from the editor.

I believe CT should just be escaping attributes when they're set against the element, will have to take a look at this today and get something in place.

**Comment by bfintal** [comment]
I can see that too, but that's while I'm editing. I see the broken output when I stop editing and when everything gets unmounted.

You can see this if you feed this object into the `attributesToString` function:

```{
    'style': 'background-image: url("http://somepath.to/image.jpg")'
}```

**Comment by anthonyjb** [comment]
@bfintal I think that should fix the issue now. Basically similar to your approach I've updated the `attributesToString` function in the ContentEdit library only instead of replacing `"` with `'` I escape the output (including quotes with `&quot;`) which I think is the correct behaviour.

**Comment by bfintal** [comment]
:+1:
