### ISSUE TITLE
Moving a non-editable part

### ISSUE THREAD

**Issue by dirkjacobs** [GetmeUK/ContentTools#112]
Hi, 

I created a page with 2 editable parts and 1 non-editable part
Is there a possibility to move the editable part below the non-editable part

**Comment by anthonyjb** [comment]
Have you tried using a [static](http://getcontenttools.com/demo#static-content) element? You can drop static elements into editable regions and then drag and drop them content around them. At the moment you can't drag the elements themselves as static elements can contain anything and the drag-drop handling code could easily clash - though this is something we've looked at.

To create the static element simply add an attribute to the static element like so:

```html
<div class="my-non-editable-content" data-ce-tag="static">...</div>
```

If this doesn't resolve the issue can you paste your source code, there are a number of circumstances this wont work for and support for an option to be able to dynamically control regions within a page is something we're looking at for the future - https://github.com/GetmeUK/ContentTools/issues/13.

**Comment by dirkjacobs** [comment]
Yes,
this seems to work and I think for my use-case is possibly good enough.

Tx
