### ISSUE TITLE
Code at the end

### ISSUE THREAD

**Issue by cesarve77** [GetmeUK/ContentTools#114]
If my last entry on editable zone is a code  then i can't easily insert new content after code.

again sorry for my english.

and congrats for this great tool and really beautiful and clean api

**Comment by anthonyjb** [comment]
@cesarve77 thanks for the kind words - does this comment relate to your previous issue or is this a new issue?

**Comment by cesarve77** [comment]
is a new issue

2016-01-27 13:36 GMT-04:30 Anthony Blackshaw <notifications@github.com>:

> @cesarve77 <https://github.com/cesarve77> thanks for the kind words -
> does this comment relate to your previous issue or is this a new issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GetmeUK/ContentTools/issues/114#issuecomment-175775744>
> .
>



-- 


César Ramos
Av. Romúlo Gallegos
Centro Gerencial los Andes.
Ofc 6D. Boleita. Caracas
04141400601
02129352802

**Comment by anthonyjb** [comment]
Can you provide a few more details it's not clear from what you've added what the issue is - the issue appears to be formatted incorrectly which might not be helping, after the word 'then' everything is appearing monospace?

**Comment by anthonyjb** [comment]
A the `<code>` tag was hidden - I've modified your comment to escape it. Can you send a screenshot showing this please?

**Comment by cesarve77** [comment]
a screenshot will not show the problem.

Let men try explain better with a example

just create a editable zone. edit inserting only a <code> </>  save it, and
edit again, intent to add a paragraph after de code

2016-01-27 14:34 GMT-04:30 Anthony Blackshaw <notifications@github.com>:

> A the <code> tag was hidden - I've modified your comment to escape it.
> Can you send a screenshot showing this please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GetmeUK/ContentTools/issues/114#issuecomment-175797069>
> .
>



-- 


César Ramos
Av. Romúlo Gallegos
Centro Gerencial los Andes.
Ofc 6D. Boleita. Caracas
04141400601
02129352802

**Comment by anthonyjb** [comment]
OK I'm really sorry but I'm still struggling to repeat the issue you're describing - can you paste the HTML here?

**Comment by cesarve77** [comment]
check https://drive.google.com/file/d/0B9cNo8W9ubq0VWNqOXNfY1dpdU0/view

2016-01-27 14:47 GMT-04:30 Anthony Blackshaw <notifications@github.com>:

> OK I'm really sorry but I'm still struggling to repeat the issue you're
> describing - can you paste the HTML here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GetmeUK/ContentTools/issues/114#issuecomment-175805742>
> .
>



-- 


César Ramos
Av. Romúlo Gallegos
Centro Gerencial los Andes.
Ofc 6D. Boleita. Caracas
04141400601
02129352802

**Comment by anthonyjb** [comment]
This is perfect thank you - the solution is to hold the `Ctrl-key` down (`Cmd` on Apple) and click the (P)aragraph tool, this will create a new paragraph rather and converting the current editable block.

There's a note on it here on the demo page http://getcontenttools.com/demo#adding-and-converting-content

**Comment by cesarve77** [comment]
ohh thanks so much for your time

2016-01-27 15:07 GMT-04:30 Anthony Blackshaw <notifications@github.com>:

> This is perfect thank you - the solution is to hold the Ctrl-key down (Cmd
> on Apple) and click the (P)aragraph tool, this will create a new paragraph
> rather and converting the current editable block.
>
> There's a note on it here on the demo page
> http://getcontenttools.com/demo#adding-and-converting-content
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GetmeUK/ContentTools/issues/114#issuecomment-175814955>
> .
>



-- 


César Ramos
Av. Romúlo Gallegos
Centro Gerencial los Andes.
Ofc 6D. Boleita. Caracas
04141400601
02129352802

**Comment by anthonyjb** [comment]
NP - let me know if you have any issues with it :+1:
