### ISSUE TITLE
Clicking on an empty paragraph in Firefox makes the element untype-able

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#116]
You can see this in the demo also, if you create an empty paragraph (press enter), then click on the new blank element the cursor moves to the right side of the highlighted area. Then you won't be able to type in it unless you click on another element.

**Comment by anthonyjb** [comment]
Interestingly this only happens if you create a new element and click it, if you empty the element and click it FF behaves as expected.
