### ISSUE TITLE
Using tools make you lose focus in Firefox

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#117]
In Chrome, when you're typing then use a tool (e.g. heading), `restoreState` brings back the cursor to the previous position prior to using the tool. In Firefox you just lose the focus and it doesn't come back.

**Comment by anthonyjb** [comment]
This issue is both chrome and firefox but as far as I can tell it only occurs if there hasn't been a change of element between changes, e.g this doesn't happen if you select an element change its content, select another element make it a heading then undo - at least for me this works for the first undo but the very last undo never reverts the selection.

**Comment by bfintal** [comment]
So far in my tests I only see this in Firefox (which is frustrating), it works great in mine in Mac Chrome, although I haven't tested in a Windows system.

I'm creating tools and when I do a `storeState` then `restoreState` after I perform the changes, everything works in Chrome. In Chrome I can type something, hit a tool, then continue on typing. In Firefox however, you can't continue.

**Comment by anthonyjb** [comment]
I'm using Chromium on Ubuntu so I guess that might make a difference as I can still get the same issue (but I've yet to find a difference in behaviour between them).

**Comment by anthonyjb** [comment]
Ah my bad can now replicate the issue on FF exactly was just misreading your original report :/

**Comment by anthonyjb** [comment]
OK I'm not sure why but it seems like preventing the default event for mouse up and down on FF doesn't prevent focus loss so I've added a check to ensure that focus is set for elements when restoring the selection state.

**Comment by bfintal** [comment]
Just tried it, it doesn't seem to be working for me

**Comment by anthonyjb** [comment]
I'm testing against the sandbox I haven't yet updated the demo on the website - did you pull down?

**Comment by anthonyjb** [comment]
Ah your right it still has an issue, I don't think my change has been applied - will resolve it now.

**Comment by anthonyjb** [comment]
Dumb mistake - I last second added an if test to prevent focus being called on a focused element but managed to put in a double negative - and didn't test in FF. That should be OK now, have tested it in the sandbox in FF before pushing.

**Comment by bfintal** [comment]
It now works! Thanks! :+1:
