### ISSUE TITLE
Edit plain text without html markup

### ISSUE THREAD

**Issue by shvetsovdm** [GetmeUK/ContentTools#118]
Is there a way to edit just block of text without html markup?

**Comment by anthonyjb** [comment]
Are you talking about within a text element (e.g a p tag), so the content could still be styled overall but there wouldn't be any option to apply markup to text within the element?

**Comment by shvetsovdm** [comment]
exactly

**Comment by shvetsovdm** [comment]
For example when I want to edit h1 tag. I just want to edit h1 text without allowing to editing markup.

**Comment by anthonyjb** [comment]
So no at the moment there isn't a way to do this through the framework, this question has been asked previously though here: https://github.com/GetmeUK/ContentTools/issues/79 and there is some advice on how to approach the problem for now.

**Comment by shvetsovdm** [comment]
Cool, then I'll close this question.

**Comment by shvetsovdm** [comment]
> Are you talking about within a text element (e.g a p tag), so the content could still be styled overall but there wouldn't be any option to apply markup to text within the element?

@anthonyjb I interpreted your question wrong. What exactly I want is to have a ContentEdit.Region that as a whole can acts as a form input text field or a textarea field. And of course solution for disabling ToolUI is also applicable to that type of Regions.

**Comment by anthonyjb** [comment]
OK so if we're talking about the region would that mean you still want paragraphs when people hit return?  Would is the advantage over using a styled textarea?

**Comment by shvetsovdm** [comment]
Nope. No paragraphs after pressing return.

> Would is the advantage over using a styled textarea?

Sorry. Not sure that I understand question.

The reason why I think about this new behavior for Regions is because every region in our app is related with one DB column and I want to be able to edit title as a text string and body as html markup.
