### ISSUE TITLE
Built-in way of changing _supportsCoding within PropertiesDialog?

### ISSUE THREAD

**Issue by Zetal911** [GetmeUK/ContentTools#119]
I want to prevent users from using the HTML editing directly via the PropertiesDialog tab. Is there any way to do this without changing the content-tools.js file? Excuse my ignorance if such is required, I'm still fairly new to Javascript.

**Comment by anthonyjb** [comment]
The simplest approach would be to hide the icon to select the code tab using CSS, for example:

```
.ct-control--code {
    display: none !important;
}
```

It's not the prettiest of solutions but it is simple.
