### ISSUE TITLE
demo code error

### ISSUE THREAD

**Issue by twn39** [GetmeUK/ContentTools#12]
![2015-09-17 22 04 32](https://cloud.githubusercontent.com/assets/1572872/9935340/996f2758-5d88-11e5-8768-0e1af3fd8cdd.png)

`status == '200'`  maybe it's `ev.target.status == '200'`, otherwise it always display the fork flash ui

link:http://getcontenttools.com/getting-started

**Comment by anthonyjb** [comment]
Fixed - thanks for the hint your suggestion was correct.

**Comment by twn39** [comment]
don't forget this page :)
http://getcontenttools.com/tutorials/saving-strategies

**Comment by anthonyjb** [comment]
@twn39 thank you! :)
