### ISSUE TITLE
Youtube video inside a div or p element

### ISSUE THREAD

**Issue by bshorrosh** [GetmeUK/ContentTools#124]
Is it possible to embed a youtube video inside a div or p element?

**Comment by anthonyjb** [comment]
Hi @bshorrosh,

So simple answer - not really through as is, more complex answer yes you can but you need to modify the editors behaviour somewhat.

The cleanest approach might be to modify the way the ContentEdit.Video works to wrap the output in the element you want it to, I can provide some example code for this but just to check - do you always want the video wrapped in an element (e.g `div`/`p` tag) or will it vary (as that's a slightly more complex proposition).

**Comment by bshorrosh** [comment]
Hi Anthony,
Yes, I need the video to always be wrapped in an element; preferably a div element.
An example will be very much appreciated.

Many thanks.

**Comment by anthonyjb** [comment]
So below is an example of how to *patch* the the `ContentEdit.Video` class to provide this functionality, it maybe neater to override the class and modify the `ContentTool.Tools.Video` behaviour, but this is the quickest approach and should serve as a reasonable basis for either approach (it looks neater in coffee but I don't know which you are using and most people use JS so I stuck with that for the example).

```javascript
// Patch the behaviour of the Video `html` method to wrap the iframe output
ContentEdit.Video.prototype.html = function (indent) {
    var indent;
    if (indent == null) {
        indent = '';
    }

  // Return a HTML string for the node
    if (this.tagName() == 'video') {
        return ContentEdit.Video.__super__.html.call(this, indent);
    } else {
        // Wrap the returned string in a div tag
        return indent + '<div class="video-wrapper" data-ce-tag="video">' +
            "<" + this._tagName + this._attributesToString() + ">" +
            "</" + this._tagName + ">" +
            "</div>";
    }
}

// Patch the behaviour of the Video `html` method to cater for a wrapped video
var _innerFromDOMElement = ContentEdit.Video.fromDOMElement;
ContentEdit.Video.fromDOMElement = function (domElement) {
    var iframe = domElement.querySelector('iframe');
    if (iframe) {
        return _innerFromDOMElement.call(this, iframe);
    } else {
        return _innerFromDOMElement.call(this, domElement);
    }
}
```

This outputs an `iframe` wrapped in a `div` with the class `video-wrapper`. The `data-ce-tag="video"` attribute is used so the editor knows to treat the `div` as a video.

---

Regarding the video's representation in edit mode, this is a little more tricky so before I offer up an example patch for the `mount` method I just want to check what you want exactly. In edit mode videos are represented by a single `div` element with no child nodes. Is it enough for this element in edit mode to have the `video-wrapper` class or do you need a `div` element within it. If you could provide some context for what you are trying to achieve with the wrapper in edit mode that would be useful in recommending the best approach :)

**Comment by bshorrosh** [comment]
Anthony, you're awesome. 
The provided sample worked as expected; no further implementations are needed. Thank you.
You may consider enabling dragging and resizing div/p elements similar to images/videos.
This is a great tool with much potential; thank you for sharing it with us.
