### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by Schweinepriester** [GetmeUK/ContentTools#125]
Hi,

at first: Thanks for creating this editor! :)

I wasn't able to find a version or changelog, therefore:
Are there any plans to implement some form of versioning, e.g. using tags?
Would be very useful to us.

**Comment by anthonyjb** [comment]
Hi @Schweinepriester thanks for the kind comments :)

Internally we use milestones to flag what will be in an upcoming release and so my intention was to use the same approach, and at the same time that would lend itself nicely to a changelog. The first milestone was planned to be when all the tests where complete but I simply have gotten that far yet unfortunately.

I'm fairly new to git (convert from Mercurial) so I've not used tags much but I'll have a read up on them and how they could be used.

I'm very happy to hear suggestions from yourself and others on the best route to take :)

**Comment by guillaumepiot** [comment]
Just a thought:

I tend to use commits to manage dependencies on older projects, because creating tags can be time consuming in a sense that they have to be fully tested to earn their name!

Tags are a great way to flag milestone though. I think they will be useful once the lib becomes available on node, and people will be compiling it as part of their project code. Eg:

```
npm install contenttools@1.0
```

NPM is in the pipeline I believe?

**Comment by anthonyjb** [comment]
@guillaumepiot - Yep NPM is in the pipeline (and your down to help me with that lol :D )

**Comment by guillaumepiot** [comment]
@anthonyjb Ahah that's true! That's for the next dev day.

**Comment by Schweinepriester** [comment]
> Internally we use milestones to flag what will be in an upcoming release and so my intention was to use the same approach, and at the same time that would lend itself nicely to a changelog. The first milestone was planned to be when all the tests where complete but I simply have gotten that far yet unfortunately.

> […]

> I'm very happy to hear suggestions from yourself and others on the best route to take :)

Alright, thanks, milestones are good! :)

Also looking forward to NPM.

Closing this issue as my question is answered.
