### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by shockdot** [GetmeUK/ContentTools#127]
I'm trying to rebuild ContentTools, but when I try to use the newly generated content tools I get the a bunch of JS errors.

Uncaught TypeError: Cannot read property 'prototype' of undefined
chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://pkedcjkdefgpdelpbcmbmeomcjbeemfm/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://fjhoaacokmgbjemoflkofnenfaiekifl/cast_sender.js Failed to load resource: net::ERR_FAILED
sandbox.js:142 Uncaught TypeError: Cannot read property 'add' of undefined

I want to add a <small> tool to the content tools (that's why I'm doing this), but even if I rebuild a CLEAN unedited version I get these errors...

**Comment by anthonyjb** [comment]
Hi @shockdot, the `chrome-extension://` errors are I believe to do with the youtube video on the sandbox page. There's some additional information on what causes this here: http://stackoverflow.com/questions/24490323/google-chrome-cast-sender-error-if-chrome-cast-extension-is-not-installed-or-usi

To test this remove The `content-tools.js` include from the sandbox page and see if you still get the errors, if so it's unrelated (this is what I did just to reassure myself and the errors disappear). 

However the `Cannot read property prototype` issue is most likely an issue in your build of content tools. I've pull fresh copies of the repo this morning and checked I can build cleanly and there are no issues running `grunt jasmine` or in the `sandbox.html` page so I'm at a loss to what might be causing your issue. 

If you can post your `content-tools.js` file and the line number for the error `Uncaught TypeError: Cannot read property 'prototype' of undefined` as well as your `sandbox.js` file I'll happily investigate further. 

If I can offer any help/advice on adding your tool please let me know.

**Comment by bfintal** [comment]
I can confirm that the `cast_sender.js` errors are from the YT video.

**Comment by shockdot** [comment]
Hi @anthonyjb I've uploaded my rebuilt content tools (this one has the <small> tool added to it, at least it should).

Here's the upload.
https://volafile.io/r/tyX6Dg

Line that causes the prototype undefined error...(Line 5913) (in content-tools.js
__extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },

Line that causes add error... (Line 143) (in sandbox.js)
    ContentTools.StylePalette.add([new ContentTools.Style('By-line', 'article__by-line', ['p']), new ContentTools.Style('Caption', 'article__caption', ['p']), new ContentTools.Style('Example', 'example', ['pre']), new ContentTools.Style('Example + Good', 'example--good', ['pre']), new ContentTools.Style('Example + Bad', 'example--bad', ['pre'])]);

**Comment by anthonyjb** [comment]
@shockdot could you also include the coffeescript or JS just for the tool you're adding?

**Comment by anthonyjb** [comment]
Looking at your source file my initial thoughts are that you seem to be including your new tool code before the `ContentTools.Tool` class is defined, can you post your Gruntfile.coffee here, or at least just the `coffee:` section please so I can see the order your building in.

**Comment by shockdot** [comment]
@anthonyjb I uploaded the grunt file to the same upload link above.
https://volafile.io/r/tyX6Dg

I don't think this is the issue.. because... While I uploaded the content tools build with my tool, I also tried to simply do a clean build with no changes which produced the same errors.

**Comment by anthonyjb** [comment]
OK I can't reproduce a build error on a clean download at the moment (but I am going to check this again - we have pushed some changes since your report so perhaps something is going on), but my recommendation would be that you include the tool at the end of the build process not at the start as this will definitely fail with a `prototype` error as described because the base class wont exist yet.

```
            build:
                files:
                    'src/tmp/content-tools.js': [
                        'src/scripts/namespace.coffee'
                        
                        # UI
                        'src/scripts/ui/ui.coffee'
                        'src/scripts/ui/flashes.coffee'
                        'src/scripts/ui/ignition.coffee'
                        'src/scripts/ui/inspector.coffee'
                        'src/scripts/ui/modal.coffee'
                        'src/scripts/ui/toolbox.coffee'

                        # UI - Dialogs
                        'src/scripts/ui/dialogs/dialogs.coffee'
                        'src/scripts/ui/dialogs/image.coffee'
                        'src/scripts/ui/dialogs/link.coffee'
                        'src/scripts/ui/dialogs/properties.coffee'
                        'src/scripts/ui/dialogs/table.coffee'
                        'src/scripts/ui/dialogs/video.coffee'

                        # Other
                        'src/scripts/editor.coffee'
                        'src/scripts/history.coffee'
                        'src/scripts/styles.coffee'
                        'src/scripts/tools.coffee'

                        # Custom Tools
                        'src/scripts/small-tool.coffee'
                    ]
```

**Comment by shockdot** [comment]
Very very strange... that seemed to work, although I'm missing all the icons now haha. I guess I was running a cached version of the script or something... I dunno.
