### ISSUE TITLE
Inline Image Editor

### ISSUE THREAD

**Issue by dantejauregui** [GetmeUK/ContentTools#128]
Hello team!

Do you know if exist any way to use an image inline editor? Like is showed below

Please check the image attached  :)

We think that feature it would be really interesting, cause many writers wants to edit just the multimedia resources, so in case you dont have any plan to develop it in the near future, we would like to help you :)

![inline image editor](https://cloud.githubusercontent.com/assets/10466343/13053411/7ce2b7ce-d3eb-11e5-842d-0d605bb27e80.PNG)

**Comment by dantejauregui** [comment]
My friend @johnidm and me are really interested in support you,

cheers!

**Comment by anthonyjb** [comment]
Hi @dantejauregui  and @johnidm - thank you for your support :+1: 

Can you highlight what features you're looking to provide. I can't see from the image anything that isn't already supported by CT but I might well be missing something, with CT you can currently:

- Resize images
- Move images (including aligning them)
- Set attributes against images via the properties dialog (such as alt tags or additional classes/styles)

If you would like to implement a pop-up menu then potential @bfintal could help here as I know he's done something similar for his wordpress plugin.

**Comment by anthonyjb** [comment]
BTW Thank you very much for offering to support the project I could certainly use the extra help as there is a lot to do still!

**Comment by dantejauregui** [comment]
Yeah @anthonyjb  we were thinking about the "pop-up menu"  to move to the left center and right  position  the multimedia resources :)   like in the picture attached

@bfintal nice to meet you!, is it true that u have a project related about a "pop up menu"?? :) 



Keep in touch! 
@jonhidm and me are sending warm regards   :)

**Comment by bfintal** [comment]
Hey @dantejauregui Yup, I've been developing Page Builder Sandwich for quite a while now https://pagebuildersandwich.com
