### ISSUE TITLE
Does ContentTools have a non-inline setting?

### ISSUE THREAD

**Issue by shockdot** [GetmeUK/ContentTools#130]
I want to use ContentTools in a form that I'm making, it's for adding news articles.

I want to have normal inputs for the Title and Date of the news, but have a ContentTools container for the news content/body input.

Does ContentTools have a non-inline setting that can be enabled?

**Comment by shvetsovdm** [comment]
Hi @shockdot. Looks like you want the same as #118.

**Comment by anthonyjb** [comment]
Hi @shockdot as @shvetsovdm commented this isn't a feature of ContentTools currently but has been discussed. I can't see it being a short term goal for the library unless it's taken up by others but I'd have no objection to this becoming a feature.
