### ISSUE TITLE
Option to edit inline element (such as a header)?

### ISSUE THREAD

**Issue by Qqwy** [GetmeUK/ContentTools#132]
Hello there!

First, let me say that this is an amazing project. It is the nicest solution to the WYSIWYG-problem I've seen thus far. Although, of course, some things are still missing or behave oddly.

From the docs:

>A common misunderstanding when marking up editable HTML is to mark up a single element as editable, for example:
>    `<h1 data-editable data-name="heading">Content</h1>`
>This wont work as a region has to contain editable block level elements. A simple way around this is to wrap the h1 tag like so:
>    `<div data-editable data-name=heading>`
>    `    <h1>Content</h1>`
>    `</div>`

In my project, I want to give users the ability to edit some elements without allowing them to create new block elements above/below it, and without changing the overall style of this element. An example would be the header (`h1`) of their page:

- I want them to be able to use bold/italics/underlines in there, as well as colours.
- I do not want them to be able to change the `h1` to a `h2`, `h3` or `p` tag.
- I do not want them to be able to use the return key to start new block elements below the h1.
- I do not want them to be able to insert lists/tables/images in there.

Is it possible to change the options to support this behaviour right now?

**Comment by anthonyjb** [comment]
Hi @Qqwy, thank you for your kind comments. Support for making greater control over editable regions/elements (such as a H1) and for limiting the tools that can be used when editing these has been raised in a number of existing issues:

- https://github.com/GetmeUK/ContentTools/issues/79
- https://github.com/GetmeUK/ContentTools/issues/118
- https://github.com/GetmeUK/ContentTools/issues/130

It's something that our clients (getme) would like to have in place to so support is planned, but as per your question no there is no support currently and work creative arounds must be implemented.
