### ISSUE TITLE
How to find out if editor is currently open or not?

### ISSUE THREAD

**Issue by Qqwy** [GetmeUK/ContentTools#134]
Basically, I want to highlight certain elements in a similar fasion as the ContentTools editor itself does when the editor is open, but open a modal when they are clicked. (e.g. when a `product` is clicked, the user sees a modal with all settings they can change for that product)

For this, I need to be able to know if the editor is open at a certain time or not. I did not find anything in the docs. Is there a way to do so?

**Comment by Qqwy** [comment]
Hmm. It seems that `editor._state` is a string saying either `ready` or `editing`.

Although I of course dislike calling a private property directly. 

I propose the following new methods:
- `editor.getState()`
- `editor.isEditing()`
- `editor.isReady()`

**Comment by anthonyjb** [comment]
Hi @Qqwy,

I agree we should add support for a `getState()` method against the editor and I will document the various states so that it's clear what each means.

**Comment by bfintal** [comment]
Here's what I'm doing right now to check states.

```
var editor = ContentTools.EditorApp.get();
editor.bind('start', function() {
	// CT just started.
});
editor.bind('stop', function() {
	// CT just stopped.
});
var starterInterval = setInterval( function() {
	if ( document.querySelector( '.ct-widget--active' ) ) {
		clearInterval( starterInterval );
		// CT is now ready.
	}
}, 200);
```

**Comment by anthonyjb** [comment]
OK the new functionality from this pull request is now in place and documented http://getcontenttools.com/api/content-tools#editor-app

**Comment by bfintal** [comment]
How about editor events? :)
