### ISSUE TITLE
Not enable to view the image after upload

### ISSUE THREAD

**Issue by Portekoi** [GetmeUK/ContentTools#135]
Hello,

In trying to test this framework with php. The upload is running and the image dialog box close normally. The image file is save in the server. It's OK.
But the image is not visible. In the source code, the width and the height are not transmit.

I've try to delete all unneeded js/css file but I've the same issu : image do not appear.

I've take the last version, follow the instructions on this page : http://getcontenttools.com/tutorials/handling-image-uploads but nothing....

Here is my online code : http://portekoi.com/contentools/

My "form.php" php file : 

    $postData = $_FILES;
    $target_dir = "";
    $temp_file = $target_dir . basename($_FILES["image"]["name"]);
    $uploadOk = 1;
    $imageFileType = pathinfo($temp_file,PATHINFO_EXTENSION);
	$file_name = "";
	$file_name = basename($_FILES["image"]["name"], "." . $imageFileType) . "-" . rand(0, 10000) . "." . $imageFileType;
	$target_file = $target_dir . $file_name;
    // Check if image file is a actual image or fake image
    if(isset($_POST["submit"])) {
        $check = getimagesize($_FILES["image"]["tmp_name"]);
        if($check !== false) {
            echo "File is an image - " . $check["mime"] . ".";
            $uploadOk = 1;
        } else {
            echo "File is not an image.";
            $uploadOk = 0;
        }
    }
    // Check if file already exists
    if (file_exists($target_file)) {
        echo "Sorry, file already exists.";
        $uploadOk = 0;
    }
    // Check file size
    if ($_FILES["image"]["size"] > 1500000) {
        echo "Sorry, your file is too large.";
        $uploadOk = 0;
    }
    // Allow certain file formats
    if($imageFileType != "jpg" && $imageFileType != "png" && $imageFileType != "jpeg"
    && $imageFileType != "gif" ) {
        echo "Sorry, only JPG, JPEG, PNG & GIF files are allowed ==> " . $imageFileType;
        $uploadOk = 0;
    }
    // Check if $uploadOk is set to 0 by an error
    if ($uploadOk == 0) {
        echo "Sorry, your file was not uploaded.";
    // if everything is ok, try to upload file
    } else {
        if (move_uploaded_file($_FILES["image"]["tmp_name"], $target_file)) {

            $arr = array('size' => array('width' => 600, 'height' => 400 ), 'url' => 'http://www.portekoi.com/contenttools/'.$file_name.'');
            echo json_encode($arr);

        } else {
            echo "Sorry, there was an error uploading your file.";
        }
    }

and my save php file : 
        

    $items = list($width, $height) = getimagesize($_POST['url']);

    $arr = array('url' => $_POST['url'], 'width' => $_POST['width'], 
     'alt'=> "Image", 'size' => array('width' => $items[0], 'height' => $items[1] ));
    echo json_encode($arr);

Sample result in json : 

    {"url":"http:\/\/portekoi.com\/contentools\/test-2703.jpg","width":"600","alt":"Image","size":{"width":775,"height":587}}

Can you help me?

I've done something wrong maybe but I don't know what.

**Comment by Portekoi** [comment]
I've found my mistake. In the save.php, change this : 

    $arr = array('url' => $_POST['url'], 'width' => $_POST['width'], 
     'alt'=> "Image", 'size' => array('width' => $items[0], 'height' => $items[1] ));

by this : 

    $arr = array('url' => $_POST['url'], 'width' => $_POST['width'], 
     'alt'=> "Image", 'size' => array($items[0], $items[1] ));

**Comment by anthonyjb** [comment]
Hi @Portekoi thanks for updating the issue and letting me know and sorry I hadn't gotten around to answering the question sooner.

**Comment by Portekoi** [comment]
Hi @anthonyjb thanks for your reply. No problem. I really want to use your project but my interface is using bootstrap and as you can see on this link, http://portekoi.com/contentools/ , if you edit the button "view detail", you lost the Bootstrap style button :(
So, i don't know how to do that. Thanks again. Really nice work.

**Comment by anthonyjb** [comment]
Hi @Portekoi can you explain the issue you're having a little further, I managed to edit the content s without too much issue: 
![image](https://cloud.githubusercontent.com/assets/3046287/13149708/6aac134a-d65a-11e5-9a12-df39783fc3f4.png)

Having said that if you remove all content from the button then it will disappear, one way to solve this is to add a style to the editor for the button (http://getcontenttools.com/getting-started#configure-styles) so that user can convert the block to a button (rather than an inline element).

**Comment by Portekoi** [comment]
It's ok with the lastest version.
