### ISSUE TITLE
Q: How show 2 different toolboxes when editing 2 different regions?

### ISSUE THREAD

**Issue by Folo4ka** [GetmeUK/ContentTools#142]
Hello, how show 2 different toolboxes when editing 2 different regions without init 2 different ContentTools on them?

For example, when I edit div with attr data-name="article-content", I see default toolbox with all tools.
And when I edit div with attr data-name="article-annotate", I see toolbox with 'italic' and 'link' tools only.

Thanks.

**Comment by anthonyjb** [comment]
Hi @Folo4ka thanks for your question, this is the topic of some debate and development currently and you can find more information against the following post https://github.com/GetmeUK/ContentTools/issues/79.

Currently it's not possible to do this without modifying the library a little bit however support for this feature is planned in the near future.
