### ISSUE TITLE
Unable to align an image in a paragraph

### ISSUE THREAD

**Issue by dirkjacobs** [GetmeUK/ContentTools#143]
Hi, 

after inserting an image, _and the image is the only element in the paragraph_, the image is always aligned in the center.
Is there a possibility to change the alignment of image to left or right ? (as can be done if text is placed next to the image) 

![capture](https://cloud.githubusercontent.com/assets/15648092/13443912/9cb11aa4-e003-11e5-9993-4159f19d9646.PNG)

**Comment by anthonyjb** [comment]
Hi @dirkjacobs the simplest/quickest way would be to define a couple of styles (css classes) for aligning the image in the manner you've described (there's some information here on how to add styles http://getcontenttools.com/getting-started#configure-styles). A user can the use the properties dialog to apply the alignment style they want to the image.

You could of course also change/override this default behaviour so that the image was initially aligned say left by updating the CSS/SCSS.

**Comment by dirkjacobs** [comment]
Hi,

tx for the quick reply. The idea is in fact to have the possibility to 
use the allignment buttons on the palette or have the system with the 
arrows when dragging. (but I would prefer the allignment buttons on the 
palette)
The reason is that for our users the properties dialog is too technical, 
that's the reason I've hidden the properties dialog.

Default behavior for the rest is fine.

D.

**Comment by anthonyjb** [comment]
You could definitely update the alignment buttons to cater for images, so you'd need to revise the Align set of tools here: https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/tools.coffee#L458

So this simplest option would just be to update the `@canApply` method to allow images, e.g:

```coffeescript

@canApply: (element, selection) ->
    # Return true if the tool can be applied to the current
    # element/selection.
    return element.content != undefined or element.type() is 'Image'
```

This would then allow the align tool to apply the `text-left`, `text-right`, `text-center` classes to images. You'd need to do a bit more work if you wanted to apply different classes for images than to text elements but not too much :)

I haven't tried the above so if you come across any issues let me know happy to take a look :)

**Comment by dirkjacobs** [comment]
Would be the perfect solution for me, but I'm afraid  coffeescript is not my 'cup of tea' ;-)

**Comment by anthonyjb** [comment]
Well it's not that different with JS to be honest:

```JavaScript
ContentTools.Tools.AlignLeft.canApply = function (element, selection) {
    return element.content !== undefined || element.type() === 'Image';
}
```

**Comment by dirkjacobs** [comment]
Tried it out and works fine.
Would be nice/perfect if 
- Was the std. behavior
- Generated a different class

**Comment by anthonyjb** [comment]
I don't want to make this the default behaviour at the moment because I think it would lead to confusion between the 2 types of alignment, for our clients at least.

However now that the new event system is in place it should be possible to listen for the alignment tools and modify the behaviour without the need to monkey patch likes this, for example:

```JavaScript
var alignLeftBtn = editor.toolbox()._toolUIs['align-left'];

alignLeftBtn.addEventListener('apply', function(ev) {
    ev.preventDefault();
    var element = ev.detail().element;
    
    ... perform the align stuff you want to do (perhaps check for the element type to determine what class will be applied...

    editor.toolbox().updateTools()
});

```

**Comment by patrikengborg** [comment]
I came up with a nifty little solution for this. I didn't want to clutter the toolbox further and the properties dialog didn't feel like the perfect solution either. So with this script it toggles between alignment classes (defined in const classes) when you double-click the image.

    window.ContentEdit.Root.get().bind('mount', function (element) {
      if (element.type() !== 'Image') return

      const classes = ['img-left', 'img-right', 'img-center']
      const el = element.domElement()

      el.addEventListener('dblclick', function (ev) {
        const currentClass = classes.find(item => el.classList.contains(item))
        const currentIndex = classes.indexOf(currentClass)
        const nextIndex = currentIndex < 0 || currentIndex === classes.length - 1
          ? 0 : currentIndex + 1
        el.classList.remove(currentClass)
        el.classList.add(classes[nextIndex])
      })
    })
