### ISSUE TITLE
Activate editor toolbar immediately after going into edit mode

### ISSUE THREAD

**Issue by Eeliya** [GetmeUK/ContentTools#144]
When I'm in the edit mode, I must click on element in order to the toolbar get activated. 
How can I get the first element focused and active toolbar, immediately after I go inside edit mode

**Comment by anthonyjb** [comment]
Hi @Eeliya,

To focus on the first editable element in the first region on start up you could use the following approach:

```coffeescript
// Select the first editable element when starting to edit
editor.start = function () {
    var editorCls = ContentTools.EditorApp.getCls();
    editorCls.prototype.start.call(this);

    // Select the first editable region
    var firstRegion = this.orderedRegions()[0];

    // Check the region has a child to focus on
    if (firstRegion.children.length > 0) {

        // Select the first element
        var firstElement = firstRegion.children[0];

        // Give the element focus
        firstElement.focus();
    }
}
```

**Comment by Eeliya** [comment]
Thanks, I used your code.

I also add a on click event to the `firstRegion` so when I click on it no matter where, the last element get focused so I don't have to specifically click on a it.

I post my code maybe someone find it handy :)

inside `_EditorApp.prototype._addDOMEventListeners` method I added this: 

    if(this._regions[0]) {
        this._regions[0].addEventListener('click', function (e) {
            _this.focusLastElement(e);
          });
     }

And I created this method:

     _EditorApp.prototype.focusLastElement = function (e) {
      if (e.target !== this._regions[0])
        return;

      var lastChild = this.regions()[0].children[this.regions()[0].children.length - 1];
      if (lastChild) {
        var range = new ContentSelect.Range(lastChild._domElement.innerHTML.length, lastChild._domElement.innerHTML.length);
        lastChild.selection(range);
        lastChild.focus();
      }
    };

**Comment by akshaysinha91** [comment]
Hi Anthony, I used the code 
// Select the first editable element when starting to edit
editor.start = function () {
    var editorCls = ContentTools.EditorApp.getCls();
    editorCls.prototype.start.call(this);

    // Select the first editable region
    var firstRegion = this.orderedRegions()[0];

    // Check the region has a child to focus on
    if (firstRegion.children.length > 0) {

        // Select the first element
        var firstElement = firstRegion.children[0];

        // Give the element focus
        firstElement.focus();
    }
}

Its working fine on general scenario, but if the first element in article is a ul or ol then its giving a error
"Uncaught TypeError: firstElement.focus is not a function"

**Comment by anthonyjb** [comment]
Hi @akshaysinha91,

To give focus to the first text content element the code should be updated to be:

```JavaScript
// Select the first editable element when starting to edit
editor.start = function () {
    var editorCls = ContentTools.EditorApp.getCls();
    editorCls.prototype.start.call(this);

    // Select the first editable region
    var firstRegion = this.orderedRegions()[0];

    // Check the region has a child to focus on
    if (firstRegion.children.length > 0) {

        // Select the first content element
        var firstElement = firstRegion.nextContent();

        // Give the element focus
        firstElement.focus();
    }
}
```
