### ISSUE TITLE
crop-marks not always correct

### ISSUE THREAD

**Issue by dirkjacobs** [GetmeUK/ContentTools#146]
After rotating an image the crop-marks not always appear correctly.
Some investigation I see that bottom-right style is not rendered.

<div class="ct-crop-marks__handle ct-crop-marks__handle--top-left" style="top: 0px; left: 0px;"></div>
<div class="ct-crop-marks__handle ct-crop-marks__handle--bottom-right" style=""></div>

See also screenshots in attach
![crop-marks-1](https://cloud.githubusercontent.com/assets/15648092/13463150/40ec8356-e08b-11e5-9736-448f255beb4e.PNG)
![crop-marks-2](https://cloud.githubusercontent.com/assets/15648092/13463151/40f56502-e08b-11e5-8e8d-2dd4013ad0dd.PNG)

**Comment by anthonyjb** [comment]
Hi @dirkjacobs does this happen every time you rotate an image or only sometimes? Could you post the image in your example here so I can download and attempt to reproduce this issue?

**Comment by dirkjacobs** [comment]
The image I used in attach
![bird](https://cloud.githubusercontent.com/assets/15648092/13463376/42bc0b38-e08c-11e5-9a19-7262aab9dfe0.jpg)
, but this is also the case with other iamges

**Comment by anthonyjb** [comment]
OK so I've tested here and I don't get this issue with this image which makes me think the issue might be in the ImageUploader code. When you update the image after performing the rotate are you passing the new update dimensions of the image? e.g 

```
// Populate the dialog
dialog.populate(image.url, image.size);
```

And if so can you check what the values you are setting are and make sure they are correct.

**Comment by dirkjacobs** [comment]
Found the problem. Sometimes, the image was not fully loaded (async) when trying to retrieve the width and height. This returned [0,0] and caused the wrong crop-marks.
But your hint helped me in finding the solution.

**Comment by anthonyjb** [comment]
Excellent news :+

**Comment by baldram** [comment]
If someone has client-side problem with crop, this comment may be also helpful: https://github.com/GetmeUK/ContentTools/issues/354#issuecomment-298298383 .
