### ISSUE TITLE
Angular with ContentTools: scope.editor.dormant is not a function

### ISSUE THREAD

**Issue by iamryandrake** [GetmeUK/ContentTools#148]
I'm using Angular and ContentTools ([http://getcontenttools.com][1]) in a UI that allows a user to craft a message. I can see in Network tab that relevant files to ContentTools loads:
[![enter image description here][2]][2]

I'm also able to correctly see the 'Message Content' container:
[![enter image description here][3]][3]

    var ContentEditorComponent = (function () {
                function ContentEditorComponent($compile, $timeout, editorService) {
                    var _this = this;
                    this.$compile = $compile;
                    this.$timeout = $timeout;
                    this.editorService = editorService;
                    this.link = function (scope, element, attrs, ngModel) {
                        // Set toolset
                        window.ContentTools.DEFAULT_TOOLS =
                            _this.editorService.getToolsByMessageType('push');
                        if (!scope.editor) {
                            var editorElement = angular.element(document.querySelector('.editor-region'));
                            editorElement.html(scope.content && scope.content.indexOf('<') > -1 ? scope.content : '<p>Enter your message content here</p>');
                            scope.editor = window.ContentTools.EditorApp.get();
                            // Console complains at next line
                            if (scope.editor.isDormant()) {
                                scope.editor.init('[tools-editor]', 'editor-name');
                            }
                            scope.editor._ignition.changeState('editing');
                            scope.editing = true;
                        }
                    }
               }

Here's the console error I am getting ```scope.editor.isDormant is not a function```:
[![enter image description here][4]][4]

So it seems ContentTools fails to initialise at that line. Here's the API document for the editor: [http://getcontenttools.com/api/content-tools][5]. No other function is firing at that line, so bit stuck on how I'd initialise the editor now.

  [1]: http://getcontenttools.com/
  [2]: http://i.stack.imgur.com/jLh3j.png
  [3]: http://i.stack.imgur.com/ARLUl.png
  [4]: http://i.stack.imgur.com/nJ6Xq.png
  [5]: http://getcontenttools.com/api/content-tools

**Comment by anthonyjb** [comment]
Hi @iamryandrake `isDormant` is a recent addition to the library have you pulled from the repo recently?
