### ISSUE TITLE
Allow default enter/return key behaviour to be configured to line-break

### ISSUE THREAD

**Issue by iamryandrake** [GetmeUK/ContentTools#150]
I notice that if you hit enter, it creates a new paragraph. The limitation with this is that you cannot highlight, therefore, across multiple paragraphs. Is there an easier option or way to configure this?

**Comment by anthonyjb** [comment]
No this isn't possible and is a fundemental feature/flaw (perhaps compromise is a better word) with the approach taken to managing content in CT / ContentEdit. This topic has been discussed in the past in particular with regard to deleting content:

- https://github.com/GetmeUK/ContentTools/issues/11
- https://github.com/GetmeUK/ContentTools/issues/41

It's not dead as a possible enhancement if someone wanted to look at adding support for this to the library it would be a popular change, but currently it's not on the more pressing list of upcomming enhancements.

**Comment by iamryandrake** [comment]
So how about binding Shift+Enter to the enter key on keypress?

It's annoying that a user has to hit newline just to stay within the same paragraph! 

Wouldn't that be a simpler approach, but also solve a lot of usability concerns?

**Comment by anthonyjb** [comment]
Hi @iamryandrake you can already press shift enter to remain within the same paragraph, shift enter automatically creates a `br` tag, this was resolved here: https://github.com/GetmeUK/ContentTools/issues/101

**Comment by iamryandrake** [comment]
I understand, however, it's very unintuitive for a user to be in a paragraph, hit enter and that starts a new paragraph for them. Rather, what I'm suggesting, is that the enter key be used to insert <br> tag.

**Comment by anthonyjb** [comment]
OK I see what you're saying now but I'm afraid I don't agree that it's the wrong way around.

Modifier(e.g shift) + return/enter is a pretty standard mechanism in applications (e.g skype, slack) for the line-break short-cut and from a HTML perspective I think the `br` tag is used less often than the paragraph tag, perhaps to list the lines of an address for example, but that it shouldn't be used to separate paragraphs of text.

We could consider a feature that allows this behaviour to be configured against the ContentEdit namespace e.g 'ContentEdit.PREFER_LINE_BREAKS' but by default this wouldn't not be the behaviour?

**Comment by iamryandrake** [comment]
^ To add that option in would be SUPERB!

**Comment by anthonyjb** [comment]
OK - well I've tagged as an enhancement for now and change the title to reflect this, it shouldn't be a huge task so hopefully someone might pick this up before me :) 

For anyone who does want to implement this enhancement you'd want to start here: https://github.com/GetmeUK/ContentEdit/blob/master/src/scripts/text.coffee#L314 in the ContentEdit library.

**Comment by anthonyjb** [comment]
OK thanks to @Qqwy this feature is not supported, docs have been updated http://getcontenttools.com/api/content-edit#settings, but as an example use:

```
ContentEdit.PREFER_LINE_BREAKS = true;
```
