### ISSUE TITLE
Table Row Handling

### ISSUE THREAD

**Issue by Qqwy** [GetmeUK/ContentTools#152]
This issue is loosely connected to #62 . 

Table handling is very finnicky right now.

 - It seems(is?) impossible to remove table rows. My tables often end up with many unused rows at the bottom.
 - It is very hard to move a table, as you need to hold the mouse down for a long time (often selecting either text or starting to drag a row).

I think that a better solution is to add icons after table rows that can be used to delete them. Or, maybe even better, would be to make use of a [changing cursor](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor). I propose:

 - Clicking and holding at the front (left) of a row selects the whole row and allows dragging.
 - Clicking behind (to the right) of a row removes the row (maybe with a confirmation dialog?).

**Comment by anthonyjb** [comment]
Hi @Qqwy,

- Deleting table rows can be achieve by clicking the delete icon while your cursor is in a table cell.
- You have to hold the mouse down for 1 second to move a table currently however you can modify this time by setting the `ContentEdit.DRAG_HOLD_DURATION` settting (by default set to 500ms).

I agree that the enhancements described in issue #62 need to be made they are on the list. 

Adding icons to to the table rows when selected or hovered over isn't something I'd like to see as I'd prefer not to add to the UI if possible. However I think there's merit in trying out your suggestion regarding cursor changing, I'm open to a new approach as opposed to the hold and wait if it feels more intuitive. If you (or anyone else) can provide a working example to trial and we think it's a better experience I'd be happy to include it either as the default behaviour or as an option if opinion is split?

**Comment by anthonyjb** [comment]
@Qqwy we could also try the same approach for lists also as these use the same approach as tables currently.
