### ISSUE TITLE
Example of adding a basic tag to toolbox

### ISSUE THREAD

**Issue by bcreeves** [GetmeUK/ContentTools#154]
I'm trying to figure out how to add extra tags to the toolbox (sup, sub, h3) by following the Add a <time> tool tutorial. I'm not sure if I'm missing something between having to compile with coffeescript or the extra stuff going on in that example because of modals/dialogs. Is there a basic example you could point to for just adding a new tag with vanilla javascript?

Also, can I add the code in a separate js file or does it need to be compiled as part of the full content-tools.min.js build?

Thanks.

**Comment by anthonyjb** [comment]
Hi @bcreeves,

So you can add tools without adding them to the existing build process or `content-tools.min.js`. If you just want to add a tool that wraps some text in say a `sup` tag then I would suggest you inherit from the bold class, here's a quick example as to how in vanilla JS:

```
// CoffeeScript helpers
var __hasProp = {}.hasOwnProperty;
var __extends = function(child, parent) {
    for (var key in parent) {
        if (__hasProp.call(parent, key)) 
            child[key] = parent[key];
    }
    
    function ctor() { 
        this.constructor = child; 
    }
    
    ctor.prototype = parent.prototype;
    
    child.prototype = new ctor();
    child.__super__ = parent.prototype; 
    
    return child; 
};

ContentTools.Tools.Sup = (function(_super) {
    __extends(Sup, _super);

    // This class extends the existing Bold tool    
    function Sup() {
      return Sup.__super__.constructor.apply(this, arguments);
    }

    // Stow the tool so we can reference it later using 'sup'
    ContentTools.ToolShelf.stow(Sup, 'sup');

    // Set the tool tip that will appear
    Sup.label = 'Sup';

    // Set the name of the icon (this wont exist unless you add one)
    Sup.icon = 'sup';

    // Set the tag that will be used to wrap content when pressing this tool
    Sup.tagName = 'i';

    return Sup;

})(ContentTools.Tools.Bold);

// Add the new `Sup` tool in it's own group to the toolbox
ContentTools.DEFAULT_TOOLS.unshift(['sup']);
```

Insert this code anywhere before you initialize the editor and it should work, I tested on the sandbox page and it works fine.
