### ISSUE TITLE
Is it possible to create a element out of a javascript domelement?

### ISSUE THREAD

**Issue by shockdot** [GetmeUK/ContentTools#158]
I need to access the PropertiesDialog, which takes an element argument.

The argument I want to pass I only have access to as a JS dom element.... Is there anyways for me to create a new CT element out of this?

I'm not sure what the CT element class is even really called....

**Comment by anthonyjb** [comment]
@shockdot there's no Element class in CT. CT provides an editor (e.g a set of tools and a UI) but the actual editable elements and the management of a tree of editable elements is provided by the ContentEdit library documented here: http://getcontenttools.com/api/content-edit and available as source here: https://github.com/GetmeUK/ContentEdit.

Even though you could probably generate an editable element on the fly to send the properties dialog, e.g (http://getcontenttools.com/api/content-edit#text):

```
# Create an editable element on the fly
element = new ContentEdit.Text('p', {'class': 'foo'}, 'some content')

# Set up the dialog
modal = new ContentTools.ModalUI()
dlg = new ContentTools.PropertiesDialog(element)

# Show the dialog
ContentTools.EditorApp.get().attach(modal)
ContentTools.EditorApp.get().attach(dialog)
modal.show()
dialog.show()

**Comment by shockdot** [comment]
I have something like this..

`<p>Some text <span>goes here</span and also here</p>`

I've done so using a span tool that ive added myself. Next I've added another tool that opens up the PropertiesDialog, similar to the inspector... However this tool uses the start & end indexes to locate the first level parent of the selected content in the element variable that is fed to all the tools "apply" function.

Now in this case when I use this custom tool, I call it the Properties tool, it should edit the closest inner html tag to the selection. In this case, if I had the word "goes" highlighted when it was pressed it would contain a link to the element <span>goes here</span>.

Now what I expect to be able to do is use this element to create an object of the same type of the "element" variable that is fed into all apply functions in each tool. So that I can create a properties dialog using the selected element and not the root element (p). So when I call the PropertiesDialog, instead of it being for the p tag it will be for the span tag.

Literally I'm done everything and am just missing this one step...

**Comment by anthonyjb** [comment]
@shockdot well you can certainly follow the example from my last comment and specify a span instead of a p tag:

```element = new ContentEdit.Text('span', {}, 'goes here')```

You will have to manually manage the save action for the properties dialog but a `ContentEdit.Text` element wont care what tag name you give it.

**Comment by shockdot** [comment]
I was able to produce the desired functionality by just replacing parts of the element variable like so...

`
      var element_j = $(element._domElement);
      if(element_j)
      {
        selected = $(":contains(" + element._domElement.innerText.substring(from, to) + ")", element_j);
        element._cached = $(selected).html();
        element._domElement = selected[0];
        element._tagName = $(selected).prop("tagName").toLowerCase();
      }
`

Not sure if this is an acceptable solution, or if it will produce unforseen issues. However, I'm starting to test it now. If it all works the only thing left is for me to convert this into coffee(going to take forever since I don't know coffee, if anyone wants to help out and do that for me thatd be great -.-).

**Comment by shockdot** [comment]
Hmm so I tried this...

selected = new ContentEdit.Text($(selected).prop('tagName'), {}, element._domElement.innerText.substring(from, to));

And it didn't produce any errors but it also didn't change anything. I'm assuming this is because we actually only created a completely new ContentEdit.Text instead of create a new one that is linked to the original dom_element...

**Comment by anthonyjb** [comment]
That's correct, you need to manually manage the save action for the properties dialog to update the content of your element per any changes to the inner element.

**Comment by shockdot** [comment]
Okay well that wasn't working out well entirely... So I took to another route... This time I made the properties dialog appear when ever I apply the span element for the first time...

They way it works is...
User selects a section of text, clicks the span element for the first time, properties window opens, they select the class, click apply. Then it adds the tag to the selection. Simple. It works great.

Only issue now is when we try to remove the span element by clicking the span tool again it doesn't remove it...

Not sure why...

This is my code for the apply function... I expected that if the isApplied condition gets thrown that any tag in the selection with span in it gets removed... Unless I'm mistaken and it just does a character match of <span>*wild card*</span>? Which thinking about it now it might....?

```
    @apply: (element, selection, callback) ->
        # Apply the tool to the current element
        element.storeState()

        [from, to] = selection.get()

        if @isApplied(element, selection)
            element.content = element.content.unformat(
                from,
                to,
                new HTMLString.Tag(@tagName)
                )

            element.content.optimize()
            element.updateInnerHTML()
            element.taint()

            element.restoreState()

            callback(true)
        else
            # Set-up the dialog
            app = ContentTools.EditorApp.get()

            # Modal
            modal = new ContentTools.ModalUI()

            # Open a Properties Dialog to choose a class...
            temp_span = new ContentEdit.Text(@tagName, {}, "");
            dialog = new ContentTools.PropertiesDialog(temp_span);

            # Support cancelling the dialog
            dialog.bind 'cancel', () =>
                dialog.unbind('cancel')

                modal.hide()
                dialog.hide()

                if @element.restoreState
                    @element.restoreState()

            # Support saving the dialog
            dialog.bind 'save', (attributes, styles, innerHTML) =>
                dialog.unbind('save')
    
                attributes = {}
                
                classes = "";
                for name, value of attributes

                    # The `class` attribute has to be handled differently from other
                    # attributes as CSS classes should only be set using the
                    # add/removeCSSClass methods.
                    if name == 'class'
                        # If the value is null (marked for remove) default it to an
                        # empty string so all classes will be safely removed.
                        if value == null
                            value = ''

                        # Add the classes to the classes list....
                        classes += value + " "
                    else
                        attributes[name] = value


                # Apply the style changes
                for cssClass, applied of styles
                        classes = cssClass + " "

                # Apply the classes attribute...
                attributes["class"] = classes

                element.content = element.content.format(
                    from,
                    to,
                    new HTMLString.Tag(@tagName, attributes)
                    )
                
                # Get rid of the selector...
                modal.hide()
                dialog.hide()

                element.content.optimize()
                element.updateInnerHTML()
                element.taint()

                element.restoreState()

                callback(true)

            app.attach(modal)
            app.attach(dialog)
            modal.show()
            dialog.show()
```

**Comment by anthonyjb** [comment]
The documentation for HTMLString explains how unformat works in terms of matching, you can find it here: http://getcontenttools.com/api/html-string#string (under `s.unformat(from, to, tags...)`)

As per the docs because a `HTMLString.Tag` instance is passed to `unformat` the span must match exactly, that is <span some="attribute"> want be matched, you'll need to either send a tag with matching attributes for the span or instead of sending a `Tag` send just the tagName, e.g 'span'.

**Comment by shockdot** [comment]
Perfect! Using just the tag name worked :) Thanks for the guidance.

**Comment by anthonyjb** [comment]
np - glad it's working for you
