### ISSUE TITLE
Cannot read property 'innerHTML' of null - After deleting table row and try to save.

### ISSUE THREAD

**Issue by mstojanovv** [GetmeUK/ContentTools#159]
This error occurs when ex. Insert table from the editor with 3 rows and after inserting delete the last row and click on the Save button.
The error also exists in the demo.

`content-tools.js:3522 Uncaught TypeError: Cannot read property 'innerHTML' of null`

**Comment by anthonyjb** [comment]
@mstojanovv thanks for posting this, I can reproduce and am looking at the issue now.

**Comment by anthonyjb** [comment]
@mstojanovv thanks again for highlighting this, the issue has now been resolved.
