### ISSUE TITLE
Inserting a Empty Div

### ISSUE THREAD

**Issue by shockdot** [GetmeUK/ContentTools#160]
I wanted to create a tool that would be used to Clear inline elements, such as a inline list.

I figured this would be simple enough, as we already have tools such as the line-break tool that accomplish the same task (inserting a html tag at a given location).

So I started by basing off the new tool from the line-break tool code...

Like so..

```
class ContentTools.Tools.Line extends ContentTools.Tools.LineBreak

    # Insert a line in to the current element at the specified selection.

    ContentTools.ToolShelf.stow(@, 'clear')

    @label = 'Clear'
    @icon = 'clear'

    @apply: (element, selection, callback) ->
        # Apply the tool to the current element

        # Insert a clear at the current in index
        cursor = selection.get()[0] + 1

        tip = element.content.substring(0, selection.get()[0])
        tail = element.content.substring(selection.get()[1])
        div = new HTMLString.String('<div style=\'clear: both;\'></div>', element.content.preserveWhitespace())
        element.content = tip.concat(div, tail)
        element.updateInnerHTML()
        element.taint()

        # Restore the selection
        selection.set(cursor, cursor)
        element.selection(selection)

        callback(true)


ContentTools.DEFAULT_TOOLS[0].push('clear')
```

To me this code should work as the only thing that really changed was we changed <br> to <div style=\'clear: both;\'></div>

However... It doesn't work and only seems to cause the current selection to advance in some order... (But does not insert anything)

I've solved the problem using CSS, but something like this should still be possible... Still wondering why it did not work as expected.

**Comment by anthonyjb** [comment]
Hi @shockdot this isn't really the approach I'd recommend for this, partly because as per the docs (http://getcontenttools.com/api/html-string#limitations) the HTMLParser is designed for inline content not block level elements (such as a `<div>`) and partly because I would recommend a different approach for clearing your content.

In my experience a better approach here would be to create a `clearfix` class and apply it to the block level element (e.g the `<p>` tag), e.g:

```
// Taken from the bourbon library which I love (https://github.com/thoughtbot/bourbon/blob/v4-stable/app/assets/stylesheets/addons/_clearfix.scss)
.clearfix:after {
    clear: both;
    content: '';
    display: table;
}
```
