### ISSUE TITLE
When calling the editor.start(); api method the editor is not fully start.

### ISSUE THREAD

**Issue by mstojanovv** [GetmeUK/ContentTools#161]
Hi,
Great Editor.

I have on click event on a button which fires the editor.start() method. After the editor.start(); is fired the in the editor only shows the tools board and not the 2 buttons Save and Cancel
Like its not fired at full.

http://postimg.org/image/n1ypxpd6b/

Also this happend when editor.stop() method is called. The tools board still exists.

Does these are the correct methods or is some bug?
Regards.

**Comment by anthonyjb** [comment]
Hi @mstojanovv - thanks for the kind comments - support for better event handling in the editor UI is under way and will be available in the next release (I have an early prototype working on my machine and it's a big improvement), but until then this is a bit of a messy area.

To start/stop the editor and animate the switch you have to fake the click events against the ignition itself, so for example after calling `init` against the editor:

```CoffeeScript
editor = ContentTools.EditorApp.get()
edit.init(...)

# Get the ignition component
ignition = editor._ignition

# Start 
ignition._domEdit.click()

# Save
ignition._domConfirm.click()

# Cancel
ignition._domCancel.click()
```

This code may well break in the upcoming release (1.2) and there will be a more appropriate approach to solving this problem - but in the short term this should work.

**Comment by mstojanovv** [comment]
Hi @anthonyjb .
Thanks for your reply and yes this worked good now.
Any ETA for the next release.

Regards.

**Comment by anthonyjb** [comment]
Hopefully the new event system will be available early next week (that's my plan at least).

**Comment by anthonyjb** [comment]
@mstojanovv Just a quick update on this, I have a version of the new event system in a usable state - I'm just updating existing tests and checking and updating documentation so I'm confident of releasing this feature next week.

**Comment by mstojanovv** [comment]
Thats good. Waiting for the release.
Thanks
