### ISSUE TITLE
How to replace image 

### ISSUE THREAD

**Issue by vladyslav2** [GetmeUK/ContentTools#162]
Hello.

First - thanks for that amazing editor! I wish i found your app 2-3 years ago !

I do have very simple and very, i guess, comon question:
- what if i want to replace one image with new one ? Currently i created that solution:
```
xhrComplated = function() {
                ...
                $('.ce-element--focused').prev().remove();                         
                $('.ce-element--focused').prop('alt', response.name);              
                ContentTools.FlashUI('Ok');  
}
```

but it seems do not work, so whats the best way to do that ?

Thanks !

**Comment by anthonyjb** [comment]
Hi @vladyslav2 and thanks for the kind words :+1: 

You're right I have been asked this question a number of times before, however I actually like the approach you've started on better than my previous suggestions as it's cleaner, so based on your code above this is what I'd suggest. In your image uploader you need to modify the behaviour of the `_onSave` view:

```JavaScript
ImageUploader.prototype._onSave = function() {
    // Select the currently focused image
    var focused = ContentEdit.Root.get().focused();

    // Save our new image inserting it into the page
    this._dialog.save(imageUrl, imageSize, {'alt': imageAlt});

    // If the focused element was an image remove it so the new image is 
    // switched with the old.
    if (focused.type() === 'Image')
        focused.parent().detach(focused);
    }
};
```

Everyone's `ImageUploader` tends to be a little different based on their integration but hopefully this gives you enough to go on, however if you do run into any issues with this let me know.
