### ISSUE TITLE
2 issues and an enhancement project

### ISSUE THREAD

**Issue by simonmuys** [GetmeUK/ContentTools#164]
Hi Anthony,

First of all, thanks for the amazing work done with ContentTools. It's really a nice library. 

I am currently using it on a Laravel based website, linked with SQL db. I'm gonna need to develop a way to add custom containers calling for external content types within the edited content so I'll keep you posted if I manage to achieve something (or if I encounter problems) and if I can release something you could reuse.

Right now I have two remaining bugs on my integration. One I simply can't figure out (after hours trying) and the other I haven't yet dived too deeply into. 

- First, on the crop function, I pass the "crop" array to my Controller and try to use it with Intervention Image (which is a pain, since it's handling crop in a totally different manner). The problem is I just can't figure out how the crop array works. From my tests, it seems to have 7 values (identified from 0 to 6), they can be an integer (between 0 and 9), a colon or a coma... And depending on the position of the cropmarks, some of the values become comas and other become integer. I have been completely unable to find a logic behind it, and from your tutorial, I would expect to find only 4 non-integer values between 0 and 1 (corresponding to top, left, bottom and right normalized values). 
I should be able to convert the normalized values to the inputs expected by Intervention Image using simple maths... But I would need your help in understanding how the 'crop' output of the imageUploader.save function is built.

- Second, and it might be a simple thing since I haven't looked into it too much, I have problems when reusing the editor a second time right after a first edit. For example, if I save the text, then reopen and save again, the editor delete the entire content. Same for the image: if I rotate an image, everything goes fine, but if I do it a second time right afterwards, it doesn't work. Also, the edit panel doesn't disappear when I save. Somehow it feels like everything's working fine, but something stays open after saving successfully and fucks things up afterwards. Maybe my controller should return a value when the AJAX request has been treated? But I've found nothing about it on your tutorials.

Below, the code for my editor.js (it's pretty much standard from your tutorials). Thanks in advance for your help.

Simon

````
/*! ContentTools v0.1.0, initialisation scripts */

window.addEventListener('load', function() {
	var editor;
	ContentTools.StylePalette.add([
		new ContentTools.Style('Author', 'author', ['p'])
	]);
	ContentTools.IMAGE_UPLOADER = imageUploader;
});

// Patch the editor's start/stop methods to support auto-save
var editorCls = ContentTools.EditorApp.getCls();

editor = ContentTools.EditorApp.get();
editor.init('*[data-editable]', 'data-name');

// Listen for save events
editor.bind('save', function (regions) {
    var name, payload, xhr;

    // Set the editor as busy while we save our changes
    this.busy(true);

    // Collect the contents of each region into a FormData instance
    payload = new FormData();
    for (name in regions) {
        if (regions.hasOwnProperty(name)) {
            payload.append(name, regions[name]);
        }
    }

    // Send the update content to the server to be saved
    function onStateChange(ev) {
        // Check if the request is finished
        if (ev.target.readyState == 4) {
            editor.busy(false);
            if (ev.target.status == '200') {
                // Save was successful, notify the user with a flash
                new ContentTools.FlashUI('ok');
            } else {
                // Save failed, notify the user with a flash
                new ContentTools.FlashUI('no');
            }
        }
    };

    xhr = new XMLHttpRequest();
    xhr.addEventListener('readystatechange', onStateChange);
    xhr.open('POST', '/www/'+contenttype+'/'+chapterid);	
    xhr.setRequestHeader('X-CSRF-TOKEN', $("#token").attr('content'));
    xhr.send(payload);
});	

editor.start = function () {

    // Call save every 30 seconds
    function autoSave() {
        editor.save(true, 'autoSave');
    };
    this.autoSaveTimer = setInterval(autoSave, 30 * 1000);

    // Start the editor
    editorCls.prototype.start.call(this);
};

editor.stop = function () {
    // Stop the autosave
    clearInterval(this.autoSaveTimer);

    // Stop the editor
    editorCls.prototype.start.call(this);
}

function imageUploader(dialog) {
     var image, xhr, xhrComplete, xhrProgress;

    // Set up the event handlers
	
     dialog.bind('imageUploader.cancelUpload', function () {
        // Cancel the current upload

        // Stop the upload
        if (xhr) {
            xhr.upload.removeEventListener('progress', xhrProgress);
            xhr.removeEventListener('readystatechange', xhrComplete);
            xhr.abort();
        }

        // Set the dialog to empty
        dialog.state('empty');
    });
	
	 dialog.bind('imageUploader.clear', function () {
        // Clear the current image
        dialog.clear();
        image = null;
    });
	
	dialog.bind('imageUploader.fileReady', function (file) {
        // Upload a file to the server
        var formData;

        // Define functions to handle upload progress and completion
        xhrProgress = function (ev) {
            // Set the progress for the upload
            dialog.progress((ev.loaded / ev.total) * 100);
        }

        xhrComplete = function (ev) {
            var response;

            // Check the request is complete
            if (ev.target.readyState != 4) {
                return;
            }

            // Clear the request
            xhr = null
            xhrProgress = null
            xhrComplete = null

            // Handle the result of the upload
            if (parseInt(ev.target.status) == 200) {
                // Unpack the response (from JSON)
                response = JSON.parse(ev.target.responseText);

                // Store the image details
                image = {
                    size: response.size,
                    url: response.url
                    };

                // Populate the dialog
                dialog.populate(image.url, image.size);

            } else {
                // The request failed, notify the user
                new ContentTools.FlashUI('no');
            }
        }

        // Set the dialog state to uploading and reset the progress bar to 0
        dialog.state('uploading');
        dialog.progress(0);

        // Build the form data to post to the server
        formData = new FormData();
        formData.append('image', file);

        // Make the request
        xhr = new XMLHttpRequest();
        xhr.upload.addEventListener('progress', xhrProgress);
        xhr.addEventListener('readystatechange', xhrComplete);
		xhr.open('POST', '/www/upload-image');	
		xhr.setRequestHeader('X-CSRF-TOKEN', $("#token").attr('content'));
        xhr.send(formData);
    });
	
	function rotateImage(direction) {
        // Request a rotated version of the image from the server
        var formData;

        // Define a function to handle the request completion
        xhrComplete = function (ev) {
            var response;

            // Check the request is complete
            if (ev.target.readyState != 4) {
                return;
            }

            // Clear the request
            xhr = null
            xhrComplete = null

            // Free the dialog from its busy state
            dialog.busy(false);

            // Handle the result of the rotation
            if (parseInt(ev.target.status) == 200) {
                // Unpack the response (from JSON)
                response = JSON.parse(ev.target.responseText);

                // Store the image details (use fake param to force refresh)
                image = {
                    size: response.size,
                    url: response.url + '?_ignore=' + Date.now()
                    };

                // Populate the dialog
                dialog.populate(image.url, image.size);

            } else {
                // The request failed, notify the user
                new ContentTools.FlashUI('no');
            }
        }

        // Set the dialog to busy while the rotate is performed
        dialog.busy(true);

        // Build the form data to post to the server
        formData = new FormData();
        formData.append('url', image.url);
        formData.append('direction', direction);

        // Make the request
        xhr = new XMLHttpRequest();
        xhr.addEventListener('readystatechange', xhrComplete);		
		xhr.open('POST', '/www/rotate-image');	
		xhr.setRequestHeader('X-CSRF-TOKEN', $("#token").attr('content'));
        xhr.send(formData);
    }

    dialog.bind('imageUploader.rotateCCW', function () {
        rotateImage('CCW');
    });

    dialog.bind('imageUploader.rotateCW', function () {
        rotateImage('CW');
    });
	
	dialog.bind('imageUploader.save', function () {
        var crop, cropRegion, formData;

        // Define a function to handle the request completion
        xhrComplete = function (ev) {
            // Check the request is complete
            if (ev.target.readyState !== 4) {
                return;
            }

            // Clear the request
            xhr = null
            xhrComplete = null

            // Free the dialog from its busy state
            dialog.busy(false);

            // Handle the result of the rotation
            if (parseInt(ev.target.status) === 200) {
                // Unpack the response (from JSON)
                var response = JSON.parse(ev.target.responseText);

                // Trigger the save event against the dialog with details of the
                // image to be inserted.
                dialog.save(
                    response.url,
                    response.size,
                    {
                        'alt': response.alt,
                        'data-ce-max-width': image.size[0]
                    });

            } else {
                // The request failed, notify the user
                new ContentTools.FlashUI('no');
            }
        }

        // Set the dialog to busy while the rotate is performed
        dialog.busy(true);

        // Build the form data to post to the server
        formData = new FormData();
        formData.append('url', image.url);

        // Set the width of the image when it's inserted, this is a default
        // the user will be able to resize the image afterwards.
        formData.append('width', 500);

        // Check if a crop region has been defined by the user
        if (dialog.cropRegion()) {
            formData.append('crop', dialog.cropRegion());
        }

        // Make the request
        xhr = new XMLHttpRequest();
        xhr.addEventListener('readystatechange', xhrComplete);
		xhr.open('POST', '/www/insert-image');	
		xhr.setRequestHeader('X-CSRF-TOKEN', $("#token").attr('content'));
        xhr.send(formData);
    });
}
	`
```

**Comment by anthonyjb** [comment]
Hi @simonmuys thanks for the kind comments and it's great to hear investing time in CT :)

So re your first question, you are correct in assuming that the output of cropRegion should be a 4 item array, so these are the 2 relevant snippets of code that return crop marks.

```CoffeeScript
ContentTools.ImageDialog.cropRegion: () ->
    # Return the defined crop-region (top, left, bottom, right), values are
    # normalized to the range 0.0 - 1.0. If no crop region is defined then
    # the maximum region will be returned (e.g [0, 0, 1, 1])
    if @_cropMarks
        return @_cropMarks.region()

    return [0, 0, 1, 1]

CropMarksUI.region: () ->
    # Return the crop region (top, left, bottom, right), values are
    # normalized to the range 0.0 - 1.0.
    return [
        parseFloat(@_domHandles[0].style.top) / @_bounds[1],
        parseFloat(@_domHandles[0].style.left) / @_bounds[0],
        parseFloat(@_domHandles[1].style.top) / @_bounds[1],
        parseFloat(@_domHandles[1].style.left) / @_bounds[0]
        ]
```

- https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/dialogs/image.coffee#L41
- https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/dialogs/image.coffee#L326

As you can see you should be returned 4 numbers between 0.0 and 1.0 in the order (top, left, bottom, right). If this isn't what's being returned then there's an issue, could you `console.log(dialog.cropRegion())` and post the result here so I can see what you're being returned.

Re. your second question this is definitely not the expected behaviour and you should certainly be able to edit more than once, this sounds like an issue is being raised during the saving process - can you post any output in the JS console of your browser for me to review please.

**Comment by simonmuys** [comment]
Hi Anthony, just a heads up on this issue:

First, you're entirely right saying all the problems come from my poor handling in back-end :).

I've solved the problem of the double crop quite easily: I was using pathinfo but since your JS adds a parameter to the URL, I needed to parse it first to escape the parameter. That didn't take long.

Second problem, on the crop, logging the $crop array returned the correct values, as you'd have guessed. Back-end, I logged everything little by little and it resulted the problem was I retrieve an array of characters instead of a proper array of the four values. So using $crop[0] or $crop[1] only returning the corresponding character and not the whole value. For example, if my crop array was [0.234, 0.5, 1, 1], $crop[0], $crop[1], $crop[2], $crop[3] were returning respectively '0', '.', '2' and '3'. I don't know where that shit comes from, I've looked extensively to find explanations but nothing to be found. I guess Laravel Request façade must have something wrong with floats being passed through a formData format. 
What I did is to explode the string into a proper array. It's dirty work, but it made the trick. 
Afterwards, the integration with Image Intervention library was headache but nothing maths can't solve. I'll publish the full Laravel Controller so feel free to use it in a tutorial if need be (it might not be perfect but it works for me!).

Now, for the last problem, I've had time to look a bit more into it and the problem was not on second save but on saving while no modification had been made. But you had provided a piece of code for that in your tutorial so it's not been too hard to solve. 

I have now just one remaining problem with the edit toolbar that remained active when editor was shut or saved was performed. I tried to solve that using widget.hide() but it seems each time I use it it breaks the reste of the saving process. 

I'll now concentrate on building a proper stylesheet and a tool for adding token calling for external content. 

Thanks again for your help!

Simon

PS: this is the current Laravel Controller

`<?php namespace App\Http\Controllers;

use File;
use Validator;
use Redirect;
use App\User;
use Intervention\Image\ImageManagerStatic as Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;

class UploadsController extends Controller {
	
	/**
     * Upload by AJAX.
     *
     * @param $request
     * @return Response
     */	
	public function upload(Request $request)
	{
		$user = User::find(Auth::user()->id);
		$imgid = count(glob(public_path().'/temp/'.$user->slug.'-image-*.*'))+1;
				
		$image = $request->file('image'); 
		$imagename = $user->slug.'-image-'.$imgid.'.'.$image->getClientOriginalExtension();
		$request->file('image')->move(public_path().'/temp/', $imagename);
		
		$size = getimagesize(public_path().'/temp/'.$imagename);
		$url = asset('temp/'.$imagename);
		
		return response()->json(['size' => $size, 'url' => $url]);		
	}

	/**
     * Rotate image by AJAX.
     *
     * @param $request
     * @return Response
     */	
	public function rotate(Request $request)
	{
		$origin = $request->input('url');
		
		$user = User::find(Auth::user()->id);
		$imgid = count(glob(public_path().'/temp/'.$user->slug.'-image-*.*'))+1;
		$imagename = $user->slug.'-image-'.$imgid.'.'.pathinfo(parse_url($origin)['path'], PATHINFO_EXTENSION);
		
		if ($request->input('direction') === 'CW') {
			$img = Image::make($origin)->rotate(-90);
		}
		elseif ($request->input('direction') === 'CCW') {
			$img = Image::make($origin)->rotate(90);
		}			
		$img->save(public_path().'/temp/'.$imagename);		
		
		$size = getimagesize(public_path().'/temp/'.$imagename);
		$url = asset('temp/'.$imagename);		

		return response()->json(['size' => $size, 'url' => $url]);
	}	

	/**
     * Insert image by AJAX.
     *
     * @param $request
     * @return Response
     */	
	public function insert(Request $request)
	{
		$origin = $request->input('url');
		
		$user = User::find(Auth::user()->id);
		$imgid = count(glob(public_path().'/media/'.$user->slug.'-image-*.*'))+1;
		$imagename = $user->slug.'-image-'.$imgid.'.'.pathinfo(parse_url($origin)['path'], PATHINFO_EXTENSION);	
		
		if ($request->input('crop') !== null) {
			$crop = explode(",", $request->input('crop'));
				
			$width = Image::make($origin)->width();
			$height = Image::make($origin)->height();
			
			$cropparam1 = round(($crop[3]-$crop[1])*$width);
			$cropparam2 = round(($crop[2]-$crop[0])*$height);
			$cropparam3 = round($crop[1]*$width);
			$cropparam4 = round($crop[0]*$height);
			
			$img = Image::make($origin)->crop($cropparam1, $cropparam2, $cropparam3, $cropparam4);
		}
		else {
			$img = Image::make($origin);
		}
		
		$img->save(public_path().'/media/'.$imagename);	
		
		$size = getimagesize(public_path().'/media/'.$imagename);
		$url = asset('media/'.$imagename);
		$alt = '';
		
		return response()->json(['size' => $size, 'url' => $url, 'alt' => $alt]);		
	}	
}
`

**Comment by simonmuys** [comment]
Hi Anthony,

I'm struggling with creating new tools with your API.

Right now, I'm trying nothing more fancy than creating a div wrapper with a class around the current paragraph. Since you have no tool that works this way, I wonder if it's possible using your Tool creation tutorial. But from what I see of your API, it should be possible.

I've been able to create a div component using ContentEdit.Element, but since I want it as a wrapper, I guess I should use ElementCollection instead.

Yet with the code below, I don't view any new div created. 
I know I haven't yet added the element text to the supposedly created node but since I have erase everything that should not be useful for the div to appear.

Could you point me to what I'm doing wrong again?

Thanks in advance,

Simon


```
class ContentTools.Tools.Dialogue extends ContentTools.Tool

    # Convert the current text block to a dialogue block (e.g <div class="dialogue">foo</div)

    ContentTools.ToolShelf.stow(@, 'dialogue')

    @label = 'Dialogue'
    @icon = 'dialogue'
    @tagName = 'div'

    @canApply: (element, selection) ->
        # Return true if the tool can be applied to the current
        # element/selection.
        return element != undefined

    @apply: (element, selection, callback) ->
        # Apply the tool to the current element

        # Create a new dialogue element using the current elements content
        collection = new ContentEdit.ElementCollection(
            'div', {class:'dialogue'}
            )
        paragraph = new ContentEdit.Text('p')
        collection.attach(paragraph)

        # Get the element region or its closest one
        if element.parent().type() != 'Region'
            element = element.closest (node) ->
            return node.parent().type() is 'Region'
        region = element.parent()
        region.attach(collection)
		
        element.focus()

        callback(true)
	
ContentTools.DEFAULT_TOOLS[0].push('dialogue')
```

**Comment by anthonyjb** [comment]
Hi @simonmuys,

The element collection class is actually designed to be inherited from rather than used directly (e.g the List element or Table element), having said that this does work there just a few minor issues with your code (you're very close):

```CoffeeScript

    class ContentTools.Tools.Dialogue extends ContentTools.Tool

        # Convert the current text block to a dialogue block (e.g <div class="dialogue">foo</div)

        ContentTools.ToolShelf.stow(@, 'dialogue')

        @label = 'Dialogue'
        @icon = 'dialogue'
        @tagName = 'div'

        @canApply: (element, selection) ->
            # Return true if the tool can be applied to the current
            # element/selection.
            return element != undefined

        @apply: (element, selection, callback) ->
            # Apply the tool to the current element

            # Create a new dialogue element using the current elements content
            collection = new ContentEdit.ElementCollection(
                'div', {class:'dialogue'}
                )
            paragraph = new ContentEdit.Text('p', {}, 'My custom wrapped p tag')
            collection.attach(paragraph)

            # Get the element region or its closest one
            if element.parent().type() != 'Region'
                element = element.closest (node) ->
                    return node.parent().type() is 'Region'

            region = element.parent()
            region.attach(collection, element.parent().children.indexOf(element))

            paragraph.focus()

            callback(true)

    ContentTools.DEFAULT_TOOLS[0].push('dialogue')
```

So here's what I changed:

- I updated the `region.attach` call so that the new element is inserted before the selected element (you were inserting it at the end of the region (which is I assume why you couldn't see it).
- I changed the focus to event to be called against the paragraph (rather than the selected element when the tool is applied).

Hope that helps - Ant

**Comment by simonmuys** [comment]
Thanks a lot Anthony, this works perfectly. I've changed a bit the code now for attaching the initial text element and returning the selection.

I've started working on the token system. It's basically an insert of a <token></token> element with a given class (depending on the tool). I'm using the video modal to give the user the opportunity to select the right content to call. So far everything's working fine so I should be able to do what I need. 
I'm still struggling to pass the array of options from my Laravel DB to the coffee script of the modal and I still have to verify I can easily create a selectbox with options but I'm quite confident on both points. 
I'll share the code once it's done (or if I'm blocked somehow). 

Thanks again for the plugin and congrats man. ContentTools is really an amazing library to work with.

**Comment by simonmuys** [comment]
Hi Anthony, 

I've almost managed to finalize the token system.
Here is how I've done it. First, I've created a new tool:

class ContentTools.Tools.Character extends ContentTools.Tool
	
```
 # Create a character block (e.g <token class="character"></token) that will be parsed and replace by the proper content

    ContentTools.ToolShelf.stow(@, 'character')

    @label = 'Character'
    @icon = 'character'
    @tagName = 'token'

    @canApply: (element, selection) ->
        # Return true if the tool can be applied to the current
        # element/selection.
        return true

    @apply: (element, selection, callback) ->

        # If supported allow store the state for restoring once the dialog is
        # cancelled.
        if element.storeState
            element.storeState()

        # Set-up the dialog
        app = ContentTools.EditorApp.get()

        # Modal
        modal = new ContentTools.ModalUI()

        # Dialog
        dialog = new ContentTools.CharacterDialog()

        # Support cancelling the dialog
        dialog.bind 'cancel', () =>
            dialog.unbind('cancel')

            modal.hide()
            dialog.hide()

            if element.restoreState
                element.restoreState()

            callback(false)

        # Support saving the dialog
        dialog.bind 'save', (characterID) =>
            dialog.unbind('save')

            if characterID
                # Create a new dialogue element using the current elements content
                collection = new ContentEdit.ElementCollection(
                    'token', {class:'character', tokenType:'character', data:characterID}
                )
                collection.can('drag', true)
                collection.can('remove', true)

                # Find insert position
                [node, index] = @_insertAt(element)
                node.parent().attach(collection, index)

            else
                # Nothing to do restore state
                if element.restoreState
                    element.restoreState()

            modal.hide()
            dialog.hide()

            callback(characterID != '')

        # Show the dialog
        app.attach(modal)
        app.attach(dialog)
        modal.show()
        dialog.show()
	
ContentTools.DEFAULT_TOOLS[2].push('character')

```

I've also created a specific dialog tool with a select box for passing the right content to the token (based on the video dialog tool). I've escaped the preview for simplification:


```
class ContentTools.CharacterDialog extends ContentTools.DialogUI

    # A dialog to support inserting a character

    constructor: ()->
        super('Insert character')

    mount: () ->
        # Mount the widget
        super()

        # Update dialog class
        ContentEdit.addCSSClass(@_domElement, 'ct-character-dialog')

        # Update view class
        ContentEdit.addCSSClass(@_domView, 'ct-character-dialog__preview')

        # Add controls
        domControlGroup = @constructor.createDiv(['ct-control-group'])
        @_domControls.appendChild(domControlGroup)

        # Input
        @_domInput = document.createElement('select')
        @_domInput.setAttribute('id', 'selectcharacter')
        @_domInput.setAttribute('class', 'ct-video-dialog__input form-control')
        @_domInput.setAttribute('name', 'url')
        domControlGroup.appendChild(@_domInput)

        characters = jsvar.characters
        for i in characters
            do ->
                for j in i
                    domOption = document.createElement('option')
                    domOption.setAttribute('value', j['id'])
                    domOption.innerHTML = j['name']
                    document.getElementById('selectcharacter').appendChild(domOption)

        # Insert button
        @_domButton = @constructor.createDiv([
            'ct-control',
            'ct-control--text',
            'ct-control--insert'
            ])
        @_domButton.textContent = ContentEdit._('Insert')
        domControlGroup.appendChild(@_domButton)

        # Add interaction handlers
        @_addDOMEventListeners()

    save: () ->
        # Save the character. This method triggers the save method against the
        # dialog allowing the calling code to listen for the `save` event and
        # manage the outcome.

        # Attempt to parse a character embed URL
        characterID = @_domInput.value.trim()
        @trigger('save', characterID)

    show: () ->
        # Show the widget
        super()

        # Once visible automatically give focus to the link input
        @_domInput.focus()

    unmount: () ->
        # Unmount the component from the DOM

        # Unselect any content
        if @isMounted()
            @_domInput.blur()

        super()

        @_domButton = null
        @_domInput = null

    # Private methods

    _addDOMEventListeners: () ->
        # Add event listeners for the widget
        super()

        # Add support for saving the character whenever the `return` key is pressed
        # or the button is selected.

        # Input
        @_domInput.addEventListener 'keypress', (ev) =>
            if ev.keyCode is 13
                @save()

        # Button
        @_domButton.addEventListener 'click', (ev) =>
            ev.preventDefault()

            # Check the button isn't muted, if it is then the character ID field
            # isn't populated.
            cssClass = @_domButton.getAttribute('class')
            if cssClass.indexOf('ct-control--muted') == -1
                @save()
```

I then have a JS parser for adding content to the token through a JQuery load control:

```
$(function() {

	/*---------------------------------------*/
    /*  AJAX PARSER FOR TOKENS
    /*---------------------------------------*/
	$(document).ready(function(){			
		$( "token" ).each(function() {
			var tokenType = $( this ).attr('tokenType');
			var tokenID = $( this ).attr('data');
			$( this ).load( "/tokenize/"+tokenType+"/"+tokenID );
		});
	});
});
```

The parser calls a Laravel controller that adds a blade view with the proper content inside the token div (I don't show the code for that since it's both pretty straightforward and very specific to my website).

I have a lot of work to do on the editor to be entirely what I need it to be but most of the difficulties are now behind since it's mostly replication of functionalities. 

I still have two core issues I haven't figured out:

- first, I just can't figure out how to have the drag/drop and remove behaviors on my token divs... I'm using an ElementCollection instead of an Element so it should be why the behavior is not set from the beginning and also why the collection.can('drag', true) method does not work. But when I switch to a regular Element, using the exact same syntaxe for the attributes object, it doesn'twork. Also, since ElementCollection inherits from Element, shouldn't it receive also the "can" method? 

- second, I still have a problem reediting the newly created div from the dialogue tool you've helped me build last time (I guess it will be the same for the token part). I can edit, toggle the behavior that creates a new div with the proper classes and appending the selected content, I can save and everything is fine. But when I try to edit again, I can't select the element anymore. My guess would be to say it's because they are ElementCollections instead of regular Elements, but I don't know where or how to specify these div can be selected and edited. Could you point out to the thing I've missed?

I hope the code I'm sharing can give you some ideas for new implementations on the core of your plugin. I do believe that adding tokens with customized data that can be parsed to add external content is an interesting feature to have in the API.

Thanks again,

Simon

**Comment by anthonyjb** [comment]
@simonmuys drop behaviour must be specified for your new element, for example look at how this is done for the Text element:

https://github.com/GetmeUK/ContentEdit/blob/master/src/scripts/text.coffee#L451

Have you done this? If not your element can't be dropped or dropped onto by another element.

Might be a pain but is is it possible to see this up and running somewhere and your full code? It's difficult to grasp what you may be missing without.

**Comment by simonmuys** [comment]
Hi @anthonyjb . 

No pb to give you an access to the WIP. Can you send me your email address at muys.simon@gmail.com. I'll send you the details for you to see what I've been doing and how it looks so far.

Best regards,

Simon

**Comment by anthonyjb** [comment]
@simonmuys done, sorry for the late reply I've been away.
