### ISSUE TITLE
imageuploader.fileready is broken

### ISSUE THREAD

**Issue by etlel** [GetmeUK/ContentTools#166]
When these lines are executed after an attempt to upload a file:
```javascript
dialog.addEventListener('imageuploader.fileready', function (ev) {
       var file = ev.detail().file;
       ...
```
Result: "TypeError: ev.detail(...) is undefined"

**Comment by anthonyjb** [comment]
Hi @etlel thanks for highlighting this, the event was being dispatched without the file information. I missed it when converting the event over to the new system I've resolved now.
