### ISSUE TITLE
Revert / Stop without alert

### ISSUE THREAD

**Issue by markusvt** [GetmeUK/ContentTools#167]
I am trying to start and stop the editor with custom buttons. It works quite fine, but when I made changes to the HTML and click the "cancel" Button (which calls the revert function of the editor),
that "do you really want to discard your changes" alert is displayed. can i somehow turn that off?

**Comment by anthonyjb** [comment]
The simplest approach would be to patch the revert method directly, e.g:

```JavaScript
var editor = ContentTools.EditorApp.get();
editor.revert = function () {
   this.revertToSnapshot(this.history.goTo(0), false);
   return true;
};
```

You might also consider keeping the event trigger here: https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/editor.coffee#L375

**Comment by markusvt** [comment]
Thank you! Works great :)
