### ISSUE TITLE
Delete or fix code in "editor.coffee"

### ISSUE THREAD

**Issue by sticklvl** [GetmeUK/ContentTools#171]
http://getcontenttools.com/demo

1. Add youtube video
2. click Save
3. click Edit
4. click Save
5. Bug, we can edit article, video is broken

I removed this code, and now it works correct
```
# Check the document has changed, if not we don't need do anything
root = ContentEdit.Root.get()
if root.lastModified() == @_rootLastModified
	# Trigger the saved event early with no modified regions,
	@dispatchEvent(
		@createEvent('saved', {regions: {}, passive: passive})
		)
	return
```

**Comment by anthonyjb** [comment]
Ah yep - my bad incorrectly updated that test in release 1.2 - will push a fix shortly.

**Comment by anthonyjb** [comment]
@sticklvl - thanks for providing a concise bug report (really helps) and for highlighting the code that was causing the issue, it's much appreciated. I've pushed a fix for this now.
