### ISSUE TITLE
Change the `tools` method for toolbox so that it doesn't unmount/mount the widget

### ISSUE THREAD

**Issue by SimBioT1954** [GetmeUK/ContentTools#173]
How to forbid any insert of images/tables etc in editable area? 
Can I create editable input for only plain text?
Thanks a lot!

**Comment by anthonyjb** [comment]
Hi @SimBioT1954 this is one of the features that will be better supported in the upcoming 1.3.0 release. We're planning on allowing individual editable elements to be configured to behave uniquely, so disabling some or all of the tools when selected, or disabling drag and drop support.

However in the mean time this is actually possible right now (if slightly long winded). You need to listen for the focus event against editable elements and then use that event to configure the tools available, for example:

```JavaScript
ContentEdit.Root.get().bind('focus', function (element) {
    var editor = ContentTools.EditorApp.get();
    if (element.domElement().classList.contains('no-images')) {
       editor.toolbox()._toolUIs['image'].disabled(true);
    } else {
       editor.toolbox()._toolUIs['image'].disabled(false);
    }
}
```

Alternatively if you want to remove all tool options you can toggle the tools in the toolbox using:

```JavaScript
// Turn all tools off
editor.toolbox().tools([]);

// Turn all tools back on
editor.toolbox().tools(ContentTools.DEFAULT_TOOLS);
```

**Comment by SimBioT1954** [comment]
Why is this code does not work?
```javascriptContentEdit.Root.get().bind('focus', function (element){
	var editor = ContentTools.EditorApp.get();

   if (element.domElement().classList.contains('plain-text')) {
editor.toolbox().tools([]);
}else{ 
editor.toolbox().tools(ContentTools.DEFAULT_TOOLS);
		}
});```

**Comment by anthonyjb** [comment]
OK so this isn't ideal and it's something I'll need to look at but because the ToolBox element is unmounting/mounting itself its not active and therefore hidden, the following fixes that:

```JavaScript
    ContentEdit.Root.get().bind('focus', function (element){
      var editor = ContentTools.EditorApp.get();
      if (element.domElement().classList.contains('plain-text')) {
        editor.toolbox().tools([]); // <-- Turns all tools off
      } else {
        editor.toolbox().tools(ContentTools.DEFAULT_TOOLS); // <-- does nothing
      }

      // Make sure the toolbox is active
      editor.toolbox().domElement().classList.add('ct-widget--active');
    });
```

However this causes an unwanted transition to occur, I need to update this to make it more efficient in the way it updates the tools and to prevent this show/hide transition. I'll flag this as an enhancement now and update the title to be more relevant.

**Comment by anthonyjb** [comment]
Hi @SimBioT1954,

The **develop** branch now contains an improvement to the `Toolbox.tools` method which resolves this issue cleanly, here's an updated example of how to approach this:

```JavaScript
var editor = ContentTools.EditorApp.get();
editor.myToolsState = 'rich';
ContentEdit.Root.get().bind('focus', function (element){

  if (element.domElement().classList.contains('plain-text')) {
    if (editor.myToolsState != 'plain') {
      editor.myToolsState = 'plain';
      editor.toolbox().tools([]);
    }
  } else {
    if (editor.myToolsState != 'rich') {
      editor.myToolsState = 'rich';
      editor.toolbox().tools(ContentTools.DEFAULT_TOOLS);
    }
  }
});
```

I'll push this fix to the master in the next release.

**Comment by SimBioT1954** [comment]
@anthonyjb thanks for your work! 
Amazing library

**Comment by anthonyjb** [comment]
@SimBioT1954 no problem and thanks :+1:

**Comment by SimBioT1954** [comment]
@anthonyjb sorry but looks like 
> The develop branch 
has issue, console: 

```
TypeError: this._domToolGroups is undefined
...=j[f],g.unmount();for(this._toolUIs={};this._domToolGroups.lastChild;)this._domT...
```

**Comment by anthonyjb** [comment]
OK This happens if you change the tools before the toolbox is mounted, I've put in place a check now so that the tools method checks if the toolbox is mounted before attempting to mount the tools - good catch @SimBioT1954
