### ISSUE TITLE
NPM + Browserify

### ISSUE THREAD

**Issue by anthonyjb** [GetmeUK/ContentTools#174]
This issue stems from #29 and while support is now in place for Bower, I have still to register the packages on NPM.

**Comment by Predjo** [comment]
Any ETA when it will be available on the NPM?

**Comment by anthonyjb** [comment]
@Predjo sorry for the slightly delayed reply. We're using NPM heavily in our own build pipelines and so this is moving up my internal todo list, I hope to have published all libraries in the collection to NPM by the end of June.

**Comment by anthonyjb** [comment]
OK so thanks to the nudge :+1:  I've published each of the libraries under NPM now, so CT is now available here: https://www.npmjs.com/package/ContentTools, and can be installed like so:

```
npm install --save ContentTools
```
