### ISSUE TITLE
How can i share embedded code?

### ISSUE THREAD

**Issue by makasanas** [GetmeUK/ContentTools#175]
You did this thing for youtube and vimeo but what about other website embedded code. otherwise give one additional feature for simple HTML so any one can paste their own code directly like example i want to add slider than i code my own way and past that simple html so it's work fine what you think about it?

**Comment by anthonyjb** [comment]
Hi @makasanas - you can actually put any URL into the video embed tool at the moment as it basically just inserts an iframe, the vimeo and youtube URLs are identified and formatted to set some additional default options via the `getEmbedVideoURL` method (https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/namespace.coffee#L95). This method can be overridden to accept support additional services and if there was a request to add a service that proved popular I'd be happy to add it to the core library.

If you wanted to insert HTML directly into an editable region then you could do this using the static element type (http://getcontenttools.com/api/content-edit#static), there's no existing tool to do this so you'd either need to create one that accepted HTML code (which might be a useful feature for the core library as well) or do something similar to wordpress tags like @bfintal has done where special tags are recognized when entered into text fields and automatically converted into predefined HTML blocks.

**Comment by makasanas** [comment]
You right but i want to embedded other website code than how can i do?

**Comment by anthonyjb** [comment]
Can you provide an example of the code you want to embed and I'll see if I can put some example code up for you to start from?

**Comment by makasanas** [comment]
I want to embedded this code you http://codepen.io/rileyjshaw/pen/MyvWpw this is for example but this type of many website

**Comment by anthonyjb** [comment]
So for example in that case if you just paste the embed link for that into the `iframe` tool (e.g `//codepen.io/rileyjshaw/embed/MyvWpw/?height=350&theme-id=0&default-tab=result`) then that will embed the code pen (see screenshot) - I changed the height parameter for the iframe above to make it fit nicely but other than that this already works, if I've understood you correctly?

![image](https://cloud.githubusercontent.com/assets/3046287/14118135/f90bd2b6-f5df-11e5-86c2-83c907fdf78f.png)

**Comment by makasanas** [comment]
an you give me some basic idea for customize any ContentTools element that can i customize my way example i need to use our pre element with prism code highlighting

**Comment by anthonyjb** [comment]
OK I use `<pre>` tags and prism myself on the http://getcontenttools.com website. To do this basically I disable prism during editing as you can't edit the code and have syntax highlighting on at the same time.

Using the editor I typically convert a paragraph to a preformatted element, add or copy > paste my code into the element, then use the code editor (e.g properties > code tab) and wrap the contents in a `<code class="language-python">` tag so that prism knows what language highlighter to use.

When the editor isn't enabled (e.g in the page presented to visitors) I enable prism and this auto converts my tags to syntax highlighted blocks,

**Comment by makasanas** [comment]
Any way but this library is best than other.
