### ISSUE TITLE
Any way to change font size?

### ISSUE THREAD

**Issue by rvizcaino80** [GetmeUK/ContentTools#176]
I can not find an option for changing font-size from the palette, it is possible? Thanks.

**Comment by anthonyjb** [comment]
Hi @rvizcaino80,

There's no tool/option for doing this though I know others have implemented support for this feature in their own integrations with ContentTools.

My personal view point is that changing font size (color, etc.) through an editing tool like CT is generally the wrong approach (though I'm sure there are exceptions) and I prefer to define a set of CSS classes which can be applied to blocks keeping things consistent (e.g http://getcontenttools.com/getting-started#configure-styles).

Having said that as I say others have added this functionality and if you let me know what you have in mind I'm happy to provide you with some idea of how you might go about implementing something.
