### ISSUE TITLE
Manually calling editor.start() don't change pencil icon

### ISSUE THREAD

**Issue by rvizcaino80** [GetmeUK/ContentTools#177]
Hi, I want to start the editor when the page loads (without the need of clicking on the pencil), I am doing that with:

    editor = ContentTools.EditorApp.get();
    editor.init('*[data-editable]', 'data-name');
    editor.start() 

but the pencil icon does not change its status to save/cancel. Thanks.

**Comment by anthonyjb** [comment]
Hi @rvizcaino80,

There's two options here, either call `edit` against the ignition switch to start the editor, or manually changes the state of the switch when you start the editor, e.g:

```JavaScript
// Use switch to start the editor
editor.ignition().edit()

// Change switch manually
editor.start();
editor.ignition().state('editing');
```

**Comment by rvizcaino80** [comment]
This is great man! Amazing work. Thank you.
