### ISSUE TITLE
Any way to stop content input when overflowing parent element?

### ISSUE THREAD

**Issue by bcreeves** [GetmeUK/ContentTools#178]
What I'm trying to do is disallow content being added beyond the fixed height and width of a certain area. Is there anyway to detect that content has overflown these boundaries and new characters from being added? I have `overflow: hidden;` on the parent element which causes the ability to keep typing but the excess is cut off. The person typing may not realize they've reached the end of the fillable area. 

This is important in my case because I'm using this to fill in a template which will be printed so it needs to fit in a fixed size area.

Any help would be greatly appreciated.

**Comment by anthonyjb** [comment]
Hi @bcreeves,

I've not done this so these are really just a couple of initial thoughts on an approach, based on your question I'm just considering preventing text content from overflowing it's parent.

**Step 1** is to detect whether or not the content has exceed the space afforded to it by its container/parent element. You may already have a tactic for doing this, in the past I've used a couple of approaches but this post on stackoverflow seems pretty solid and is where I'd start: http://stackoverflow.com/questions/143815/determine-if-an-html-elements-content-overflows/143889#143889

**Step 2** If the content has exceed the bounds of the container then we need to revert it to it's state before it exceeded the containers bounds (if we do this we'll also be preventing further entry).

```
// Here we're assuming that the paragraphs with fixed heights/widths have
// the class limited against them.

// Prevent merge behaviour for elements with the limited class
ContentEdit.Root.get().bind('mount', function (element) {
    var domElement = element.domElement();
    if (!(domElement && domElement.classList.contains('limited'))) {
        return;
    }
    element.can('merge', false);
});

// Revert any change to the element that causes it to overflow
ContentEdit.Root.get().bind('taint', function (element) {
    var domElement = element.domElement();
    if (!(domElement && domElement.classList.contains('limited'))) {
        return;
    } 

    // On overflow revert
    if (checkOverflow(domElement) && element.previousHTML) {
        domElement.innerHTML = element.previousHTML;
    }

    // Remember the previous state
    element.previousHTML = domElement.innerHTML;
});
```

I've not tested this code and I suspect the revert here is going to be too simplistic and feel like it is but hopefully it helps get things started, let me know how you get on I'm sure this is something others might want to solve if not now in the future at some point.

**Comment by bcreeves** [comment]
Thanks a lot for that! I was able to get it working. I used the parent elements height and width because that was my limiting element. Below is my code for anyone curious.

    function checkOverflow(el) {
        var curOverflow = el.style.overflow;
        var isOverflowing = el.parentNode.clientWidth < el.scrollWidth || el.parentNode.clientHeight < el.parentNode.scrollHeight;
        return isOverflowing;
    }


    // Revert any change an element that causes it to overflow it's parent element.
    ContentEdit.Root.get().bind('taint', function(element) {
        var domElement = element.domElement();

        // Stop editing and blur element
        if (checkOverflow(domElement) && element.previousHTML) {
            domElement.innerHTML = element.previousHTML;
            element.blur();
        }

        // Remember the previous state
        element.previousHTML = domElement.innerHTML;
    });
