### ISSUE TITLE
Highlight multiple paragraphs

### ISSUE THREAD

**Issue by iamryandrake** [GetmeUK/ContentTools#182]
Why can't I hit Command + A and highlight all of my content? Or highlight content across paragraphs? Every other editor on the planet allows you to do this.

In the case of wanting to delete multiple blocks of content or paragraphs at once?

**Comment by anthonyjb** [comment]
Hi @iamryandrake - the approach ContentTools uses is different from other editors and makes this difficult to achieve, you can read a more in-depth response to this questions in issue #11 and further discussions on enhancements made around the issue #41.
