### ISSUE TITLE
How can I had an "article" tag and populate it with heading, paragraph ..

### ISSUE THREAD

**Issue by marc-drulot** [GetmeUK/ContentTools#183]
Hello,
thanks for this editor is really great and easy to use (even for me ) !

But i need a feature I don't find : 
I need to have html5 article, section tags (and some more) but i will be nice to add heading and paragraph in them.

Basiclly i copy/paste ContentTools.Tools.Heading class, rename it in ContentTools.Article, replace tagname, icon, label & all "Heading" inside it. I adding my button following the tutorial, and so it works !
My button create an Article tag, and i can write some text in it , Cool !

But what if I want to create a paragraph in my Article Tag, Clicking the "P" button (with or not Ctrl ), just transform my article tag into p tag
 !
Is there any way to do that ? ( excluding editing html ;) )

Thanks

**Comment by anthonyjb** [comment]
Hi @marc-drulot,

So at the moment content tools doesn't provide support for;

- sub regions (regions within in regions as you're describing above) or,
- creating regions dynamically.

This is something that's been discussed as is a long term goal for the library (see issue #183). Some users such as @bfintal have also added support for this functionality to their editors though it's not a simple undertaking.

**Comment by marc-drulot** [comment]
Ok thanks for your reply !
sorry for the duplicate post, i've not see the original issue.
I'm going to check it !
