### ISSUE TITLE
Save event raised once per region

### ISSUE THREAD

**Issue by richardprice** [GetmeUK/ContentTools#184]
The editors 'save' event is called once per region on the page, rather than once overall, which means that any saving strategy needs to take this into account.

If I have three regions on the page, the save event handler is called three times.

I am using the following code:

```
    function link(scope, element, attrs){
 
            // Initialise the editor
            var editor = new ContentTools.EditorApp.get();
            editor.init('[ng-editor]', 'ng-editor');

            // Bind a function on editor save
            editor.bind('save', function(regions, autoSave){
                console.log("saving");
                ContentService.update($stateParams.pageId, regions);
            });
    }
```

Also, if I change the above code to use the 'saved' event instead, the event handler is never called.

Any ideas?

**Comment by richardprice** [comment]
It occurs to me on the walk home that the reason its firing three times is because I am binding three times - but I cant find any docs on clearing or checking existing bindings...?

**Comment by anthonyjb** [comment]
Hi @richardprice,

As you've highlighted this behaviour is caused by binding to the save event multiple times. It looks as if you are using an older version of the library as `bind` is no longer the correct method call and `addEventListener` should be used (this changed occurred in [release 1.2.0](https://github.com/GetmeUK/ContentTools/releases/tag/1.2.0)).

In the releases prior to 1.2.0 you can use the `unbind(eventName, func)` to remove a previous binding however I'd recommend you update your library and that you checkout the documentation for the new event methods http://getcontenttools.com/api/content-tools#component-ui, see:

- component.addEventListener(eventName, callback)
- component.createEvent(eventName, detail)
- component.dispatchEvent(ev)
- component.removeEventListener(eventName, callback)

**Comment by richardprice** [comment]
Heh, typical, started using CT about a month ago :)

Is there anyway to check if a particular component has a particular event listener for a given event? Or will I just have to clear the event of any listeners just to make sure?

**Comment by anthonyjb** [comment]
Hi @richardprice - there's no officially documented way but actually it's pretty simple to do at the moment:

```javascript
if (editor._binding['eventName']) {
    ...has event binding for ...
}
```

If you do upgrade to the latest version of the library then take a look at the [getting started](http://getcontenttools.com/getting-started) and [saving strategies](http://getcontenttools.com/tutorials/saving-strategies) pages again.

**Comment by richardprice** [comment]
@anthonyjb Thats fantastic, thank you very much for that!  I'm using the example angular directive code, so that might be a worthwhile addition to that as Im sure many people will run into the same issue (multiple bindings).

Just a small correction to the code:

```
if (editor._bindings['eventName'] && editor._bindings['eventName'].length > 0) {
    ...has event binding for eventName...
}
```

(the binding collection/object is `component._bindings`)

**Comment by iit2011081** [comment]
@andyjbgm 
Where I need to write my event listener , please see my code , i have done this way. Its not working, please tell me where I am going wrong. Also, ev.regions is giving undefined. How can I use 'this' inside $scope.apply. 
```
app.directive('ngEditor',  function(){

    function link(scope, element, attrs){

        // Initialise the editor
        scope.editor = new ContentTools.EditorApp.get();
        scope.editor.init('[ng-editor]', 'ng-editor');

        // Bind a function on editor save
        if (scope.editor._bindings['saved'] && scope.editor._bindings['saved'].length > 0) {

        }
        scope.editor.addEventListener('saved', function (ev) {
            scope.$apply(function(){
                scope.regions = ev.regions;
                console.log(scope.regions);
                console.log(ev.detail().regions);
            });
        });
    }
    return {
        link: link
    }
})
```
