### ISSUE TITLE
text is undefined bug

### ISSUE THREAD

**Issue by Eeliya** [GetmeUK/ContentTools#187]
I'm trying to create a video tag with a long src and I get `text is not defined`

**Comment by anthonyjb** [comment]
Hi @Eeliya please provide the full traceback from the console if possible, also can you provide the steps or code required to reproduce the bug.

**Comment by Eeliya** [comment]
in ContentEdit - src/scripts/videos.coffee line 50

[The error line](https://github.com/GetmeUK/ContentEdit/blob/master/src/scripts/videos.coffee#L50)

**Comment by anthonyjb** [comment]
@Eeliya thanks I'll push a fix for this shortly.

**Comment by anthonyjb** [comment]
A fix for this has now been pushed.
