### ISSUE TITLE
Making perfect <hr>

### ISSUE THREAD

**Issue by l2aelba** [GetmeUK/ContentTools#189]
Im trying to make a new tool like `<hr>`

```javascript
ContentTools.Tools.HR = (function(_super) {
	__extends(HR,_super);
	function HR(){return HR.__super__.constructor.apply(this,arguments);}
	ContentTools.ToolShelf.stow(HR,'hr');
	HR.label = 'HR';
	HR.icon = 'hr';
	HR.canApply = function(element,selection){return element.content;};

	HR.apply = function(element, selection, callback) {
		var hr, cursor, tail, tip;
		cursor = selection.get()[0] + 1;
		tip = element.content.substring(0, selection.get()[0]);
		tail = element.content.substring(selection.get()[1]);
		hr = new HTMLString.String('<hr>',element.content.preserveWhitespace());
		element.content = tip.concat(hr,tail);
		element.updateInnerHTML();
		element.taint();
		selection.set(cursor,cursor);
		element.selection(selection);
		return callback(true);
	};
	return HR;
})(ContentTools.Tool);
```

**Problem is :**
- This insert inside `<p></p>` , How can I un-wrap the `<p>`tag ?
---- When save , this unwrap `<p>` tag, oh wired.
- Cant select (focus), Should be possible to select and remove it

**Comment by anthonyjb** [comment]
Hi @l2aelba,

The `<HR>` element is a block level element and therefore the editor want handle it as part of the contents of a text element (see the first note here: http://getcontenttools.com/api/content-select).

You'd need to create a custom element class/type to do this ideally, unfortunately there's no tutorial about doing this though I've been working through this task with a friend recently and hope to be able to provide an example in the not too distant future. In the mean time you could take a look an existing element class such as the [`Static` class](https://github.com/GetmeUK/ContentEdit/blob/master/src/scripts/static.coffee) as a basis for writing your own.

For the tool you'd have to look to split the paragraph into 2 elements inserting the horizontal rule between them, if you look at the code for the return key [here](https://github.com/GetmeUK/ContentEdit/blob/master/src/scripts/text.coffee#L321) this is a pretty good example on where to get started.

**Comment by l2aelba** [comment]
@anthonyjb Thanks , So I came to this so long :+1: 

```javascript
ContentTools.Tools.HR = (function(_super) {
	__extends(HR,_super);
	function HR(){return HR.__super__.constructor.apply(this,arguments);}
	ContentTools.ToolShelf.stow(HR,'hr');
	HR.label = 'HR';
	HR.icon = 'line-break';
	HR.canApply = function(element,selection){return element.content;};

	HR.apply = function(element, selection, callback) {
		var hr = new ContentEdit.Static('hr',{},'');
		element.parent().attach(hr, element.parent().children.indexOf(element));
		return callback(true);
	};
	return HR;
})(ContentTools.Tool);
```
But seems like I can remove `<hr>` after added.

**Comment by anthonyjb** [comment]
Because you've made it a static element (statics can't be interacted with for the most part) - you would need to create a custom element type for `hr`s.
