### ISSUE TITLE
Is there a list of frameworks build with ContentTools?

### ISSUE THREAD

**Issue by AndreasFurster** [GetmeUK/ContentTools#190]
I wanted to write my own framework with ContentTools. I got an idea of [TidyCms v1](http://v1.tidycms.com/docs/). Basically the same idea, but even simpler.

- No database
- No advanced templating
- Editing plain html files 
  (maybe even singlepage)
- 'REAL' wysiwyg fealing
- Editing text, images and repeatables

I'm building a lot of websites for clients that are just to simple for big, complex CMSes.

I wanted to write my own, but I can't let it go to think that more people thought of this. 
Why write my own if there already solutions out there?

Is there any list of saving implementations or complete CMSes? Or does anyone know of a project like this? Anyone more interested in this?

**Comment by anthonyjb** [comment]
Hi @AndreasFurster thanks for the interest in CT and sorry for the slightly delayed response,

As far as I'm aware there are a number of people using ContentTools in their own personal CMS projects, there's a couple of integrations to existing frameworks and there's one small CMS project that's open source. The CT site itself and several other small sites I've developed are built using the techniques I've discussed in the [Saving strategies tutorial](http://getcontenttools.com/tutorials/saving-strategies) and maybe a useful starting point for your project. 

The team here is also currently working on a Flask based OpenSource CMS that will hopefully be release before the end of the year - but it will be of the bigger variety.

#### Integrations
- Dyango (https://github.com/Cotidia/django-contenttools-demo)
- YII (http://www.yiiframework.com/extension/yii2-content-tools/)
- Wordpress (https://pagebuildersandwich.com/)

#### CMS projects
- Lights (https://github.com/bedriva/lights)

Hope that helps.

**Comment by Rubytastic2** [comment]
Any other projects in the rails / php world that integrate ?
Very much thanks for content tools looks exactly what we need
