### ISSUE TITLE
Add support for <col> elements in tables

### ISSUE THREAD

**Issue by shchedrakov** [GetmeUK/ContentTools#191]
I have html code of table:
```html
<table class="table table-striped table-fixed-layout table-wrap">
    <col width="24">
    <col width="9">
    <col width="12">
    ....
    <thead>
        <tr>
            <th>URL</th>
            <th>Words</th>
            <th>Characters</th>
            ...
        </tr>
    </thead>
    <tbody>
        {% for data in tables.tagsInfo %}
            <tr>
                <td>{{ data.url }}</td>
                <td>{{ data.words|number_format(0, ' ', ' ') }}</td>
                <td>{{ data.characters|number_format(0, ' ', ' ') }}</td>
                ...
            </tr>
        {% endfor %}
    </tbody>
</table>
```
And I have next js:
```js
window.addEventListener('load', function () {
    var editor;
    
    ContentTools.StylePalette.add([
        new ContentTools.Style('Author', 'author', ['p'])
    ]);
    
    editor = ContentTools.EditorApp.get();
    editor.init('*[data-editable]', 'data-name');
    editor.start();
});
```
When I click on the ```edit``` button the Content Tools cut ```<col>``` tags from my table.
Why??? It's event broke width of  columns.

Before edit: https://screencloud.net/v/p48W
Editing: http://screencloud.net/v/5dNd
Agter edit: http://screencloud.net/v/dMb8

**Comment by anthonyjb** [comment]
Hi @shchedrakov and thanks for your interest.

ContentEdit doesn't recognize `col` elements I'm afraid, I never added support for them so it's simply ignores them when parsing the `table` element here: https://github.com/GetmeUK/ContentEdit/blob/master/src/scripts/tables.coffee#L87.

It wouldn't be too hard to add support for a `col` editable element I imagine (though as they're invisible it might be better to make them a property of tables) and I'd be very happy to include this in the core library if some one did. I'll flag as an enhancement request for now though in all honesty it's going to be some time before I get to it given the currently scheduled enhancements.

**Comment by anthonyjb** [comment]
@shchedrakov looking at the `col` specs (https://developer.mozilla.org/en/docs/Web/HTML/Element/col) it looks like the `width` attribute you're using it for here is now obsolete and that for the most part `col` is used for setting the number of columns spanned given that I'm not sure it's much benefit over just setting the `colspan` attribute. Thoughts?

**Comment by shchedrakov** [comment]
Thanks for fast answer.
I use ```<col>``` to set column width of all table (columns may have different width). The ```colspan``` attribute that's not what I need. But you right that the ```<col>``` tag is deprecated. I will try to solve my problem through only CSS. I will write about what I got later.

**Comment by shchedrakov** [comment]
@anthonyjb Thank you.
I rewrited my html code and now it works good:
```
<table class="table table-striped table-fixed-layout table-wrap" id="tags-rpt-table-main" data-editable>
    <thead>
        <tr>
            <th style="width: 24%">URL</th>
            <th style="width: 9%">Words</th>
            <th style="width: 12%">Characters</th>
            ....
        </tr>
    </thead>
    <tbody>
        {% for data in tables.tagsInfo %}
            <tr>
                <td>{{ data.url }}</td>
                <td>{{ data.words|number_format(0, ' ', ' ') }}</td>
                <td>{{ data.characters|number_format(0, ' ', ' ') }}</td>
                ...
            </tr>
        {% endfor %}
    </tbody>
</table>
```
