### ISSUE TITLE
Editable element after save

### ISSUE THREAD

**Issue by sticklvl** [GetmeUK/ContentTools#192]
Hello, I found a bug

http://getcontenttools.com/demo

- click edit 
- remove all elements from a region, now we have `<p>` element
- focus it
- click save button
- now we have editable `<p>`
	
This bug element creates in

`_EditorApp.prototype._preventEmptyRegions = function() {
	...
	region.attach(placeholder);
	...
};`

I change 

src/scripts/editor.coffee

`if ContentEdit.Root.get().focused()
	ContentEdit.Root.get().focused().blur()`
	
to

`if ContentEdit.Root.get().focused() and ContentEdit.Root.get().focused().content.html().length>0
	ContentEdit.Root.get().focused().blur()`

**Comment by anthonyjb** [comment]
@sticklvl thanks for reporting this and for the information/fix will post a patch shortly.
