### ISSUE TITLE
Allow to apply style with filtering Class or Type

### ISSUE THREAD

**Issue by l2aelba** [GetmeUK/ContentTools#193]
**Example I have a element like this :**

```javascript
ContentEdit.TagNames.get().register(ContentEdit.Button,'div');
```

But I will use many `div`s in the future , so I cant just set `['div']` in **applicableTo**  :

```javascript
ContentTools.StylePalette.add([new [ContentTools.Style('Large','button-large',['div'])]);]
```

Anyway can I allow / filter like "**div with class .button**" or "**div with ContentEdit.Button**" ?

**Comment by anthonyjb** [comment]
@l2aelba so short answer at the moment this isn't possible, but I think it needs to be so I'm going to tag this as an enhancement and prioritize it hopefully for the next release.

**Comment by l2aelba** [comment]
@anthonyjb Wow , I will wait to next release, thanks

**Comment by anthonyjb** [comment]
Hi @l2aelba,

OK so the new release is out and it's now possible to modify the `StylePalette.styles` method to support whatever selection mechanism you want. For the example you've described you might take an approach similar to this:

```JavaScript
var largeText = ContentTools.Style('Large text','text-large', [{'typeName': 'p'}]);
var largeButtonStyle = ContentTools.Style('Large button','button-large', [{'type': 'Button'}]);
ContentTools.StylePalette.add(largeButtonStyle);

ContentTools.StylePalette.styles = function (element) {
    // If no element is provided return all styles    
    if (element) { return this._styles.slice() }

    // Build a list of applicable styles
    var styles = [];
    for (var i = 0; i < this._styles.length; i++) {
        var style = this._styles[i];
        
        // Check if the style is applicable to all elements
        if (!style._applicableTo) {
            styles.push(style);
            continue;
        }

        // Check if the style is applicable to this element
        for (var j = 0; j < styles._applicableTo.length; j++) {
            var applicableTo = styles._applicableTo[j];
            if (applicableTo.type && applicableTo.type === element.type()) {
                styles.push(style);
                break;
            } else if (applicableTo.tagName && applicableTo.tagName === element.tagName()) {
                styles.push(style);
                break;
            }
        }
    } 
};
```

**Comment by l2aelba** [comment]
@anthonyjb Thanks so much, But must I have the last code ? `ContentTools.StylePalette.styles = function (element) {};` ???

Doesnt it push all style ? Seems like a bug  or I did something wrong

**Comment by anthonyjb** [comment]
Hi @l2aelba I haven't tested the code I must admit, the `styles = function(element) { ... }` overrides the standard `styles` method to add support for selecting styles either by a `tagName` or optionally by a `type` (where type is the type of element - all element classes have a `type` method which should return by default their class name but this does need to be defined by you in your Button class).

**I did spot an obvious issue in the code which I've just updated (was specifying `typeName` not `tagName`.**

The code above should only return all styles if they all match, can you send me the styles you've set up and I'll take a look, if the issue isn't obvious I'll test this in the sandbox later this evening to check the code is solid.

**Comment by l2aelba** [comment]
@anthonyjb  Sorry so long respone.

But im done with this :

```javascript
ContentTools.StylePalette.add([new ContentTools.Style('Large','button-large',[{'type': 'Button'}])]);
```
And : 

```javascript
ContentTools.StylePalette.styles = function(element) {
	var tagName;
		tagName = element.tagName();
		if (element === void 0) {
			return this._styles.slice();
		}
		return this._styles.filter(function(style) {
			if (!style._applicableTo) {return true;}
			if (style._applicableTo[0]['type']) {
				return style._applicableTo[0]['type'] === element.type();
			}
			return style._applicableTo.indexOf(tagName) !== -1;
		});
};
```
