### ISSUE TITLE
Save doesn't work when the last action is the deletion of a table header

### ISSUE THREAD

**Issue by nXu** [GetmeUK/ContentTools#194]
I encountered something strange: when I edit a contentable area and the last action I do is deleting a table header (clicking inside the `thead` and pressing delete), then click save, the buttons disappear and there is no saving perfomed, the editor kind of dies.

Could this be some kind of a bug, or am I doing something wrong? Thanks in advance!

**Comment by anthonyjb** [comment]
Hi @nXu thanks for the information.

I've tried to reproduce this error as you've described a couple of times now both using the sandbox in the repo and demo page on the website but I'm unable to. This doesn't mean this isn't a bug though just that I can't reproduce it to fix, can you provide me with:

- Any error information output to the console during your editing session.
- Can you try to reproduce with the sandbox or demo editors and if you can send me instructions on how to do so so I can track it down.

Thanks for your help in advance.

**Comment by nXu** [comment]
Thanks for your quick answer, @anthonyjb 
I could not reproduce the error in the sandbox either, it must be an error in my integration somewhere. I'll try my best to debug.

**Comment by concept-core** [comment]
@nXu did you already figured it out and is it solved or not yet ?

**Comment by anthonyjb** [comment]
@concept-core if you're able to reproduce the area @concept-core please let me know (ideally using the demo or sandbox page) as we weren't able to making it difficult to follow up on this.

**Comment by concept-core** [comment]
@anthonyjb I will try to do this tomorrow.

It seams it's something I encounterd to but I am not completely sure. 
If I cannot recreate it and he doesn't respond you can close this issue until further notice.

**Comment by nXu** [comment]
I was not yet able to figure out the reason as I haven't really taken the time, but it apparently doesn't always happen. I can't reproduce it in the online demo so I think it has something to do with how I integrated ContentTools, but for the most part, I just copypasted the code from the Getting started guide

**Comment by concept-core** [comment]
It is possible that you changed the ajax request and you got a 500 error.
I had that happen and I only saw a gear icon.

I am not sure if that is what you saw.

**Comment by concept-core** [comment]
@nXu @anthonyjb 
This is what I have encounterd when I saved to a page that returned a 500 internal server error.
I think this is the closest I can get the to actual problem.

The gear icon keeps spinning and doesn't show a actual error for the user.
http://s32.postimg.org/n5av7e2cl/Schermafbeelding_2016_05_02_om_09_46_46.png

**Comment by nXu** [comment]
@concept-core 
My error is most likely not related. There is no request being sent, there's just a JS error:
`content-tools.js:3523 Uncaught TypeError: Cannot read property 'innerHTML' of null`

**Comment by concept-core** [comment]
@nXu @anthonyjb 

I think I am getting there.
First off @nXu I am not sure if you use jquery or xhr, but I changed my code to jquery.

I think you didn't get the following code to work : 
```javascript
// Note this is the standart code that is provided
        // Send the update content to the server to be saved
        function onStateChange(ev) {
            // Check if the request is finished
            if (ev.target.readyState == 4) {
                editor.busy(false);
                if (ev.target.status == '200') {
                    // Save was successful, notify the user with a flash
                    new ContentTools.FlashUI('ok');
                } else {
                    // Save failed, notify the user with a flash
                    new ContentTools.FlashUI('no');
                }
            }
        };
```

Now let's change it to jquery.
```javascript
       // Save object
        var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content'); // For laravel
        var data = $.extend({}, {"_token": CSRF_TOKEN}, regions); // combine regions and csrf token
        $.ajax({
            url: "save",
            type:"POST",
            data: data,
            success: function(data){
                console.log(JSON.stringify(data));
            },
            error: function(){ 
                // Build some error notification in here.
                alert("error!!!!");
            },
            complete: function(data) {
                editor.busy(false); // This will fix the gear icon
            }
        }); //end of ajax
```

I will add my complete file so you can check it out completely.

```javascript
window.onload = function() {
    // Run code
    var editor;

    ContentTools.StylePalette.add([
        new ContentTools.Style('Author', 'author', ['p'])
    ]);

    editor = ContentTools.EditorApp.get();
    editor.init('*[data-editable]', 'data-name');

    editor.addEventListener('saved', function (ev) {
        var name, payload, regions, xhr;

        // Check that something changed
        regions = ev.detail().regions;
        if (Object.keys(regions).length == 0) {
            return;
        }

        // Set the editor as busy while we save our changes
        this.busy(true);

        // Collect the contents of each region into a FormData instance
        // payload = new FormData();
        // for (name in regions) {
        //     if (regions.hasOwnProperty(name)) {
        //         payload.append(name, regions[name]);
        //     }
        // }

        // // Send the update content to the server to be saved
        // function onStateChange(ev) {
        //     // Check if the request is finished
        //     if (ev.target.readyState == 4) {
        //         editor.busy(false);
        //         if (ev.target.status == '200') {
        //             // Save was successful, notify the user with a flash
        //             new ContentTools.FlashUI('ok');
        //         } else {
        //             // Save failed, notify the user with a flash
        //             new ContentTools.FlashUI('no');
        //         }
        //     }
        // };

        // Save object
        var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
        var data = $.extend({}, {"_token": CSRF_TOKEN}, regions);
        $.ajax({
            url: "save",
            type:"POST",
            data: data,
            success: function(data){
                console.log(JSON.stringify(data));
            },
            error: function(){ 
                alert("error!!!!");
            },
            complete: function(data) {
                editor.busy(false);
            }
        }); //end of ajax

        // xhr = new XMLHttpRequest();
        // xhr.addEventListener('readystatechange', onStateChange);
        // xhr.open('POST', 'save');
        // xhr.send(data);
    });
};
```

**Comment by concept-core** [comment]
@nXu which version of contenttools do you use ?

**Comment by concept-core** [comment]
@nXu What version of contenttools are you running and do you have a demo of the how you implemented it ?

**Comment by anthonyjb** [comment]
Closing as we don't have a reproducable error report but if someone can reproduce the error and provide steps for doing so that would be a big help and I'll re-open the issue.
