### ISSUE TITLE
Refresh or reset plugin?

### ISSUE THREAD

**Issue by jedidas** [GetmeUK/ContentTools#197]
Hello, could you please help me?
I tried the ContentTools on a project and is fantastic. For my project must dynamically add new several editable areas dynamically.
Is there any method to refresh or restart the plugin to detect the newly added content?

**Comment by anthonyjb** [comment]
Hi @jedidas - thanks for your interest and kind comments.

This feature isn't available currently by is planned (see issue/feature #13). However in the mean time as a work around you could try the following approach:

```javascript
function addNewRegion(domRegion) {
    // Add a new region to the editor
    var editor = ContentTools.EditorApp.get();

    // Add the region to the editor
    editor._domRegions.push(domRegion)
    
    // If the editor is not 'editing' we're done
    if (!editor.isEditing()) {
        return;
    }

    // Initialize the new region
    var name = domRegion.getAttribute(editor._namingProp);
    if (!name) {
        name = editor._orderedRegions.length;
    }

    editor._regions[name] = new ContentEdit.Region(domRegion);
    editor._orderedRegions.push(name);

    // Store the date at which the regions was last modified (used when saving 
    // to check for changes).
    editor._regionsLastModified[name] = editor._regions[name].lastModified();
} 
```

So in using this code you create your new region element and add it to the DOM, then send a reference to it to the `addNewRegion` method. I haven't tested the code scavenged directly from the editor `init` and `start` methods so it should work - let me know how you get on :)

**Comment by danielrob** [comment]
I had exactly the same question in mind. Great there is workable workaround. I was curious as to what happens if you call the editor.init method multiple times (as a way for it to pick up the added (or subtracted) elements? Or would this cause all sorts of madness?

**Comment by anthonyjb** [comment]
Hi @danielrob - the [latest release - 1.2.5](https://github.com/GetmeUK/ContentTools/releases/tag/1.2.5) looks to resolve this issue some what, whilst you shouldn't call `init` consecutively you can now call the `editor.syncRegions()` method which will pick up additional regions/fixtures.

The only caveat is that you will either need to specify a query string on `init` (e.g `editor.init('.editable')` ) or provide a new set of regions when calling `syncRegions` (e.g `editor.syncRegions(myDomElements)`).

**Comment by danielrob** [comment]
Plenty fantastic. I came at the write time! Thanks:)
