### ISSUE TITLE
Add plugin to a cdn for quick use ?

### ISSUE THREAD

**Issue by concept-core** [GetmeUK/ContentTools#198]

**Comment by anthonyjb** [comment]
Yep I agree with this, I've had a couple of CDN providers contact me an offer a free account to host the project so I'll take a look over them this weekend and see about hosting the releases on a CDN.

**Comment by concept-core** [comment]
Also take a look at : https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by anthonyjb** [comment]
Sweet thanks I'll do that :+1:

**Comment by anthonyjb** [comment]
@concept-core took your advice thanks and have submitted a pull request for inclusion on jsdelivr so I'll update and close this issue when/if the project gets approved and included. Hopefully I got my pull request correct!

**Comment by concept-core** [comment]
@anthonyjb  sure no problem, thought it was easier for everyone if you can just use a cdn.

Let's hope it gets accepted now.
