### ISSUE TITLE
Angular integration

### ISSUE THREAD

**Issue by martyLauders** [GetmeUK/ContentTools#20]
ContentTools is really amazing, and maybe what I have been looking for.

But, question: we are working with an AngularJS driven project. We have a lot of directives, and I was wondering if it is possible to combine AngularJS and ContentTools.

This way I could call in directives, give them specific attributes, and fastly create complex content blocks in the page.

Do you feel it could be possible?

Greetings,

Maarten

**Comment by guillaumepiot** [comment]
@martyLauders that should be no problem, I can provide you with an example. But first, which version of Angular are you running on your project?

**Comment by martyLauders** [comment]
That would be amazing. I'm running 1.4.

**Comment by guillaumepiot** [comment]
Hi @martyLauders, I have created a demo which can check here: https://github.com/Cotidia/contenttools-angularjs

Basically, you can create a directive that will bind the DOM element to the editor. Then, the data will retrieve in the scope as `$scope.regions`.

    angular.module('editorApp', [])
        .directive('ngEditor',  function(){
            
            function link(scope, element, attrs){

                editor = new ContentTools.EditorApp.get()
                editor.init('.editable', 'ng-editor')

                editor.bind('save', function(regions, autoSave){
                    
                    scope.$apply(function(){
                        scope.regions = regions;
                    });

                    // "regions" contains all the html for each editable regions
                    // Now, "regions" can be saved and used as needed.

                })

            }

            return {
                link: link
            }
            
        })

In the HTML, you can simply use the directive as follows:

    <div ng-editor="my-content">
        <p>Some content...</p>
    </div>

    <div ng-editor="my-content-another">
        <p>Another content....</p>
    </div>

I hope that helps.

**Comment by anthonyjb** [comment]
Awesome work @guillaumepiot :+1:

**Comment by martyLauders** [comment]
Ok, guillaumepiot, that is already incredible :)

Now, what I want to achieve is that, when I add in an attribute, that is linked to a directive, that it renders the directive. For example:

![image](https://cloud.githubusercontent.com/assets/1078132/10022608/095a8116-614e-11e5-8f2b-3ef7e2e75e22.png)

And my directive would be:

    directive('testDirective', function() {
    return {
            template: '<div>TEST</div>',
            restrict: 'A',
            replace: true,
            link: function(scope) {
               console.log('The directive loaded');
            }
        };
    })

Do you think this is possible? I can't seem to get it to work. 

I'd put up a quick demo, but am on the road, sorry!

**Comment by anthonyjb** [comment]
@martyLauders Where would the directive be inserted? Would it be within an editable region or would the directive actaully be an editable region (e.g contain editable content, `<p>`, `<img>`, etc.)

Could you provide a bit more detail on what you're trying to achieve?

**Comment by martyLauders** [comment]
The region would be within an editable region. What I am trying to achieve is that I could add just a <div>, add an attribute, for example: parrallax=true, and the directive would then work on this div.

But now I have the feeling that angularjs doesn't notice the change in attributes.

Does it make sense what I am asking / trying to do?

**Comment by anthonyjb** [comment]
Hi @martyLauders sorry my knowledge of Angular is really limiting me here. The problem here I think is that if Angular updates the contents of an editable region while it's being edited then the editor and angular will become out of sync (e.g the editor wont know about the new element added by angular). 

If you can provide an example of the HTML before and after that you're trying to achieve I might be able to provide a solution that's not specific to angular?

**Comment by piyushchauhan2011** [comment]
:+1: Thread helped a lot for clarifying some issues

**Comment by iit2011081** [comment]
saved event listener is getting called multiple times when I save one field , any solution for this ?

**Comment by anthonyjb** [comment]
@iit2011081 this sounds like the issue is caused by the editor being initialized multiple times without being destroyed?

**Comment by iit2011081** [comment]
@anthonyjb this is the whole code which I have written . Please see where I am going wrong.
```
app.directive('ngEditor',  function(){

    function link(scope, element, attrs){

        // Initialise the editor
        scope.editor = new ContentTools.EditorApp.get();
        scope.editor.init('[ng-editor]', 'ng-editor');

        // Bind a function on editor save
        if (scope.editor._bindings['saved'] && scope.editor._bindings['saved'].length > 0) {

        }
        scope.editor.addEventListener('saved', function (ev) {
            scope.$apply(function(){
                scope.regions = ev.regions;
                console.log(scope.regions);
                console.log(ev.detail().regions);
            });
        });
    }
    return {
        link: link
    }
})
```
