### ISSUE TITLE
how can I save change on express framwork ?

### ISSUE THREAD

**Issue by hiepxanh** [GetmeUK/ContentTools#202]
I'm working with nodejs and found that kind of "context editor". You are so impressed but how can I save my changed to my file, after edit ? I'm using nodejs and don't know how to edit my server code to do that.
I understand the tutorial with python but I can't apply it to my nodejs code

**Comment by anthonyjb** [comment]
Hi @hiepxanh,

What part are you struggling with? For example have you got as far as being able to send the content from CT to the a view on the web server?
