### ISSUE TITLE
 Invalidate applied classes on tag change

### ISSUE THREAD

**Issue by andreygolovin** [GetmeUK/ContentTools#203]
I found minor issue with custom style classes.

Here is steps to reproduce:

* navigate to http://getcontenttools.com/demo
* switch to edit mode
* select paragraph
* apply custom style to this paragraph (Definition or Note)
* select paragraph text and switch text tag for header (h1 or h2)
* definition and note tags will be applied to h1

**Comment by anthonyjb** [comment]
Hi @andreygolovin - thanks for the detailed report, I'll look to patch this today.
