### ISSUE TITLE
ImageUploader - resize image before upload

### ISSUE THREAD

**Issue by saso-petrov** [GetmeUK/ContentTools#204]
I can't find the way to make image smaller before upload to the server. The sandbox.js does not provide the solution. I think many of us have same problem.

Please help.

**Comment by anthonyjb** [comment]
Hi @saso-petrov,

Thanks for your interest in CT. Regarding your question can you clarify it for me? Do you want to shrink the image in size (e.g width x height) client-side and then upload the image to the server before using the URL returned by the server to show the image in the CT image dialog?

If so, an example of client-side image manipulation was posted here: https://github.com/GetmeUK/ContentTools/issues/136 (thanks to @Qqwy).

In my implementations currently I reduce the size of the image server-side and store a copy of the original as well as the working draft (with an admittadly 'space is cheap so ehh...' attitude), this way I always have the original to use when creating resized versions of the image which provides the best output quality. If you haven't already looked it's worth checking out the [Handling Image Uploads](http://getcontenttools.com/tutorials/handling-image-uploads) tutorial.
