### ISSUE TITLE
addCSSClass when on blur

### ISSUE THREAD

**Issue by rhnkyr** [GetmeUK/ContentTools#207]
Hi guys,

I try something like this : 

`ContentEdit.Root.get().bind('focus',function (element) {  ContentEdit.addCSSClass(element, 'myClass');});`

but it gives **content-tools.min.js:3 Uncaught TypeError: domElement.getAttribute is not a function**

i tried it with jquery and my code is :

`$(element.tagName()+'.ce-element--focused').addClass('myClass');`

but when i save Content Tools remove my custom class.

What i want is when i save modification, myClass would stay.

Cheers.

**Comment by rhnkyr** [comment]
Anybody? It is really urgent. My client wait for it.

**Comment by anthonyjb** [comment]
Hi @rhnkyr - I'll try and help though abroad at the mo and my internet connection is patch at best and I'm using a borrowed netbook with an unfamiliar keyboard layout lol

So you seem to be trying to add a CSS class to an element whenever it's focused. You almost had it right in your original sample code but you're calling the `addCSSClass` method against the  `ContentEdit` namespace, it needs to be called instead against the `element` instance, so:

```JavaScript
ContentEdit.Root.get().bind('focus', function (element) { 
    element.addCSSClass('myClass');
});
```

**Comment by rhnkyr** [comment]
Thank u for ur reply @anthonyjb . How did i miss it :)
