### ISSUE TITLE
How to change the position of the tool-box??

### ISSUE THREAD

**Issue by mallikarjuna909** [GetmeUK/ContentTools#208]
Actually, The tool-box position is fixed and drag-able. But now i want to change the position of the tool-box and i also want to remove drag-able functionality.

**Comment by mallikarjuna909** [comment]
After the couple of Hours, I got the solution. Here you go.
Change the mount function.

_EditorApp.prototype.mount = function() {
      this._domElement = this.constructor.createDiv(['ct-app']);
      document.getElementById('YourPositionID').insertBefore(this._domElement, null);
      return this._addDOMEventListeners();
    };

**Comment by oodavid** [comment]
You might want to read #120
