### ISSUE TITLE
"Option" as alternative for Properties dialog

### ISSUE THREAD

**Issue by l2aelba** [GetmeUK/ContentTools#211]
I wish ContentTools has an alternative like **"Select/Option"** , Not just switch on/off

Think if you have many styles :D

![screen shot 2016-05-20 at 13 29 47](https://cloud.githubusercontent.com/assets/983458/15426501/54c7e1ee-1e8f-11e6-8bc3-a4ec1337e941.png)

Thanks

**Comment by anthonyjb** [comment]
Hi @l2aelba thanks for this you've highlighted something I haven't come across myself previously.

So for scenarios where you have a significant number of styles I agree possibly a compact input option/component would be useful and I'm open for suggestions here, select/options suffer the same problem as the scrollable on/off options above in that if you have a lot of them you'll need to scroll, there also unintuitive (IMHO) when selecting multiple options (which is required to set multiple CSS classes).

In general with styles I try not to build a palette of styles in the way you've highlighted in your example, I instead try to keep styles to just the classes a user of the editor will apply and give them names that are where possible semantically relevant, such as **Quote**, **Byline**, **Note**, etc. I realize everyone has there own way of doing these things but for the most part I general find few styles which a user may require in the editor are globally applicable to *all pages and all elements *of a site and that good organizations of those styles will often helps keep the list of styles short making it easier for the user and keeping the site look'n'feel consistent. Move advanced users (such as developers) of course can always manually set styles against an element via the attributes tab. But that just my 2 cents I'm interested to hear how others are using the system.
