### ISSUE TITLE
Edit text link different on Chrome and Firefox

### ISSUE THREAD

**Issue by l2aelba** [GetmeUK/ContentTools#212]
**Firefox :** 
![firefox](https://cloud.githubusercontent.com/assets/983458/15426875/9f3811b6-1e91-11e6-895a-ec958ef425d5.gif)

**Chrome :**
![chrome](https://cloud.githubusercontent.com/assets/983458/15426882/a42f097c-1e91-11e6-85de-458854ee9b03.gif)

Seems like Chrome when continue typing at last or first char, So link does not continue.

_PS: Im not sure, which is correct one :D_

**Comment by anthonyjb** [comment]
I'm currently away (back on the 27th) so I'm unable to test but my first thoughts are that this behaviour might be down to the way `contenteditable` behaviour is defined in each browser - I'll confirm this when I get back.

In the meantime does anyone have any thoughts on which is the correct behaviour and reasons for?

**Comment by anthonyjb** [comment]
OK having tested myself the behaviour appears to be browser specific and occurs using `contenteditable` (e.g it's not specific to CT). In addition the behaviour only occurs when the cursor is positioned at the end of a block of text, if the cursor is placed at the end of a link within a text block (e.g surrounded by at least spaces on either side) then the behaviour is per the chrome example in both cases.

At this time I'm not going to attempt to resolve the behaviour between the browsers as it doesn't have a significant impact on a user's experience (e.g their ability to edit content) and the difference is in the way the browsers have decided to implement `contenteditable` (or possibly their selection behaviour).
