### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by mstojanovv** [GetmeUK/ContentTools#213]
Hi.

http://oi66.tinypic.com/r1j5m1.jpg

What can cause this problem.
I just upgraded to the latest version, in the previous versions seems to work good.

This problem happens when i upload an image and Click insert. The image is inserted 2 times inside the editor area and this error appears in the console.

Any ideas?
Thanks.

**Comment by anthonyjb** [comment]
Hi @mstojanovv,

Can you provide a full stack trace from the browser console to help. My first thoughts are that when you upgraded to the latest version of the library you didn't upgrade your image uploader code, the libraries event system changed and this requires some minor changes to your image uploader code. The tutorial has been updated and should help you if this is the cause of the issue: http://getcontenttools.com/tutorials/handling-image-uploads
