### ISSUE TITLE
Add !default to all global variables in scss

### ISSUE THREAD

**Issue by vudaltsov** [GetmeUK/ContentTools#214]
Please, add !default to all global variables in _settings.scss, otherwise there is no possiblity to overwrite them...

This approach is used in bootstrap, for example. [documentation at sass-lang.com](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_)

**Comment by anthonyjb** [comment]
Hi @vudaltsov - thanks for the solid suggestion will add  this to the next release.
