### ISSUE TITLE
Unable to resize <img> with border-radius. Video. Bug.

### ISSUE THREAD

**Issue by oodavid** [GetmeUK/ContentTools#215]
Because a tag with border-radius doesn't accept events in the clipped of areas, I'm unable to highlight the corner to start the resize operation.

Figured a video was easier:

https://www.youtube.com/watch?v=Gy2cnjHgi_I

**Comment by anthonyjb** [comment]
Short term I'd recommend either modifying the style during editing to remove the border radius (e.g ce-element-type-image border-radius: none !important;) or increase the value of the ContentEdit.RESIZE_CORNER_SIZE to compensate (e.g I your border radius is 15 consider setting this to 30 to compensate.)

These aren't ideal though so once I'm back from Mexico I'll have a think about how we might tackle this for the next release - open for suggestions.
