### ISSUE TITLE
keep aspect ratio image

### ISSUE THREAD

**Issue by concept-core** [GetmeUK/ContentTools#218]
Hello anthony,

Is there a easy way to keep the aspect ratio of the image ?
Of course I know that we used a custom solution for me but would there be a way in js to keep the aspect ratio of the image ?

Best regards,
Wouter.

**Comment by anthonyjb** [comment]
Hi Wouter,

The ratio is fixed by default and set by the size that you give the image when you create it, see here: https://github.com/GetmeUK/ContentEdit/blob/master/src/scripts/images.coffee#L16

If your creating the image dynamically in JS that means you'll need to set a width and height in the attributes, e.g:

```
var image = new ContentEdit.Image({src: '...', width: 400, height: 300});
```

If a width and height aren't set and the image is parsed from the page then the editor will query the size of the image in an attempt to set a width and height, see here: https://github.com/GetmeUK/ContentEdit/blob/master/src/scripts/images.coffee#L143

**Comment by concept-core** [comment]
But if I don't set the height and width the image will be inserted very small.
Is there a  way to insert percentages as values ?

**Comment by anthonyjb** [comment]
It defaults to a minimum set by  `ContentEdit.DEFAULT_MIN_ELEMENT_WIDTH` (80 by default). You can't set a percentage I'm afraid.

What is the problem you're having setting a width and height for the image? Are the diminensions not available to you?

**Comment by concept-core** [comment]
Well I need to find a way to get the sizes back from kcfinder.
But I also saw that JS has a image class that can be used so I will try that.

**Comment by anthonyjb** [comment]
@concept-core Did you have any luck with this?

**Comment by concept-core** [comment]
@anthonyjb No sorry did not have the time since I have been busy with work.
I will check if I can get it working in the afternoon.

**Comment by concept-core** [comment]
@anthonyjb Here is the javascript code that returns the full width and height of a image ( get's it from url )
```
function getImageSizes(url) {
    var img = new Image();
    img.onload = function(){
        alert( this.width+' '+ this.height );
    };
    img.src = url;
}
```

Maybe use that in the core so people do not have to give in the images sizes ?

**Comment by anthonyjb** [comment]
Hi @concept-core, thanks for this, whilst the image upload code isn't part of the core library (or any of the libraries people implement there own) I think this is a really helpful snippet so I'll include it in the Image uploads tutorial on the site and credit you for the code. Thanks again :+1:

**Comment by concept-core** [comment]
But isn't there a way to insert that snippet in the main code and make a option to turn it on or off ?
Maybe it will help out some people with just turning it on if needed ?

**Comment by anthonyjb** [comment]
@concept-core the core code doesn't provide an image handler, there's a skeleton image handler in the demo that doesn't actually load an image (so not much use there) but there isn't an core image handler per ce.

**Comment by anthonyjb** [comment]
@concept-core I could add the code above to the sandbox to show how to integrate KCFinder, especially if you fancy helping out with a tutorial about integrating KCFinder for the site ;)

**Comment by concept-core** [comment]
@anthonyjb Yeah sure I am willing to help out.
I actually created a repo for the KCFinder intergration.

I will make a tutorial for it this week ( I don't know when yet ).
But I will contact you when I have more information about it.

Have a nice day.
