### ISSUE TITLE
Shift+Enter inserts newlines instead of line-breaks?

### ISSUE THREAD

**Issue by shawnlehner** [GetmeUK/ContentTools#220]
I noticed a strange behavior in my local testing. Using the Shift+Enter combination inserts a new line instead of a line-break (`<br>`) element. This differs from the line-break tool which does correctly insert the `<br>`.

Am I missing something? Is this a configuration option?

**Comment by anthonyjb** [comment]
Hi @shawnlehner - can you confirm a couple of details for me?

- Which version of CT are you using?
- Are you pressing shift-enter in a text or preformatted text block (e.g `<p>` vs `<pre>` tag).
- Does this behaviour occur for you when you use the online demo?

I can't replicate this in my local sandbox or on the online demo but if you can then my guess is if that perhaps for a given OS and/or browser I'm not registering the shift key being held down. If so can you provide me with OS/Browser details so I can attempt to replicate?

Thanks in advance.

**Comment by anthonyjb** [comment]
Ah I wasn't saving so on inspecting the element in edit mode the BRs are there. Will take a look at this now.

**Comment by anthonyjb** [comment]
Quick experiment and I think the cause is that the shift+enter key isn't triggering a modify event against the text element so when you save it returns an out of date version of the content. Thanks for the spot. Will push out a fix in the next release tomorrow.

**Comment by shawnlehner** [comment]
Great. Thank you very much for the help!

Amazing editor by the way!
