### ISSUE TITLE
Regions changes counter have minor bug

### ISSUE THREAD

**Issue by a-komarev** [GetmeUK/ContentTools#221]
I have `saved` event listener, and there is a check for the regions data being changed.

```js
if (Object.keys(regions).length === 0) {
    return;
}
```

But I found that it's not 100% working solution. Here is how to replicate it step-by-step:

1. Open sandbox `index.html` file (you see `5 rules for naming variables` title there).
2. Click edit button.
3. Edit title. Change integer `5` to `6` for example. **Don't click save just yet!**
4. Revert your changes by changing integer from `6` to `5` (as it was initially).
5. Click save and `Object.keys(regions).length` will return `1`.

**Note:**

- If you will revert changes using undo tool - `Object.keys(regions).length` will return `0`.
- If you will revert changes by typing them manually - `Object.keys(regions).length` will return `1`.

**Comment by anthonyjb** [comment]
Hi @a-komarev - I think the behaviour you are describing is the expected/correct behaviour.

ContentTools doesn't use a diff to determine if the contents has changed instead it uses a timestamp against each region which records the last time the region's content was changed (tainted). This is the way many editors work I believe, for example the behaviour of sublime or LibreOffice Writer is the same.

Reverting with Undo sets the modified timestamp for the effected region back to the the timestamp at the point the history snapshot was taken and so if you undo all changes then the timestamp will be reset to the initial timestamp and the editor will know that no changes have occurred.

**Comment by a-komarev** [comment]
Thank you for detailed clarification.
