### ISSUE TITLE
Add body class while editor is active

### ISSUE THREAD

**Issue by damiansb** [GetmeUK/ContentTools#224]
I would like to suggest adding a **class to the body element** while the editor is active, so it becomes really simple to style certain elements conditionally, like putting an outline on certain elements. 

Something like:

`<body class=" ... ct-editing">`

Best regards and congratulations on this great project.

**Comment by anthonyjb** [comment]
Hi @damiansb thanks for the kind words.

**Re. Adding a class when editing**
Ideally I wouldn't have CT modify the any elements outside of the `ct-app`, and similarly with ContentEdit classes are only applied to elements managed by the library.

Having said that for individual integrations I can certain imagine a number of ways in which this might be very useful. My recommendation for the moment would be to simply add the class as part of the editor start/stop process like so:

```JavaScript
var editor = ContentTools.EditorApp.get();

// Add a class to the body when the editor is started...
editor.addEventListener(
    'start', 
    function() { 
        document.body.classList.add('editing'); 
    }
);

// ...remove the class when the editor is stopped. 
editor.addEventListener(
    'stop', 
    function() { 
        document.body.classList.remove('editing'); 
    }
);
```

**Comment by damiansb** [comment]
I understand your point of view, and your solution covers the needs perfectly. Thanks a lot for your feedback. Keep the good work!
