### ISSUE TITLE
Spacing before and after content being removed on save

### ISSUE THREAD

**Issue by shawnlehner** [GetmeUK/ContentTools#225]
When in edit mode you can use line breaks, and empty elements, to create additional spacing between paragraphs or content. As soon as edit mode exits, this space is removed. Is this by design? If so, is there a suggested way for users to create space between their content?

**Comment by anthonyjb** [comment]
HI @shawnlehner - there's a stackoverflow post which includes a description on why this is the default behaviour and instructions on patching the editor to modify this behaviour if you need to (http://stackoverflow.com/questions/36883079/how-to-preserve-multiple-br-when-no-content-before-or-after-with-contenttools/36954440#36954440)

My recommendation however would be to use CSS and not additional line-breaks or paragraphs to add extra space between elements in scenarios where the default spacing for an element needs to be overwritten. For example:

```css
.mind-the-gap {
    margin-bottom: 40px;
}
```

```JavaScript
ContentTools.StylePalette.add([new ContentTools.Style('Mind the gap', '.mind-the-gap')]);
```

You'll then be able to apply the `.mind-the-gap` class to any editable element (other than static elements) within a region (e.g via the inspector bar > properties dialog > style tab).
