### ISSUE TITLE
Adding content after Preformatted Text

### ISSUE THREAD

**Issue by themoor88** [GetmeUK/ContentTools#226]
I can't add paragraph or heading elements after preformatted text. Every time I push enter it makes a new line with preformatted text. If I try to add an heading or paragraph element it changes the preformatted text to those formats

**Comment by anthonyjb** [comment]
Hi @themoor88 - to add a paragraph after preformatted text hold down the ctrl key (command on Apple) whilst clicking the paragraph tool.

**Comment by themoor88** [comment]
That doesn't work...I tried it on your homepage demo as well.

**Comment by anthonyjb** [comment]
OK I'm using on a documentation project and just tested it on the sites demo page so my guess is perhaps this is an issue specific to one or more OS/browser types/versions. Can you let me know what OS/browser you're using and I'll try to reproduce the issue.

In the meantime if you want a quick work around create a new paragraph with some content in it above the preformatted content block and drag the new paragraph below it - not ideal but a short term option.

**Comment by themoor88** [comment]
Okay thanks for the work around. Here are my details for Chrome and for the type of OS I am using. Thanks for the quick reply.

![image](https://cloud.githubusercontent.com/assets/10791707/15876274/80989800-2cda-11e6-8779-ae12298c4dad.png)

![image](https://cloud.githubusercontent.com/assets/10791707/15876304/a866c5d2-2cda-11e6-83c3-19acd039a753.png)

**Comment by anthonyjb** [comment]
No problem, I'll have access to a mac in the office tomorrow running the same OS and browser so will try to reproduce there (I suspect I'm not detecting the command key on OSX correctly). If I can reproduce I'll flag as a bug and push a fix in the next release (planned early next week).

**Comment by anthonyjb** [comment]
@jonolock91 - hey buddy any chance you can check this for me when you get a mo and let me know if you get the same problem, if so can you take a look at the why CT is failing to register the command key as pressed (or at least confirm that's the cause of this bug)?
