### ISSUE TITLE
"Delete" key on images and videos

### ISSUE THREAD

**Issue by damiansb** [GetmeUK/ContentTools#230]
I've noticed that when you delete an **image** or **video** by pressing the **delete key on keyboard** instead of clicking the trash bin removes the first letter of the next element (like a ``<p>`` or ``<h1>``) alongside the image/video itself.

That behaviour can be seen on the [demo page](http://getcontenttools.com/demo).

I know it's pretty minor, but a fix for that little issue in the future would be nice :)

**Comment by anthonyjb** [comment]
Good spot @damiansb :+1: Will push a fix in the next release (early next week).
