### ISSUE TITLE
enclosing editable content with divs blocks editing

### ISSUE THREAD

**Issue by sbotting** [GetmeUK/ContentTools#231]
Hi, 
I really like ContentTools

I have a question and perhaps maybe an issue

If I have some content like for example:
```
<div data-editable data-name="content">
<p>
Some content and <a href="#">a link</a>
</p>
</div>
```
But if I put some and enclosing div around the content:

```
<div data-editable data-name="content">
<div>
<p>
Some content and <a href="#">a link</a>
</p>
</div>
</div>
```

The content tools editor doesn't seem to let me actually edit the content within the "content" data-name div.

Any suggestions?  Am I doing something wrong or misunderstanding how it works?

Cheers
Simon

**Comment by anthonyjb** [comment]
Hi @sbotting,

So what's happening here is that the div isn't registered as an editable tag and so is converted to a static tag with the editable region. While you can place content around static elements you can't edit them or their contents - in the case the paragraph tag inside.

The simplest solution here is to move the editable region to the inner div, for example:

```
<div>
    <div data-editable data-name="content">
        <p>
            Some content and <a href="#">a link</a>
        </p>
    </div>
    ... If you have more sections you want to make editable within the same outer div
    add another region...
    <div data-editable data-name="other-content">
        <p>
            Some content and <a href="#">a link</a>
        </p>
    </div>
</div>
```

**Comment by sbotting** [comment]
Hi @anthonyjb thanks for you quick reply, 

That definitely helps.

You mention about registering editable tags, is there some resource that you can point me to that shows me how to do that, there are several parts of the page I want to edit that have div tags which enclose other tags (for sytlistic reasons) and it would be good if I could edit the content within those div tags.

Thanks very much for your help.

**Comment by anthonyjb** [comment]
@sbotting no problem the most relevant documentation is here: http://getcontenttools.com/api/content-edit#tag-names

I'm not sure however the approach you mentioned will work with CT simply because regions are the only editable tag type that can support an unstructured collection of editable elements (e.g a div with children as opposed to lists or tables with defined structures). Regions can't be nested within each other and therefore you need to define each such region a separately editable region.

**Comment by sbotting** [comment]
Hi @anthonyjb 

Just to make sure I'm understanding it, if I have some content that was marked as one editable region, like:
```
<div data-editable data-name="main-content">

<h2>Some title</h2>
 <div class="pull-left imagecontainer">      
         <img src="[image-url]" class="img-rounded img-responsive mainimage" alt="[alt]">      
         <span class="caption">Caption Underneath Image</span>  
 </div> 
<p>Large paragraph of content...</p>
... more of the same
</div>
```

And I wanted to edit the content within the span, my best bet would to be change the format so that each logical group of tags was an editable region e.g.in the above case it would become three regions:

```
<div data-editable data-name="header-1">
<h2>Some title</h2>
</div>

 <div class="pull-left imagecontainer" data-editable data-name="image-frame-1">      
         <img src="[image-url]" class="img-rounded img-responsive mainimage" alt="[alt]">      
         <span class="caption">Caption Underneath Image</span>  
 </div> 

<div data-editable data-name="paragraph-1">
<p>Large paragraph of content...</p>
</div>
... more of the same
```

Thanks once again for your time

**Comment by anthonyjb** [comment]
That's correct.

On a related note - the span tag is also not an editable tag by default, typically only block or inline-block elements are encapsulated by the ContentEdit.Element classes (e.g ContentEdit.Text in this case), but you can have inline elements/tags within their content (like spans), so in the example above you should either wrap/replace the span in/with a paragraph tag (e.g a block level element) or let CT know that the span should be handled as a paragraph tag which you can do as follows:

```
<span class="caption" data-ce-tag="p">Caption Underneath Image</span>  
```

No worries on the help :) I'm grateful to devs like yourself investing their time in CT. Its a relatively young library and we're releasing almost weekly so there's not the knowledge base of articles and tutorials that there is with longer established libraries so I'm keen to fellow devs out and it helps me identify improvements and new features.

**Comment by sbotting** [comment]
Hi @anthonyjb 

I've come up with a workaround for my particular case although  I think it isn't really using it in the spirit it was intended.

If I indicate to CT that the div and span tags should be treated like block elements (like p tags for example) using the data-ce-tag="p" attribute in each tag instance,  I can edit their contents so in the above case I can do the following: 

```
<div data-editable data-name="main-content">

<h2>Some title</h2>
 <div class="pull-left imagecontainer" data-ce-tag="p">      
         <img src="[image-url]" class="img-rounded img-responsive mainimage" alt="[alt]">      
         <span  data-ce-tag="p" class="caption">Caption Underneath Image</span> 
 </div> 
<p>Large paragraph of content...</p>
... more of the same
</div>

```

And then the content of the span tag becomes editable, although you lose the ability to edit the tags at the bottom of the page with custom styles etc.

**Comment by anthonyjb** [comment]
Cool :) In the case above you don't need the `data-ce-tag="p"` against the `span` as that's a valid element inside a Paragraph.

**Comment by mattsah** [comment]
Hi @anthonyjb,

Can you provide any insight on how this works and/or is circumvented with ContentFlow?  It's my understanding with ContentFlow that you can have a snippet which creates new flows, and therefore, in which you can insert other snippets.  If one editable area cannot be a child of another (without becoming static) how is this done?  Is the idea that no snippet that provides flows should also provide for editable areas (e.g. anything with a flow should mainly be structural) and all snippets with editable areas are isolated to be inserted in those flows?

**Comment by anthonyjb** [comment]
@mattsah ContentFlow provides a way of laying out page content using predefined snippets of HTML, these snippets can have editable regions & fixtures, and each snippet can be configured using settings to provide flexibility over the snippet's HTML (for example we often have a setting to control whether a block of text is followed by a CTA (call to action) / button).

Snippets can also contain content flows (the can also have editable regions & fixtures at the same time but not within the flow itself). When a content flow is defined within a snippet it will appear as a new flow in the drop-down at the top of the snippet draw, you can then select it and insert snippets of content into that.

There are numerous things we use this dynamic flows approach for, we're currently experimenting with building a form builder using this approach and we frequently use it to build things like image carousels where we want to repeat a very specific section of content (in the case of a carousel we use a snippet with an image fixture and text (caption) fixture to in a snippet that lays out a single slide).

**Comment by mattsah** [comment]
@anthonyjb 

I understand all that.  My question was moreso, if I use ContentFlow to insert a snippet that has a flow in it, but is also editable at a higher level, say just for simplicity I have a two column layout for which I want people to be able to add paragraphs and other things directly to the columns, but also have the option of adding snippets.  So the Two column snippet itself contains:

```
<div class="group split-2">
    <div data-editable data-ct-flow="column">
    </div>
    <div data-editable data-ct-flow="column">
    </div>
</div>
```

Now if I add  that, then add a new snippet in one of the columns I might end up an editable section inside the parent which is editable.  How does ContentTools deal with that?  or doesn't it and the columns cannot be directly editable, i.e. would require someone to add an additional snippet that was editable before being able to edit/add content to it.

**Comment by anthonyjb** [comment]
The example you've provided would allow you to add content editable snippets into the two columns, other than the flows need custom names, such as: column-1 and column-2.

Initially you might want to consider inserting default snippets into both flows so that the user can immediately edit content in them (but that's something for the server side). We often setup default snippets in flows to help with page layout.

In effect (and I think this is what you suspected) ContentTools doesn't know anything about ContentFlow, ContentFlow is responsible for building the page layout, then when you're done you switch to edit mode for ContentTools. ContentTools sees the page generated by ContentFlow in the same way it would see any HTML page.
