### ISSUE TITLE
get data

### ISSUE THREAD

**Issue by jbehrouzi** [GetmeUK/ContentTools#232]
Hi !
how can in get current editor data without save event ?

**Comment by anthonyjb** [comment]
While the editor is in the `editing` state you can get the content for any region like so:

```JavaScript

var regionHTML = editor.regions()['region-name'].html();

```

**Comment by jbehrouzi** [comment]
If i want get that without editing state , what should i do ?

**Comment by anthonyjb** [comment]
Well actually once you `init` the editor you will be able to access the HTML as per my previous comment, the only reason I mentioned `editing` state is you can't trigger the save event unless you're in the editing state.
