### ISSUE TITLE
SHIFT button makes graphical glitches

### ISSUE THREAD

**Issue by a-komarev** [GetmeUK/ContentTools#233]
If you hold down `SHIFT` key and wait for a couple seconds - all regions will be outlined with a blinking border:

![selection_138](https://cloud.githubusercontent.com/assets/1849174/15974411/50a8af6e-2f59-11e6-9c97-aba0157bff81.png)

I found an issue which working in all modern browsers. To reproduce it you need to have more than 1 tab opened in browser window.

There are default hotkeys combinations to switch between tabs: `CTRL + TAB` for the next tab and `CTRL + SHIFT + TAB` for previous one.

1. You should be on a tab with ContentEditor located on the page (editor state doesn't matter).
2. Press `CTRL + SHIFT + TAB` to switch to another one tab.
3. Press `CTRL + TAB` to return back.
4. Now you can see region outline borders are blinking all the time, until you press SHIFT button one more time.

I think there is a browsers behavior problem. It looks like `keyup` event isn't sending to the tab which was active before switching. Because switch to previous tab combination has `SHIFT` key - editor think you are just holding it even after switching back.

**Comment by anthonyjb** [comment]
I'll look to get a fix out in the next release but sounds like I need to check that only the shift key is down before starting the region outline flash. Thanks for the detailed description :+1:

**Comment by a-komarev** [comment]
Can you provide use case of this feature, please? I just found it accidentally after tab switching issue :}

**Comment by anthonyjb** [comment]
@a-komarev it allows you to visually highlight the editable regions on a page, so if you want to know what can be edited (without starting the editor even) you just hold down shift.

**Comment by a-komarev** [comment]
@anthonyjb Is there is a way to mark regions this way programmatically? Because I'm not sure at least 1% of users will find this feature themselves.

**Comment by anthonyjb** [comment]
@a-komarev sure call `editor.hightlightRegions(true)` send `false` to disable.

The feature/purpose is documented on the demo page second paragraph - *Editable regions*. In a lot of cases (like the demo page) I guess it's not that useful because almost everything editable is obvious, we've tended to find if useful on pages where only small sections of content are editable, like a product listing page where only a delivery notice top right can be edited in page (that sort of thing).

**Comment by anthonyjb** [comment]
This is now fixed in the develop branch.

**Comment by a-komarev** [comment]
Thanks, working like a charm!
