### ISSUE TITLE
Adding Source or Caption after Image/Media

### ISSUE THREAD

**Issue by themoor88** [GetmeUK/ContentTools#236]
Hey there,

I am trying to simultaneously add a paragraph tag after I upload an image or video. I have customized my own uploader and dialog. I am getting along the lines of something like this in my modal after save
```

tool = new ContentTools.ToolUI(ContentTools.ToolShelf.fetch('paragraph'))
region = new ContentEdit.Region(document.querySelectorAll('.editable')[0])
element = region.children[region.children.length - 1]
tool.apply(element)
```
But I need to figure out a way to attach the paragraph or caption right after the image, not only after the last element which might or might not be an image.

Also when I push save it doesn't actually save the paragraph element.

Your help is greatly appreciated.

Cheers,
themoor88

**Comment by anthonyjb** [comment]
Hi @themoor88,

When/where is your code above being applied to trigger after an image upload? Is it within your `ImageUploader` code?

**Comment by themoor88** [comment]
No, I have a custom image uploader, image tool and image dialog. I am calling this specific code in the `custom-image-tool` in the `apply` class method.

**Comment by anthonyjb** [comment]
In that case you'll have access to the newly created image element I assume, so instead of finding the last element in the region per your code sample if you send the new image element to the paragraph tool the new paragraph will be created after the new image.

**Comment by themoor88** [comment]
Oh right! That was a silly question. Thanks for your help.
