### ISSUE TITLE
Demo code/container for plugins

### ISSUE THREAD

**Issue by wotta** [GetmeUK/ContentTools#237]
Hello @anthonyjb,

Would it be an option to create a demo plugin that display's all hooks that the system has ?
Also shows the most common ways to extend ?

I am thinking about creating an template plugin.
It should be able to load templates from ajax or files at certain directory's, Also should have a button on the menu bar.
or maybe on the bottom bar.

Best regards,
Wouter.

**Comment by anthonyjb** [comment]
Hi @concept-core,

This has some cross-over with issue #47. I agree an example/demo plugin for CT would be useful inclusion (similar to the ImageUploader example code).

This is however quite a big task to undertake as there's currently no set workflow for plugins within the CT user interface (so we'd need to come up with one) and no established approach for creating a plugin (which hopefully a demo would provide at least in part).

I'm happy to open up that discussion here (moving it from #47) and it would be great if anyone who is developing plugins for CT at the moment could chime in with their thoughts/wishes on the matter.
