### ISSUE TITLE
How to set heading — h2 and subheading — h3?

### ISSUE THREAD

**Issue by SimBioT1954** [GetmeUK/ContentTools#239]
@anthonyjb How to set default heading to `<h2>` and subheading to `<h3>`?

**Comment by anthonyjb** [comment]
Hi @SimBioT1954,

This is something I typically do on sites also, it can be achieved as follows:

```JavaScript
ContentTools.Tools.Heading.tagName = 'h2';
ContentTools.Tools.Subheading.tagName = 'h3';
```

**Comment by SimBioT1954** [comment]
Thanks! @anthonyjb
