### ISSUE TITLE
Where do I replace the image uploader?

### ISSUE THREAD

**Issue by QuantumRevenger** [GetmeUK/ContentTools#241]
I have a custom HTML 5 image uploader that I would like to use, but the documentation of the code is non-existent, which code should I replace to either fully remove the current image uploader, or replace with my own.

Also, is it possible to disable certain features and/or call them from a function. I would like to better integrate the controls around my theme?

Many thanks in advance.

**Comment by QuantumRevenger** [comment]
Hi @anthonyjb,

Thank you ever so much for pointing me in the right direction, I was under the impression there was no documentation as I was looking for it in the code (My IDE uses @jsdoc to determine descriptions and IntelliSense.)

It turns out that this project is far more capable than I initially thought, it really is amazing to have such control for personalising around your own projects. - Mine to simplify editing content for my clients who lack technical expertise.

Do you think that the code will ever be updated to comply with "http://usejsdoc.org/"? If I ever have any spare time, I may contribute to the project by gradually adding in jsdoc (as I learn about the features)

**Comment by anthonyjb** [comment]
@QuantumRevenger I did review several such tools before launching the project, I hadn't if I'm honest considered that people would hook into a specific documentation format such as the one you mention in their IDE and that is a good argument for using using such a format.

The reason I didn't select a documentation tool/format at the time was that I simply felt documenting the tool by hand using CT would give me more control over the end result. I actually like writing documentation in a rich environment and dislike the use of markdown or other such verbose formats in code comments as I feel they can obscure the code making it more difficult to read. 

That's not to say I don't comment my code, I do, but I like the presentation of the comments to aid not hinder the flow of code. For example some of the snippets presented here http://usejsdoc.org/about-namepaths.html (particularly the last one) - seem to make the code less readable to my eyes.

So I'm on the fence, I happy to discuss further, but I think you make a valid point re. IDEs that integrate with such tools/formats.

**Comment by anthonyjb** [comment]
Having looked through some of the examples in more detail I have to say for the most part http://usejsdoc.org/ isn't overly verbose in most cases (I picked a bad example in my previous comment).

**Comment by QuantumRevenger** [comment]
I completely agree with you, I am a huge fan of ensuring my code flows and comments are presented well. This is why I took to PHPStorm as my IDE of choice, it is really worth the free trial in my opinion.

Started out using notepad, then notepad++, vs code, and then dipped into a free trial of PHPStorm thinking I would never actually buy it, never went back afterwards.

I often hide the @jsdoc sections by collapsing them.

However, I respect the path you choose for the project and whether supporting http://usejsdoc.org/ or not is ultimately your decision.
