### ISSUE TITLE
target="" when no target specified in a link

### ISSUE THREAD

**Issue by sbotting** [GetmeUK/ContentTools#243]
Hi I'm not sure if this is the desired behavior, but when you create a link and don't specify it as having a target, the source is written out as

`<a href="mylinkurl" target="">My Link Target</a>
`
Not sure if this is the desired behavior or not.

But I think personally it would be better if the target attribute were omitted altogether.

Once again thanks for putting time into the project

**Comment by anthonyjb** [comment]
Thanks for spotting this, that's not the desired behaviour - will fix in the next release.

**Comment by anthonyjb** [comment]
This is now fixed in develop.

**Comment by sbotting** [comment]
brilliant, thanks very much
