### ISSUE TITLE
Add some features to editor

### ISSUE THREAD

**Issue by stepan-perlov** [GetmeUK/ContentTools#244]
I wanna add some features to editor:

1. Multiple editor instance
2. Configurable toolbar
3. Configurable attach / not attach ignition button (I know trick with display: none, but this is dirty)

Do you have something against?
If not, any suggestions?

**Comment by anthonyjb** [comment]
Hi @stepan-perlov,

1 - Multiple editors aren't supported by CT, the EditorApp class is a singleton and much of the related code (UI, tools, etc.) relies on this. It would of course be possible to create multiple toolboxes. If you provide some information on what you're attempting to do I will try to help further.
2 - You can configure the tools within the toolbox like so:

```JavaScript
var editor = ContentTools.EditorApp.get();

// Only show the undo, redo and remove tools
editor.toolbox().tools([['undo', 'redo', 'remove']])
```

3 - If you want to build your own custom ignition you can initialize the editor without creating the ignition component using the `withIgnition` option, eg:

```JavaScript
var editor = ContentTools.EditorApp.get();
editor.init('[data-editable], [data-fixture]', 'data-name', null, withIgnition=false);
```

*This option is new to [release 1.2.7](https://github.com/GetmeUK/ContentTools/releases/tag/1.2.7)*

You can then create your own ignition component and that calls:

- `editor.start()` - Start editing
- `editor.stop(false)` - Stop editing and cancel changes
- `editor.stop(true)` - Stop editing and save changes

**Comment by stepan-perlov** [comment]
Hi @anthonyjb 

1 - On screen I have form for creating new article and list of article.
When I click add button, I want create editor instance.
When I click edit article, I want create editor instance.
All items can be in edit mode together.

I want change singleton nature of CT.

2 - I want to use custom template.

**Comment by anthonyjb** [comment]
Hi @stepan-perlov,

1 - There some discussion on changing the singleton nature of CT here: https://github.com/GetmeUK/ContentTools/issues/99 The reality is this isn't a short term goal for us. Based on your description however I'm not sure you need separate editor instances, can't you just re-initialize the editor each time sending the selector for the content you want to make editable? (Apologies in advance if I'm not fully understanding what you're trying to achieve).

2 - CT doesn't use templates to generate the HTML for UI components, everything is build using JS via the DOM, so whilst you can modify the CSS for the toolbox as much as you want there's template to update. However you can replace the existing toolbox with your own component, either using the CT component model or totally independent code. The tools are available independent of the toolbox and so can be called from any code, e.g:

```JavaScript
var boldTool = ContentTools.ToolShelf.fetch('bold');
var element = ContentEdit.Root.get().focused();
var selection = null;
if (element.selection) {
    selection = element.selection();
}
boldTool.apply(element, selection, function (applied) { // Logic to execute once tool is applied  } );
```
My advice would be to read through the code for the toolbox itself initially: https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/toolbox.coffee, and then decided on how you want to implement your custom toolbox. It's possible to completely replace any or all of the UI for CT, as an example this Wordpress editor is based on CT but you'd hardly recognize it from the UI https://pagebuildersandwich.com/

**Comment by stepan-perlov** [comment]
Ok, thanks for feedback.
Going to #99 for point 1
