### ISSUE TITLE
What should be php response when clicked on insert image

### ISSUE THREAD

**Issue by aniket27** [GetmeUK/ContentTools#249]
I'm unable to decide what should be json response when i will click on insert image button, one more thing i want ! i want to remove crop & rotate button  from the image upload popup how can i achieve this?

**Comment by anthonyjb** [comment]
Per the [Handling image uploads](http://getcontenttools.com/tutorials/handling-image-uploads) tutorial you should return at least a URL and the dimensions/size of the image, for example:

```JSON
{
    "url": "/foo.jpg",
    "size": [600, 400]
}
```

The response from your PHP script must be in JSON format.

To remove the image crop and rotate buttons I recommend you simply hide them with CSS, e.g:

```CSS
.ct-control--rotate-ccw,
.ct-control--rotate-ccw,
.ct-control--crop {
    display: none;
}
```

--- 

**These questions don't belong on the issue tracker,** they should be posted to [StackOverflow](http://stackoverflow.com/), jsut mention ContentTools in your question.
