### ISSUE TITLE
How to change Auto save url into another url when clicked on save

### ISSUE THREAD

**Issue by aniket27** [GetmeUK/ContentTools#252]
I have created two php file one for updating content & one more posting that content finally & removing all session variable, but according to plugin

```
   xhr = new XMLHttpRequest();
    xhr.addEventListener('readystatechange', onStateChange);
    xhr.open('POST', '/x/save-page');
    xhr.send(payload);
```
Auto save function will run every 30 second & post the data in save-page.php

is there any function which will make the post data to go to different url !
I mean if i click on save button then i want to post the data on different url

**Comment by anthonyjb** [comment]
Thank very much for using CT. Unfortunately, this request is not considered to be an issue or idea and therefore has been rejected. Please ask your CT related questions on [StackOverflow](stackoverflow.com) or consult the documentation.
