### ISSUE TITLE
User authentication?

### ISSUE THREAD

**Issue by meghart** [GetmeUK/ContentTools#26]
I love this, but I don't want my site content to be openly editable by anyone. Is there a way to add an admin user log in?

**Comment by anthonyjb** [comment]
Hi @meghart, glad you like the editor :)

To clarify - ContentTools is not a CMS - it's a front-end tool that provides a more natural editing environment for HTML pages than traditional rich text boxes. You still need a CMS behind it. 

The (Saving Strategies)[http://getcontenttools.com/tutorials/saving-strategies] tutorial is intended to help those looking to integrate ContentTools into their CMS understand how the output of the editor can be stored and only briefly touches on the subject of user authentication.

I am working on an article currently (which I hope to publish early next week) which will look at how to integrate ContentTools into the workflow of your CMS, in particular the UI, and this will cover the basics of user authentication.

In the mean time I can tell you that I've integrated ContentTools into a number of projects internally now all of which use existing CMS applications. In these cases I use cookies to determine if the editor should be shown when a user is browsing the front-end of the website (e.g is the `administrator` cookie set). Of course the server-side view that receives saved changes must still validate the administrator's credentials  before committing any changes.

I hope that helps better explain the role of ContentTools, I've taken to tweeting when I publish a new tutorial but I'll also try to remember to update this question at the same time.

**Comment by Pilskalns** [comment]
On kind a same theme - **is there any known open source CMS who use ContentTools?** Would love to try out for new projects.

If there is no one, and if I had enough time in evenings, I would love start new one.

**Comment by anthonyjb** [comment]
As it stands I know that @guillaumepiot is working on an open source Django based CMS that use's the editor and I'm working with him also on a WordPress integration. I've spoken to someone looking at integrating the editor with Laravel - but nothing more concrete than that to date.

**Comment by anthonyjb** [comment]
Also this video maybe of interest as it shows ContentTools integrated into a CMS https://youtu.be/Vh3Fd91pVqQ

**Comment by bfintal** [comment]
I think this should be closed since this is outside the scope of content tools
