### ISSUE TITLE
data-tooltip conflicts with semantic-ui

### ISSUE THREAD

**Issue by brunjick** [GetmeUK/ContentTools#260]
data-tooltip css attribute on toolbox widget conflicts with new semantic-ui update and buttons doesn't appear
![avtorebi com 2016-06-30 13-32-23](https://cloud.githubusercontent.com/assets/6980903/16483806/19ac53d0-3ec7-11e6-8d6c-fd0959c38fba.jpg)

**Comment by anthonyjb** [comment]
I've namespaced the tool tips to used `data-ct-tooltip` now so hopefeully that resolves the issue.
