### ISSUE TITLE
Unexpected duplication of the contents of a new bullet list

### ISSUE THREAD

**Issue by etlel** [GetmeUK/ContentTools#261]
Reproduction of this problem on the demo page:

1. click on the middle of the first paragraph and press enter (for instance, after ";")
2. click on the bullet list tool to make this new paragraph a list.
3. click in the middle of the new paragraph and press enter to create a second bullet
4. repeat step 3 to do new bullets from the last one
5. save

The first bullet will contain what expected + the contents of all the following bullets, etc.

**Comment by anthonyjb** [comment]
Hey @etlel - thanks for reporting this I've found the cause of the issue it's because `taint` isn't being called in the return key handler for list items. Will fix now should have fix in place in the next hour.

**Comment by etlel** [comment]
Hi Anthony, the same thing is still happening with the numbers list :)

**Comment by anthonyjb** [comment]
I can't reproduce with the numbers list using the list of actions you provided - number or bullet isn't a different element class so shouldn't matter which list item - are you using the same steps to reproduce?

**Comment by etlel** [comment]
I can't reproduce it anymore. Caching problem maybe? Looks alright !

**Comment by anthonyjb** [comment]
Good news :+1:
