### ISSUE TITLE
Making text bold in a preformatted element, moves the cursor to another location in the element.

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#262]
How to replicate in the sandbox:

1. Create a preformatted element containing a paragraph,
2. Highlight a word somewhere in the middle of the element,
3. Click on the bold tool, the word will unhighlight and the cursor will move to somewhere near the start of the string.

**Comment by anthonyjb** [comment]
Confirmed. Doesn't happen if you use the keyboard short-cut so must be either in the CT bold tool or potentially the HTMLString library - the same issue appears to occur for links and italic text.

**Comment by anthonyjb** [comment]
OK this is now fixed - will go out in the next release (1.2.10) for now it's against the master.

**Comment by bfintal** [comment]
If you think about it, should strong, italic, and headings be allowed inside preformatted text? The `pre` spec doesn't say anything about restrictions though.

**Comment by anthonyjb** [comment]
You can't add headings inside `PreText` elements using CT tools (though you can always add it through the HTML source), but as for bold and italic I don't see any reason to disallow them (though it would be easy to). Syntax highlighters wrap different elements within `pre` tags to style them in a similar way (though I don't imagine they use `b` or `i` much, most likely `span` tags with classes).

**Comment by bfintal** [comment]
Oh yeah nevermind. Because syntax highlighters add `span` tags :)

**Comment by bfintal** [comment]
Thanks for the fix! 👍
