### ISSUE TITLE
Link tool: support for selecting existing pages

### ISSUE THREAD

**Issue by snimavat** [GetmeUK/ContentTools#264]
It would be great if contenttool itself provided a way/api so that link tool can be used to provide list of exieting pages (some thing like select2js dropdowns, where user start typing and suggestions comes up)
And user can link existing page from the system.

But i guess this would be out of the scope of the contenttools. So what would be right approch to extend/implement this functionality ?

**Comment by anthonyjb** [comment]
Hi @snimavat,

I guess the question here is how to hook an autocomplete tool, like [Awesomplete](https://leaverou.github.io/awesomplete/) into the link dialog's select field. Using that library as an example here's a really simple (if slightly ugly way to do this).

```JavaScript
// Patch the behaviour of the link dialog
var _linkDialogMount = ContentTools.LinkDialog.prototype.mount;
ContentTools.LinkDialog.prototype.mount = function() {
    // Call original behaviour
    _linkDialogMount.apply(this);

    // Add the auto-complete to the link input (we provide a static list but most likely you'd
    // have the auto-complete call the server for a list).
    new Awesomplete(
        this._domInput, {
        list: ['/about-us', '/demo', '/getting-started']
    });
}
```

If you try this out using a Awesomplete you'll also might also need to set the font size in the list items (I do in the sandbox demo):

```CSS
div.awesomplete > ul > li {
    font-size: 15px;
}
```

**Comment by snimavat** [comment]
Thanks @anthonyjb for showing me the road, i will play with it now.
