### ISSUE TITLE
List within a list

### ISSUE THREAD

**Issue by borntodesign** [GetmeUK/ContentTools#267]
Example:

* List
  * List inner
* Really tricky to get back here

When we are putting content into the system the list feature seems really buggy. Pressing tab to indent and start another list within that list works well, however trying to get back to the main list does not work very well...

**Comment by anthonyjb** [comment]
Hi @borntodesign can you be more descriptive about the issue you're having, to get to the previous list you should just be able to move the caret left/right or up/down (e.g using the arrow keys to navigate back to the parent list at either end of the current list item).

If this isn't the case for you can you let me know what browser you're using in case it's a browser specific issue.

**Comment by borntodesign** [comment]
I am using the latest version of chrome, I have tested it from a clean slate however I know that the problem came from pasting a block of content in from a word document (sigh). We run a magazine company so all articles are first done in word.

**Comment by anthonyjb** [comment]
Hi @borntodesign - I'm using Chrome also and can't repeat the issue just creating a list from scratch so it sounds like it might be a problem from pasting in the content from word, is there any chance you can send me an example word doc containing a snippet of content that was pasted in and caused the issue so I can repeat the problem and get a fix in place?

We are looking to add better support for pasting in HTML and content from other applications, at the moment we convert everything into basic text structures but seems like we may be allowing in special characters or something that's causing a glitch.

**Comment by cgriffin4** [comment]
Creating a nested `ol` is fine but editing one results in collapsing the nested `ol`.

**Comment by anthonyjb** [comment]
@cgriffin4 - I don't think this is the same issue as I can't repeat this with unordered list, but I can reproduce the error you have highlighted and will flag an error for that now.

**Comment by cgriffin4** [comment]
@anthonyjb Apologies, you are correct. I commented too early and after a bit more testing realized it was not related. Thank you for raising the error.

**Comment by anthonyjb** [comment]
@cgriffin4 no problem - thank you for taking the time to notify me about the issue :)

**Comment by cgriffin4** [comment]
@anthonyjb no problem - thank you for this project. I've had difficulties extending it but everything it does is exactly what I was looking for in a WSIWYG editor. Excellent work on UI/UX!
