### ISSUE TITLE
using innerHTML in _EditorApp::save

### ISSUE THREAD

**Issue by revyh** [GetmeUK/ContentTools#270]
Hi!

I need to add to ContentTools the ability to creating carousels. For now, I have `CarouselTool` and `CarouselElement`. `mount` method of `CarouselElement` actually initializes carousel. I want that carousel remains working and simply becomes non-editable when `CarouselElement` is unmounted. But when I save changes, [innerHTML in _EditorApp :: save](https://github.com/GetmeUK/ContentTools/blob/cba9e59d37a62554aca0927bc9d2f1160cc0631b/src/scripts/editor.coffee#L535) removes all auxiliary containers and event handlers, created by the carousel. So, after saving, instead of working carousel I get a container with slides. I can workaround this and reinit carousel in `saved` event handler, but it causes lags and flickerings. I can't just replace innerHTML with something else, because other tools and editor logic based on it.

Advices?

**Comment by anthonyjb** [comment]
Can you post your code for the carousel element here or in a gist so I can take a look and see if I can help?

**Comment by revyh** [comment]
Thanks for the quick response!
Simplified code should look like this:

```coffeescript
class CarouselElement extends ContentEdit.ElementCollection
  constructor: (attributes) ->
    super('div', attributes)

  cssTypeName: () -> 'carousel'
  type: () -> 'Carousel'
  typeName: () -> 'Carousel'

  mount: () ->
    super()

    @addCSSClass('slider')

    @_sliderInstance = new BM.Carousel(@domElement())

    @_domElement = @_sliderInstance.holder[0]

  unmount: () ->
    for child in @children
      child.unmount()
    ContentEdit.Root.get().trigger('unmount', this)

class BM.Carousel
  constructor: (root) ->
    @root = $(root)
    @slides = @root.children()
    @holder = @root.wrap('<div class="slider-holder" />').parent()
    @info = $('<div class="slider-info" />')
    @slidesCount = $('<div class="slider-info_count" />').appendTo(@info)
    @slidesTitle = $('<div class="slider-info_title" />').appendTo(@info)
    @fullscreenButton = $('<button class="slider-info_fullscreen" data-current="0" />').appendTo(@info)
    @holder.append(@info)

    @root.owlCarousel
      margin: 0
      nav: true
      dots: false
      items: 1
      smartSpeed: 400
```

When `CarouselElement` is mounted I have a DOM like this:
```html
<div class="slider-holder">
	<div class="slider">
		<!-- slides -->
	</div>
	<div class="slider-info">
		<div class="slider-info_count"></div>
		<div class="slider-info_title"></div>
		<a class="slider-info_fullscreen" data-current="0"></a>
	</div>
</div>
```

And after save like this:
```html
<div class="slider">
	<!-- slides -->
</div>
```

**Comment by anthonyjb** [comment]
OK I can understand what you're trying to achieve now.

Saving causes CT to to request a HTML version of the CarouselElement via the `html()` method, remove the existing ContentEdit element using `unmount()` (in this case BM.Carousel) and then replace it with with the output of `html()`. Further in the editor `save()` method the HTML is not replaced per element but rather all elements are unmounted and then the HTML for the region is inserted into the region.

You could conceivable change the save method to replace the regions HTML piecemeal (e.g per element) and to check the type of element before deciding whether to replace the element with the `html()` output or simply store it for the save operation but leave the element in place - but I don't think this would be the ideal solution.

I'd recommend taking the approach that videos do, when you manage a video it's converted to a `div` that you can position and size, when you save out the video is converted to an `iframe` (if it's youtube or vimeo at least). The JavaScript loaded by the `iframe` activates the video.

Using this approach I recommend that you update your carousel code to detect for changes in the DOM or bind to the editor `save/saved` event and then reinitialise the carousel at that point (which I think was the conclusion you were coming to). There maybe a small flicker while the JS kicks in, as there is with videos, but so long as you use CSS to keep the elements size the same this shouldn't be substantial.

Having said all of this @bfintal has actually created a manageable carousel for his [PageBuilderSandwich](https://pagebuildersandwich.com/) project so if you have any thoughts/advice Benjamin I'm sure they'd be appreciated.

**Comment by revyh** [comment]
@anthonyjb thanks. It seems that the "reinitialize on `save`" approach more preferable for my current project.
@bfintal definitely, I would be very appreciated if you share your experience with carousels and CT.
