### ISSUE TITLE
why can not insert audio?

### ISSUE THREAD

**Issue by haozhouxu** [GetmeUK/ContentTools#271]
why can not insert audio?i try to insert mp3 into video,but can not display perfect?what should i do ? thanks

**Comment by anthonyjb** [comment]
There's no audio element currently in ContentEdit. One needs creating to support inserting audio - if you want to add a request for such an element then please post it on the ContentEdit issue tracker and I'll happy to add it to the enhancements list. https://github.com/GetmeUK/ContentEdit/issues
