### ISSUE TITLE
Add the tag p automatically after add the table

### ISSUE THREAD

**Issue by megamuf** [GetmeUK/ContentTools#272]
After adding table need to automatically add tag p after table, 
how it can be implemented?
Thank in advance.

**Comment by anthonyjb** [comment]
Does it matter if the table is in the middle of some content or is this only when the table is at the end?

**Comment by megamuf** [comment]
Thank you for your answer,
is this only when the table is at the end?

**Comment by anthonyjb** [comment]
OK so there are a couple of approaches you could take, I'd recommend updating the a Table tool to do this personally, I'll show how to do this in CoffeeScript, if you need it in JS let me know:

```CoffeeScript
    class ContentTools.Tools.TableP extends ContentTools.Tools.Table

        # Override existing table tool
        ContentTools.ToolShelf.stow(@, 'table')

        @apply: (element, selection, callback) ->

            _callback = (added) =>

                console.log(element)

                # # Check if we need to add a paragraph
                if added

                    # Find the last child in the collection
                    siblings = element.parent().children
                    lastChild = siblings[siblings.length - 1]

                    # If it's a table...
                    if lastChild.type() == 'Table'

                        # ...add a paragraph
                        p = new ContentEdit.Text('p', {}, '')
                        element.parent().attach(p)
                        p.focus()

                # Perform the standard callback
                callback(added)

            super(element, selection, _callback)
```

**Comment by megamuf** [comment]
My experience with CoffieScript is practically null, so could you please provide JS solution?.

**Comment by anthonyjb** [comment]
Sure, hope this helps:

// Some stuff required when extending a CoffeeScript class
var __hasProp = Object.prototype.hasOwnProperty, __extends = function(child, parent) {
  for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; }
  function ctor() { this.constructor = child; }
  ctor.prototype = parent.prototype;
  child.prototype = new ctor;
  child.__super__ = parent.prototype;
  return child;
}, __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

// Our new tool in Javascript
ContentTools.Tools.TableP = (function() {

  // Inherit from the existing table tool
  __extends(TableP, ContentTools.Tools.Table);
  
  // Constructor
  function TableP() {
    TableP.__super__.constructor.apply(this, arguments);
  }

  // Override existing table tool in the default tools
  ContentTools.ToolShelf.stow(TableP, 'table');
  
  // Customize the apply method for the tool
  TableP.apply = function(element, selection, callback) {
    
    // We wrap the passed callback in out own version that adds the additional
    // paragraph element if needed.
    var _callback;
    _callback = __bind(function(added) {
      var lastChild, p, siblings;

      // Check the table was added
      if (added) {
        // If the table was added is it the last child...
        siblings = element.parent().children;
        lastChild = siblings[siblings.length - 1];
        if (lastChild.type() === 'Table') {

          // ...if so add a paragraph at the end of the parent collection 
          p = new ContentEdit.Text('p', {}, '');
          element.parent().attach(p);
          p.focus();
        }
      }

      // Perform the standard callback
      return callback(added);
    }, this);

    // Perform the standard apply method with out wrapped `_callback` function
    return TableP.__super__.apply.call(this, element, selection, _callback);
  };
  return TableP;
})();

**Comment by megamuf** [comment]
Thanks for excellent answer!!!

**Comment by megamuf** [comment]
Hello,
I also need to do it this with pictures and videos,
can help me with this?
Thanks in advance.

**Comment by anthonyjb** [comment]
Hi @megamuf, 

In line with the **Where to post... How do I?** guide on in the project readme file please ask this question on StackOverflow for the benefit of everyone - I check SO daily and will happily post an answer there, but it does belong there not here.

General questions are better on SO as they are just easier for people with the same or similar questions to find in the future.

Thank you in advance.

**Comment by megamuf** [comment]
http://stackoverflow.com/questions/39074758/content-tools-add-the-tag-p-automatically-after-add-the-image-and-video

Question on stackoverflow

**Comment by anthonyjb** [comment]
Hi @megamuf - I'll try to get an answer posted for you today.

**Comment by anthonyjb** [comment]
@megamuf I've posted a much neater solution for you on SO now :)

**Comment by megamuf** [comment]
Thank you!!!

**Comment by megamuf** [comment]
Hello @anthonyjb,

I'm trying to add a image, but before that i delete the text of the default paragraph, but when i'm inserting the image it gives an error that afects the further functionalities. What i understand of it is that ContentTools deletes the paragraphs without text, and this gives the error. Could you please give me a solution if possible? Thanks

### Code
                 function _followWithP(ev) {

                            var element = ev.detail().element;
                            // Find the top level element 
                           // Here is where the code has error
                            if (element.parent().type() !== 'Region') {
                                element = element.closest(function (node) {
                                    return node.parent().type() === 'Region';
                                });
                            }

                            // Find the newely insert element
                            var newElement = element.nextSibling();

                            // Check if this is the last item in the region
                            var siblings = newElement.parent().children;
                            if (newElement === siblings[siblings.length - 1]) {
                                // This is the last child so apply add a paragraph
                                var p = new ContentEdit.Text('p', {}, 'Description');
                                newElement.parent().attach(p);
                                p.focus();
                            }
                        }

                        // Modify the applied behaviour of the image, table and video tools to use
                        // `_followWithP`.
                        if (this._toolUIs['image'] !== undefined) {
                            this._toolUIs['image'].addEventListener('applied', _followWithP);
                        }
                        if (this._toolUIs['table'] !== undefined) {
                            this._toolUIs['table'].addEventListener('applied', _followWithP);
                        }
                        if (this._toolUIs['video'] !== undefined) {
                            this._toolUIs['video'].addEventListener('applied', _followWithP);
                        }
                    };`

### error
![error](https://user-images.githubusercontent.com/13167613/30162078-30e6d9bc-93cb-11e7-886b-5bc60ba290b5.png)

**Comment by megamuf** [comment]
@anthonyjb,
"Problem is that if there is only 1 empty <p> tag the elemento has its _parent property null aswell as the ­­­_domElement property"
