### ISSUE TITLE
How to get all regions when saving

### ISSUE THREAD

**Issue by snimavat** [GetmeUK/ContentTools#273]
So, when  `editor.addEventListener('saved', function (ev) {}` is fired, `ev.detail().regions` returns just updated regions. However, as we are saving to a database string type field which holds all regions in a single columns, i would like to send all regions to server and not just updated one.. so how do i get all regions and not just the one which is updated ?

**Comment by anthonyjb** [comment]
Hi @snimavat,

If you want the HTML from all the regions you can do the following on save instead:

```javascript
var regions = ContentTools.EditorApp.get().regions();
htmlMap = {};
for (var name in regions) {
    htmlMap[name] = regions[name].html();
}
```

**Comment by snimavat** [comment]
Thanks @anthonyjb
