### ISSUE TITLE
It is impossile to add new paragraphs after a preblock within same region

### ISSUE THREAD

**Issue by snimavat** [GetmeUK/ContentTools#274]
So once you have a `<pre>` block as last element in the region, its impossible to add new paragraphs after that, unless i convert the pre to a paragraph, hit enter to create new paragraph, and convert the previos paragraph back to pre

http://screencast.com/t/OtOYdA9NGhQB

**Comment by anthonyjb** [comment]
From the demo page docs: 

> Pre-formatted blocks of text can be converted back to standard text using the paragraph tool, however if you have a pre-formatted section of text and want to add a new paragraph after it you can hold down the ctrl key (command on Apple) whilst clicking the paragraph tool to achieve this.

**Comment by snimavat** [comment]
Oh yes, missed it, Thanks for the quick reply, and sorry for bombarding with issues.

**Comment by anthonyjb** [comment]
Hi @snimavat - not a problem, glad to see your using the library :)

**Comment by snimavat** [comment]
Contenttools is the best thing i found.. way much nicer then the bulky editors. Just love it.
I am doing a simple integration with grails, along with backend to create pages / serve pages / templating etc.

Will put it on mygithub and upate here, just incase anyone can benifit.
