### ISSUE TITLE
is it possible to disable certain tools for specific regions?

### ISSUE THREAD

**Issue by snimavat** [GetmeUK/ContentTools#276]
Lets say, i want to disable table/image and certail tools for some specific regions ?

**Comment by SimBioT1954** [comment]
https://github.com/GetmeUK/ContentTools/issues/173

**Comment by anthonyjb** [comment]
Thanks @SimBioT1954. 

@snimavat as the issue @SimBioT1954 references shows it is possible to configure the tools available by region.
