### ISSUE TITLE
Freely resize images without maintaining aspect ration 

### ISSUE THREAD

**Issue by snimavat** [GetmeUK/ContentTools#277]
Is it possible to configure editor, so it lets me scale the image the way i want (all four side), without forcing the aspect ration ?

**Comment by anthonyjb** [comment]
Hi @snimavat - technically yes but the code is a little untested so...

> I'd recommend implementing this in CoffeeScript but you could use a converter for my code below if need be (e.g http://js2coffee.thomaskalka.de/) 

We need to define a new `FlexibleImage` element class that supports an attribute to determine if the aspect raitio is fixed when resizing, that would be done something like:

```CoffeeScript
class ContentEdit.FlexibleImage extends ContentEdit.Image
    
    # An image element that can be configured with a flexible aspect ratio    
    
    resize: (corner, x, y) ->
        # Resize the element
        unless @isMounted() and @can('resize')
            return
        
        flexible = @hasAttr('data-ce-flexible')
        ContentEdit.Root.get().startResizing(this, corner, x, y, flexible)

# Register `ContentEdit.FlexibleImage` as the tag to associate with images (over Image)
ContentEdit.TagNames.get().register(ContentEdit.FlexibleImage, 'img')
```

To then implement an image with a flexible aspect ratio we just need to set the `data-ce-flexible` attribute against it:

```HTML
<div data-editable="my-region">
    <img src="some-image.svg" width="400" height="400" alt="a flexible image" data-ce-flexible>
</div>
```

**Comment by snimavat** [comment]
Great, i would try it out..

The other issue i am facing is, element.constructor.name is always c, but never 'Image'

Resizing:

```
 imageResizer = (element) ->
    $log.debug element.constructor.name
    return if element.constructor.name != 'Image'
    $log.debug "Image resized", element.constructor.name
    #src = element.attrs("src")
    #$log.debug src

ContentEdit.Root.get().bind 'taint', imageResizer
```

However, it never pass this condition - ``` if element.constructor.name != 'Image'```

**Comment by anthonyjb** [comment]
@snimavat I don't recommend using `constructor.name` it's not safe across browsers (I learned this the hard way). Instead CE provides the `type()` method against elements, so instead I'd recommend you try:

```CoffeeScript
return element.type() != 'Image'
```

**Comment by snimavat** [comment]
Perfect, that works.. i was following cloudinary example, which uses constructor.name

**Comment by anthonyjb** [comment]
Ah I need to update that then (thanks for letting me know :+1: ) - I used to use `constructor.name`, then like I say discovered it's not reliable.

**Comment by anthonyjb** [comment]
Thanks again for highlighting this @snimavat - I've now updated all references to `element.constructor.name` with `.type()` within the documentation.
