### ISSUE TITLE
line break on pressing enter on an empty p tag

### ISSUE THREAD

**Issue by akshaysinha91** [GetmeUK/ContentTools#278]
How can we add line-break when enter key is pressed on an empty p tag.

**Comment by anthonyjb** [comment]
Hi @akshaysinha91 - Please see this issue https://github.com/GetmeUK/ContentTools/issues/150 for information on inserting line-breaks in paragraphs and how to set the default behaviour. 

The setting `PREFER_LINE_BREAKS` setting is also documented here: http://getcontenttools.com/api/content-edit#settings

**Comment by akshaysinha91** [comment]
hi @anthonyjb,

Thanks for your response, I checked this setting, but it's not I was looking for. I also believe shift+Enter should add a <br> rather than Enter.
My issue is when there is an empty p tag(new para), Shift+Enter does not create <br> tag, we have to use the Line-break button on toolbar to add <br> tag but its not intuitive.

**Comment by anthonyjb** [comment]
Hi @akshaysinha91 - OK I understand what you mean now - I think this is actual a bug of sorts, you can see the test responsible here: https://github.com/GetmeUK/ContentEdit/blob/master/src/scripts/text.coffee#L330

This is too aggressive and should allow `br` tags to count as content. I'll push a fix for this later today as a hotfix.

**Comment by anthonyjb** [comment]
Hi @akshaysinha91 - I've pushed a hot fix for this issue now.

**Comment by akshaysinha91** [comment]
Functionality is working now but when we move to the next Paragraph, the <br> tag is getting removed.
In an empty para
1) Press Shift+Enter 2-3 times.
2) Then enter some text.
3) Then Press Enter.
4) It strips the para. <br> tags get removed.

**Comment by anthonyjb** [comment]
The issue of stripping white space from tags has been discussed in some detail before, I'd recommend taking a look at this post: https://github.com/GetmeUK/ContentTools/issues/205 which provides an overview and the SO post it mentions which provides a patch to achieve this: https://stackoverflow.com/questions/36883079/how-to-preserve-multiple-br-when-no-content-before-or-after-with-contenttools/36954440#36954440

Ultimately outside of `pre` tags I'm not keen on text elements preserving white space at either end as this this `<p><br/><br/></p>` or event `<p><br />test</p>` whilst valid is not something I would like to see clients use to implement padding or spacing between elements.
