### ISSUE TITLE
Don't show dialog on canceling edit.

### ISSUE THREAD

**Issue by jumika** [GetmeUK/ContentTools#279]
Hi!

I would like to change the ignition ui with my own.
I've managed to init the editor without the ignition ui with giving false as fourth parameter on init function. I bind an event handler on a cancel button which then calls editor.stop(false).
My problem is that the EditorApp's stop event (and even revert) is triggered regardless of the user's choice in the "Your changes has not been saved..." dialog. I think these should only be triggered when the user choose to really end editing, since if he answers no in this dialog, the editing is not stopped nor the content reverted.
It would be also nice if we could override these dialogs.

**Comment by anthonyjb** [comment]
Take a look at #269. Does this help?

**Comment by jumika** [comment]
Wow, You are blazing fast!
I'll take a look at it tomorrow.
Thank you, and keep up the good work!

**Comment by jumika** [comment]
No wonder that it's working. Thank you again.
Note: There is an at sign in the code referenced. I assume it means "this." like in coffescript.

**Comment by anthonyjb** [comment]
Thanks for letting me know about the @ sign @jumika :+1: - have fixed now.
