### ISSUE TITLE
Simplify developer experience?

### ISSUE THREAD

**Issue by voltagex** [GetmeUK/ContentTools#28]
I saw this post on HN and had similar concerns:
https://news.ycombinator.com/item?id=10309462

>I've got to say, this entire set of tools looks incredibly polished and well designed. The documentation is amazingly thorough, and the getting started tutorials cover exactly what I hoped they'd cover. (I'm looking at building a collaborative, real-time editor for Markdown-like content.)

>Everything was super positive.

>And then I went to browse the code, and it turns out it isn't actually hosted on NPM; it has a weird custom build process that means every file has implicit module dependencies between them, but you can't really tell which; and everything's written in Coffeescript.

>Went from super excited to questioning whether it's something that is going to be more of a hassle to develop and contribute to than it's worth.

>The design decisions of the library itself still seem strong, but the developer experience design decisions will probably mean that it sees nowhere near the adoption it could have seen. If anyone knows of similar libraries I'd be really curious to hear what people have used in the past.

Is there a guide for getting up and running other than `npm install` from the git repo? Specifically what parts depend on what, how things are put together and what can be extended?

**Comment by anthonyjb** [comment]
Thank you for the feedback. Right now all dependencies are included with the package in a folder called '/externals' and the build process concatenates them to the start of the final output file - which 'hands up' isn't ideal and moving towards correct node/npm support is a goal for the very near future.

To provide a very quick overview: ContentTools is a collection of libraries all written in CoffeeScript (this is up for debate https://github.com/GetmeUK/ContentTools/issues/10), the collection includes:

- FSM (https://github.com/GetmeUK/FSM) [no dependencies]
- HTMLString (https://github.com/GetmeUK/HTMLString) [depends on FSM]
- ContentSelect (https://github.com/GetmeUK/ContentSelect) [no dependencies]
- ContentEdit (https://github.com/GetmeUK/ContentEdit) [depends on HTMLString, ContentSelect]
- ContentEdit (https://github.com/GetmeUK/ContentTools) [depends on ContentEdit]

Full reply to original HackerNews question available here: https://news.ycombinator.com/item?id=10310256

**Comment by developit** [comment]
Just wanted to drop a note here mentioning it would be nice to see this migrate to a more standardized npm + (rollup/browserify/webpack/babel/whatever) module architecture.

**Comment by anthonyjb** [comment]
This issue has partially been resolved as ContentTools (and all other related libraries) are now registered on Bower. NPM registration is still planned but the issue has been re-raised specifically in that context: https://github.com/GetmeUK/ContentTools/issues/174
