### ISSUE TITLE
Disable resizing of images

### ISSUE THREAD

**Issue by Yopi** [GetmeUK/ContentTools#281]
In a responsive design it is not necessarily so that you would want to allow the user to resize the images, but rather do it with percentage widths. This ties in with not wanting to set a static width/height on an image when uploading it.

I am not sure if this is perhaps possible today, but if not I think it would be a great feature, and should not be too hard to do? Perhaps it is easy to add it for me, if so I wouldn't mind some pointers where to start.

**Comment by Yopi** [comment]
Haha, it seems like I might have been a bit hasty in creating this issue. Switching the Image prototype in content-edit to creating an img tag instead of a div with background-image solves seemingly what I wanted to accomplish. 

I realise though that this might not be the optimal solution, so I won't close the issue :-).

**Comment by anthonyjb** [comment]
Another approach to this is to use the behaviour flags for the element:

```JavaScript
// Watch for element mount events
ContentEdit.Root.get().bind('mount', function (element) {
    var domElement = element.domElement();

    // Check the element is an `Image` with the `no-resize` attribute
    if (element.type() === 'Image' && element.hasAttr('data-no-resize')) {
        // Disable resizing for that element
        element.can('resize', false);
    }
});
```

You'd then use the `data-no-resize` attribute to flag that an image should not be resizeable:

```HTML
<div data-editable="my-region">
    <img src="/images/my-image.png" alt="My image" width="400" height="300" data-no-resize>
</div>
```

**Comment by Yopi** [comment]
I think that could work for an image that has a static width and height, but I'm not sure -just- disabling resizing on the element will be sufficient for images that need to be full width. Scaling with the browser and so on, since it will still be converted to a div with a background-image, it will not take up any space if it doesn't get a specified height.

**Comment by anthonyjb** [comment]
@Yopi I'm not entirely sure I've correctly understood, do you want the the user be able to resize the image as a percentage? Or do you simply want the image to be a fixed size, based on percentages, but otherwise moveable/draggable.

The reason we don't use `img` as the DOM element when editing images is because as an inline block they don't support child elements including puesdo `:before`/`:after` elements which are used to display the size of the image - if you can do without the size because it's fixed then I agree using the `img` tag is an good approach.

Perhaps if resize is disabled we could have the element use `img` instead of `div` when editing?

**Comment by Yopi** [comment]
Sorry for not explaining it very well. In my use case, I would not want the user to be able to resize the images at all, since that is something which is handled by the layout in general. The images would always be the correct size when uploaded (for the layout), so that they can be scaled and refit as needed when the browser resizes, which is why it is not a good idea to set static values for those properties, even if they would be 'correct' in one resolution. Still should be draggable though. Hopefully that explains it a bit better.

I didn't realise that was why it turned into a `div`, but that makes perfect sense. And if that is the only reason I think it could probably stay an img if it cannot be resized. I wouldn't mind submitting a PR, although I am not entirely sure if it's something that can be fixed within ContentTools or if it needs to be changed in ContentEdit. In my testing I made changes directly in the mount function for `ContentEdit.Image`.

**Comment by anthonyjb** [comment]
@Yopi that makes sense now :) The change if you'd like to submit a PR needs to be made in ContentEdit, and then I can upgrade the version of CE that ContentTools uses to support this fix :)

**Comment by revyh** [comment]
Hi @Yopi! I had the same issue. I solve it with [padding-bottom hack](https://css-tricks.com/snippets/sass/maintain-aspect-ratio-mixin/).

```coffeescript
class ContentEdit.Image extends ContentEdit.Element
  mount: ->
    ...
    # essential part
    # before
    # if @_attributes['width']
    #   style += "width:#{ @_attributes['width'] }px;"
    #
    # if @_attributes['height']
    #   style += "height:#{ @_attributes['height'] }px;"

    # after
    aspectRatio = @_attributes['height'] / @_attributes['width']
    style += "padding-bottom:#{ aspectRatio * 100 }%"
    ...
```
This way you can preserve drop-placement styles.

**Comment by patrikengborg** [comment]
@Yopi Do you mind sharing how you changed the Image prototype to create an image instead of background-image div? I want to rely on percentage widths as well and disable pixel-resizing.
Thanks!

**Comment by Yopi** [comment]
@patrikengborg what I did was just this:
```coffeescript  
ContentEdit.Image::mount = ->
    @_domElement = document.createElement('img')
    classes = ''
    if @a and @a['class']
      classes += ' ' + @a['class']
    if @_attributes['class']
      classes += ' ' + @_attributes['class']
    @_domElement.setAttribute 'class', classes
    @_domElement.setAttribute 'src', @_attributes['src']
    ContentEdit.Image.__super__.mount.call this```

It didn't feel like a clean enough solution to make a PR from, but it works for my use case.

**Comment by patrikengborg** [comment]
Thanks a lot! @Yopi
