### ISSUE TITLE
Cross document bugs?

### ISSUE THREAD

**Issue by mattsah** [GetmeUK/ContentTools#284]
Hello.  First, let me say thank you very much for this tool.  Overall, it's been a really good experience.  That said, I'm trying to develop a very robust WYSIWYG content editing system.  Part of this means that there are additional interfaces from the ContentTools editor.

For this reason, I have attempted to load all CSS/JS into a wrapping document, wherein the document it's actually editing/modifying is in a full width/height iframe beneath.

Overall this was working swimmingly until I finally got to a point where some editable nodes were injected, I synced ContentTools, saw my editable areas pop up, then tried to edit.  While I'm able to type and even use most (perhaps all tools), I can't backspace.  It also seems to insert new elements above, so if hit enter in a paragraph, the new paragraph inserts above the other one.

I poked around the source and noticed there's some hard coded `document` uses in there.  I think this may be related.  Would it be possible to set the document somehow?  I'd try to do this myself, but I'm not very familiar with coffeescript and I'd fear I'd just waste a lot of time going back and fourth on bogus pull requests.  I'm hoping that once this initial functionality is in I can develop some plugins and learn it a bit more.

**Comment by anthonyjb** [comment]
Hi @mattsah,

I'm not entirely sure I can visualise the issue you're getting, an example I could have a look at would be great. 

Regarding the use of the `document` there are a number of places that rely on the document; incase it helps I've detailed them below:

- The biggest use of document is the `createElement` method which is used to generate HTML elements that are inserted into the ContentEdit (CE) editable elements as well as the ContentTools UI.
- Both CE and ContentTools (CT) add event handlers against the document to listen for mouse events when elements/UI widgets are dragged.
- CE also uses `document.body` to add a CSS class to the body element to indicate if an element is being dragged or resized (`ce--dragging`, `ce--resizing`). CT does similar for `ct--no-scroll` and `ct--dragging`).
- ContentTools uses `document` to add a number of document level event listeners (mostly for tracking key modifiers, the delete key, and the visibility of the current page/tab).
- CT uses `document` to report on the scroll position of the page.
- CT mounts the editor itself directly as the last element within the body using `document.body.appendChild`.

I'm not sure which of these approaches/uses would be causing the behaviour you describe, but happy to have a look if you can provide an example :)

**Comment by mattsah** [comment]
Here's a small example:

## Editor page:

Save as whatever you like

```html
<!doctype html>
<html>
	<head>
		<link href="https://rawgit.com/GetmeUK/ContentTools/master/build/content-tools.min.css" rel="stylesheet" />
		<style>
			html,
			body {
				width: 100%;
				height: 100%;
			}
		</style>
	</head>
	<body>
		<iframe id="view" name="view" src="frame.html" style="width:100%; height:100%;"></iframe>
		<script src="https://rawgit.com/GetmeUK/ContentTools/master/build/content-tools.js" type="text/javascript"></script>
		<script src="https://code.jquery.com/jquery-3.1.0.js" integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk=" crossorigin="anonymous"></script>
		<script>
			$(function() {
				var editor = ContentTools.EditorApp.get();

				editor.init($('#view').contents().find('[data-node]').toArray(), 'data-name');
			});
		</script>
	</body>
</html>
```

## Frame Page

**Save this one as `frame.html`**

```html
<!doctype html>
<html>
	<head>
	</head>
	<body>
		<div data-node data-name="node-1">
			<h1>Test</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum labore atque facere mollitia repellat dolores, similique nihil deleniti soluta perspiciatis at totam modi saepe suscipit esse reprehenderit quam! Libero, aperiam.</p>
		</div>
	</body>
</html>
```

Then just open the editor page in the browser.

**Comment by mattsah** [comment]
Just hit edit mode and try to delete some of the paragraph or whatever.  Or go to the end, hit enter and let it make a new one then start typing (the new paragraph will be above the original, not below).  It doesn't have the highlight styles in, but it is "editable."

**Comment by mattsah** [comment]
Just as a note, Chrome won't do anything at all it seems cause of origin (which I'll solve separately), but firefox should load it properly at least.

**Comment by mattsah** [comment]
Running a local server (origin policy limitation is on files) and testing in chrome, the same behavior is shown.

**Comment by anthonyjb** [comment]
Hi @mattsah - so I've set up the demo you sent and can see that basically nothing works. The issue I believe mostly relates relates to the `ContentSelect` library which is not able to report on the current selection within the iframe as it's using `window.getSelection`. This means the selection is always reported as position as a range of `[0, 0]` meaning tools like bold are disabled, and other tools such as the line break, are always added at the start of the elements content (hence when you spawn a new paragraph with the return key it's like you hit return at the start of the paragraph and therefore added it above the current one).

As a quick solution you could patch the ContentSelect library replacing `window.getSelection()` with `gIframe.contentWindow.getSelection()` so long as you assign a value to `gIframe`. Before loading ContentTools (and hence ContentSelect).

I'll also look to update the ContentSelect library next week to allow you to set the window used to get the selection from against the ContentSelect namespace as a setting.

This probably wont solve all the issues your facing however, the library isn't designed to run in an iframe and no thought has been given to this scenario - it could be a bumpy road. One other option to consider (and I don't know how feasible this is for your project), is to run CT in the iframe but patch CT not to mount itself to the `document.body`, but to the `window.parent.document.body` here: https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/editor.coffee#L307. I tried this using a simply JS patch and it appears to be a possible viable option (only slight annoyance I had to load the CSS in both the iframe and parent HTML.

```HTML
<!doctype html>
<html>
    <!-- test.html -->
    <head>
        <link href="https://rawgit.com/GetmeUK/ContentTools/master/build/content-tools.min.css" rel="stylesheet" />
        <style>
            html,
            body {
                width: 100%;
                height: 100%;
            }
        </style>
    </head>
    <body>
        <iframe id="view" name="view" src="frame.html" style="width:100%; height:100%;"></iframe>
    </body>
</html>
```

```HTML
<!doctype html>
<html>
    <!-- frame.html -->
    <head>
        <link href="https://rawgit.com/GetmeUK/ContentTools/master/build/content-tools.min.css" rel="stylesheet" />
    </head>
    <body>
        <div data-node data-name="node-1">
            <h1>Test</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum labore atque facere mollitia repellat dolores, similique nihil deleniti soluta perspiciatis at totam modi saepe suscipit esse reprehenderit quam! Libero, aperiam.</p>
        </div>
    </body>
        <script src="https://rawgit.com/GetmeUK/ContentTools/master/build/content-tools.js" type="text/javascript"></script>
        <script src="https://code.jquery.com/jquery-3.1.0.js" integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk=" crossorigin="anonymous"></script>
        <script>
            $(function() {
                var editorCls = ContentTools.EditorApp.getCls();
                editorCls.prototype.mount = function () {
                    this._domElement = this.constructor.createDiv(['ct-app']);
                    window.parent.document.body.insertBefore(this._domElement, null);
                    this._addDOMEventListeners();

                    console.log(window.parent.document.body);
                }

                var editor = ContentTools.EditorApp.get();
                editor.init('[data-node]', 'data-name');
            });
        </script>
</html>
```

**Comment by mattsah** [comment]
As a first workaround attempt, I did try to insert ContentTools into the iframe document and work with that one.  The CSS is inserted anyhow, and the class names are namespaced enough that I'm not that concerned.  Because the whole thing is WYSIWYG editing, the reason I'm running in an iframe is to avoid conflicts between libraries/css needed for editing and libraries/css needed for the site.

I will actually try that solution and report back.  If it works flawlessly, there may be no need to patch, as I'd consider that a viable workaround if it were documented.

Thank you much.

As you probably saw from my pull requests, some of the crazy stuff I'm doing is probably going to uncover a lot of little bugs.  As I get more accustomed to coffeescript I'll aim to contribute as much as I can and my own patches when I run into bugs.

This was just a bit beyond my capacity at the moment though.

**Comment by mattsah** [comment]
Thanks for the ideas... the below appears to be working without any prototype overload.

```js
var viewpane = document.getElementById('viewpane');

var load = function() {
	setTimeout(function() {
		var contentTools = viewpane.contentWindow.ContentTools;

		if (contentTools == undefined) {
			load();
			return;
		}

		new Inkwell.ModulesDialog({
			data: {
				subdoc: viewpane.contentWindow.document,
				contentTools: contentTools
			}
		});
	}, 50);
};

$('link[data-copy], script[data-copy]').each(function() {
	var subdoc  = viewpane.contentWindow.document;
	var element = subdoc.createElement(this.localName);

	if (element.localName == 'script') {
		element.src = this.src;
	} else {
		element.href = this.href;
		element.rel  = this.rel;
	}

	subdoc.body.appendChild(element);
});

load();
```

I'd tried something like this before, but couldn't get it to budge.  This basically just enables an easy way to copy some CSS/JS into the document I'm editing in the iframe, waits for ContentTools to be available on that window, then injects then creates my Vue object with that one.

From there I'm able to use all the features on the "remote" ContentTools.

**Comment by anthonyjb** [comment]
Yes the only difference is that in the above the CT UI will mount/display in the iframe and not in the parent window. I wasn't sure if that was acceptable for your project soso the prototype override I provided simply makes CT mount the base app element for the editor in the parent document.

**Comment by mattsah** [comment]
I believe it's acceptable given the general use of good namespacing on classes and what not.  That said, I'll keep this in mind if it runs into a problem.

Thanks again.
