### ISSUE TITLE
Listen to save for all PropertiesDialog's

### ISSUE THREAD

**Issue by joelmoss** [GetmeUK/ContentTools#290]
I want to listen for the `save` event on all `PropertiesDialog` instances. How would I do that?

**Comment by anthonyjb** [comment]
Hi @joelmoss, there's a couple of approaches you could take to do this, overwriting the `TagUI._onMouseDown` method is one option but my recommendation would be to patch the `save` method against `ContentTools.PropertiesDialog`:

```JavaScript
// Override the `save` method to also trigger an event against the editor app on save
var superSave = ContentTools.PropertiesDialog.prototype.save;
ContentTools.PropertiesDialog.prototype.save = function () {
    superSave.call(this);
    var ev = this.createEvent('save-props', {dlg: this});
    ContentTools.EditorApp.get().dispatchEvent(ev);
}

// Listen for the `save-props` event against the editor
ContentTools.EditorApp.get().addEventListener('save-props', function(ev) {
    var dlg = ev.detail().dlg;

    ... insert your code for on save here ...
});
```

--

In line with the **Where to post... How do I?** guide on in the project readme file please ask questions of this nature on StackOverflow for the benefit of everyone - I check SO daily and will happily post an answer there, but such questiosn don't belong here (historically they did and I apologise for any confusion).

You can also post a link to your SO question in the gitter feed and so I can find and answer it quicker (I don't have an SO tag for ContentTools yet but hopefully will soon).

General questions are better on SO as they are just easier for people with the same or similar questions to find in the future.

Thank you in advance.

**Comment by joelmoss** [comment]
Ok, so I was expecting [this](https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/dialogs/properties.coffee#L271) to be an event that I can listen for. Wouldn't that be a better way?

thx

**Comment by anthonyjb** [comment]
@joelmoss you can listen for that event but it's triggered against the `ContentTools.PropertiesDialog` instance, e.g you can do:

```JavaScript
var dlg = ContentTools.PropertiesDialog(...);
var dlg.addEventListener('save', function (ev) {
... do something here...
});
```

But a new dialog is created each time you click on a tag in the inspector so to do this you'd need to override the behaviour of the `TagUI._onMouseDown` method - which is a lot less clean. This patch means `save-props` events are triggered against the `EditorApp` (which is globally available) for any property dialog instance.

**Comment by joelmoss** [comment]
That's what I thought, but was half expecting some global way to listen on events for all instances. No worries. Thanks so much, and great work on an amazing project
