### ISSUE TITLE
How to add element text(textarea or textbox)in dialogui

### ISSUE THREAD

**Issue by zahir-elhoucine** [GetmeUK/ContentTools#291]
How to add element text(textarea or textbox) in dialogui
thanks.

**Comment by anthonyjb** [comment]
Hi @zahir-elhoucine,

Your going to need to be more specific about what it is you are trying to do and ideally present your code to date, what have you tried?

--

In line with the **Where to post... How do I?** guide in the project readme file please ask this question on StackOverflow for the benefit of everyone - I check SO daily and will happily post an answer there, but it does belong there not here. 

You can also leave a link to your SO questions here so I can find it and answer it more quickly (there's no `contenttools` tag on SO yet but I'm hopeful there will be soon).

General questions are better on SO as they are easier for people with the same or similar questions to find in the future.

Thank you in advance.

**Comment by zahir-elhoucine** [comment]
that's my goal 
![ok](https://cloud.githubusercontent.com/assets/10165602/17964801/ca7bb022-6ab2-11e6-9d68-5351b77cdc55.png)

**Comment by anthonyjb** [comment]
@zahir-elhoucine what have you tried so far? My advice would be to initially look at the CoffeeScript for the PropertiesDialog (here: https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/dialogs/properties.coffee)

The simplest approach is to:

- Create your own dialog class that extends `ContentTools.DialogUI`
- Override the `mount` method to insert your `textarea` DOM element (using the properties dialog code as an example).
