### ISSUE TITLE
editor.stop(true) Reverting Inline Style Changes On Block Level

### ISSUE THREAD

**Issue by haberman13** [GetmeUK/ContentTools#292]
**(firstly, this is an epic library, great job!)**

See update post below for temporary workaround with Javascript / jQuery extended block level styling.

I successfully extended the "Heading" tool to allow font color, background color, and a few other options using Javascript and jQuery for both the block level, and selection level.

Works great when applying styles to a selection, I can save, and the changes are saved.

On the other-hand, **all changes are removed from the block element styles when using editor.stop(true).**

Any idea how to prevent that reversion on the block level inline style additions?

Maybe forgo block level styles and just wrap the content in a span with the inline styles if there is no selection?

[hopefully that made sense]

The relevant section minus the jquery irrelvant stuff:

    ContentTools.Tools.Sup = (function (_super) {
        __extends(Sup, _super);

        // This class extends the existing Bold tool    
        function Sup() {
            return Sup.__super__.constructor.apply(this, arguments);
        }

        ContentTools.ToolShelf.stow(Sup, 'sup');

        // Set the tool tip that will appear
        Sup.label = 'Text and Block Options';

        // Set the name of the icon (this wont exist unless you add one)
        Sup.icon = 'option';
        
        Sup.isApplied = function (element, selection) {
            return false;
        };
        
        Sup.canApply = function (element, selection) {
            return true;
        };

        Sup.apply = function (element, selection, callback) {

            app = ContentTools.EditorApp.get();
            modal = new ContentTools.ModalUI();
            dialog = new ContentTools.PropertiesDialog(element);

            dialog.addEventListener('cancel', function () {
                $("#myModal").modal("hide");
                modal.hide();
                dialog.hide();

                callback(true);
            });

            var button = document.getElementById("saveCustomTextOptions");
            button.addEventListener('click', function () {
                $("#myModal").modal("hide");
                modal.show();
                dialog.show();
            });
                        
            dialog.addEventListener('save', function (ev) {

                detail = ev.detail();
                attributes = detail.changedAttributes;
                styles = detail.changedStyles;
                innerHTML = detail.innerHTML;
                               
                
                element.storeState();

                $.each(styles, function (k, v) {
                    if (v) {
                        if (element.hasCSSClass(k)) {
                            element.removeCSSClass(k);
                        } else {
                            element.addCSSClass(k);
                        }
                    } else {
                        if (element.hasCSSClass(k)) {
                            element.removeCSSClass(k);
                        }
                    }
                });
                
                var select = selection.get();
                
                if (select[0] === select[1]) {
                                                            
                    // no selection, globally apply options with jquery
                    // removed to shorten script (just jquery colorpicker style generating)
                    
                } else {
                                                            
                    // only apply to selected text
                   // jquery stuff removed
                    element.content = element.content.format(
                        select[0],
                        select[1],
                        new HTMLString.Tag("span", {'style': style}));                                                 
                }
                
                element.content.optimize();
                element.updateInnerHTML();
                element.taint();

                element.restoreState();
                                                   
                modal.hide();
                dialog.hide();

                callback(true);
            });

            $("#myModal").modal("show");
            app.attach(modal);
            app.attach(dialog);

            return Sup;
        };

        return Sup;

    })(ContentTools.Tools.Heading);

**Comment by haberman13** [comment]
Update:

As a temporary solution, I'm wrapping the content in a div, and applying the styles there, like so:

// remove previous
element.content = element.content.unformat(0, -1, "div"); 

// add new
element.content = element.content.format(
                        0,
                        -1,
                        new HTMLString.Tag("div", {'style': style})); 

Where "style" = the inline styles.

If anyone has any questions about extending Contenttools with javascript, let me know.  I have a good grasp on it now.

**Comment by anthonyjb** [comment]
Hi @haberman13 - thanks for the kind words and it's awesome to hear you mastering the library in JS :+1: 

From your example I can't see how you set styles against the element, only how you set them against the inline block. To set the style attribute against the block level element are you using the `attr` method, e.g:

```element.attr('style', 'background: red;')```

If not the attribute changes wont be remembered.

**Comment by haberman13** [comment]
@anthonyjb - thank you!  That fixed it.

I (cheated and) was using jQuery(element._domElement).css(); which didn't set the state within your library I'm guessing.

Again I'll say this is a fantastic library, you did a great job coding it.
