### ISSUE TITLE
How to add blockquote element in toolbox

### ISSUE THREAD

**Issue by alichoobdar** [GetmeUK/ContentTools#294]
Hi! First of all Thanks for your amazing work. i don't know how to expose my feeling. its just the library i wanted.

I need to add a tool in toolbox that add a "blockquote" element to DOM. please help me with this.

thanks again

**Comment by anthonyjb** [comment]
Hi @alichoobdar thanks for the kind words :)

So the simplest approach here is to inherit from an existing tool such as `ContentTools.Tools.Heading`, for example:

```CoffeeScript
class ContentTools.Tools.BlockQuote extends ContentTools.Tools.Heading

    # Convert the current text block to a block quote (e.g <blockquote>foo</blockquote>)

    ContentTools.ToolShelf.stow(@, 'blockquote')

    @label = 'Block quote'
    @icon = 'blockquote'
    @tagName = 'blockquote'
```

The [Adding new tools](http://getcontenttools.com/tutorials/adding-new-tools) tutorial covers how to insert a new tool into the toolbox.

If you need to convert the code to JavaScript I often use: http://js2coffee.thomaskalka.de/ 

--

In line with the **Where to post... How do I?** guide in the project readme file please ask questions of this nature on StackOverflow for the benefit of everyone - I check SO daily and will happily post an answer there, but such questions don't belong here (historically they did and I apologise for any confusion).

You can also post a link to your SO question in the gitter feed so I can find and answer it quicker (I don't have an SO tag for ContentTools yet but hopefully will soon).

General questions are better on SO as they are just easier for people with the same or similar questions to find in the future.

Thank you in advance.
