### ISSUE TITLE
Adding padding on the images

### ISSUE THREAD

**Issue by d0brii** [GetmeUK/ContentTools#296]
I need help with Images. As I can see, in the edit mode, all image tags become divs and images are displayed as a background element of that div.  
If I try to add padding to the image, padding will be applied to the div itself, and practically it will not be visible until I leave edit mode, and div placeholder get revert to image tag again.
Is there any way that I can apply padding to the image, besides via predefined styles, and that is visible during editing of the page?  
Is it possible to keep image image,  in the edit mode, without turning it into the div?
Below is code I'm using to add padding to the image. Probably is not most elegant way to do it. 

`var selectedElm = ContentEdit.Root.get().focused();`
`var ahrev             = selectedElm._attributes.src; `
`var aheight = selectedElm._attributes.height;`
`var awidth  = selectedElm._attributes.width;`
`var image = new ContentEdit.Image({src: ahrev,style:'padding:5px;',height:aheight,width:awidth});`
`selectedElm.parent().attach(image, selectedElm.parent().children.indexOf(selectedElm))`
`selectedElm.parent().detach(selectedElm); `

Thank You

**Comment by anthonyjb** [comment]
Hi @d0brii,

OK so I've done a little bit of playing around with what's possible with CSS and there's 2 easy (if not perfect) options here that are easy if you want to add padding to the image and keep it's appearance when in edit mode (e.g when it is represented with a div with a background image):

1. Apply the padding as a border instead e.g `border: 5px solid transparent`.
2. (Recommended) Add the following to your CSS for ContentTools:

```CSS
.ce-element--type-image {
    background-origin: content-box;
}
```

I hadn't used `background-origin` before but it's really cool and means that the padding will be applied around the background image in the div so it behaves the same as the image.

I tested both these on the website demo and both worked for me, let me know how you get on.

**Comment by d0brii** [comment]
Thank You very much,
Second option feels more natural, or as it should be. :)   

Regarding my second question, is it possible to keep image image, in the edit mode instead converting it to the div; reason I'm asking is that DIV and IMG respond differently in the (left, right) align situations.  

So if i have image just below paragraph in a template. and than, in the edit mode, I drag that image to the left, as it's indicated by arrows in layover, in the edit mode, Image stays on the right side of the paragraph, as it should, but when I switch to preview mode, picture drops below paragraph. 

Both IMG and DIV have "align-left" style applied.  To maintain image position on the left of the paragraph in the preview mode IMG tag should have, float: left, applied instead. 

Is that possible?

Edit Mode
![screen shot 2016-08-30 at 9 12 50 pm](https://cloud.githubusercontent.com/assets/8220543/18115749/a17add9a-6ef6-11e6-95fc-d726c332175a.png)

Preview Mode
![screen shot 2016-08-30 at 9 13 10 pm](https://cloud.githubusercontent.com/assets/8220543/18115754/ad6318de-6ef6-11e6-98ed-b99e3da5d800.png)

**Comment by anthonyjb** [comment]
It is possible to switch the type from `div` to an `img` tag (with some caveats) and there is a discussion on this in another issue (thought I failed to find it - but it is here :/) - however I don't think this will solve this problem.

The CSS class `align-left` should be applied as you say to both the `div` (in edit) and `img` (in preview) versions of the image (e.g `<div class="align-left" ...>` or `<img class="align-left" ...>`, and the CSS you define for the `align-left` class should apply `float: left`. There's an example of the default CSS that you should apply for your project here: http://getcontenttools.com/getting-started#preparing-the-css

**Comment by d0brii** [comment]
Thank You :) Some how I miss that part 👍

**Comment by Alex360hd** [comment]
The problem come from the use of a div with background instead of real img tag when you edit an image.

You probably have a css framework like boostrap that apply a max-width:100% to your image to make them "responsive".

The problem is that due to :before and :after issue, the plugin use background css property in a div when you edit the images.

But as you switch to img tag to a div with background, you have a lot of different visual issue that become to appears. Yours is great example.

To fix it, you should wait for the module to support real img tag instead of converting it. I think the plugin should allow this in a parameter when you call the plugin.
