### ISSUE TITLE
Add br instead of p when pressing the Enter.

### ISSUE THREAD

**Issue by megamuf** [GetmeUK/ContentTools#299]
I need to when pressing the "enter" instead tag p add tag br,
how it can be implemented?
Thank in advance.

I need ask this question on http://stackoverflow.com ?

**Comment by anthonyjb** [comment]
Hi @megamuf, ideally yes because then others will find it quicker.

**Comment by anthonyjb** [comment]
@megamuf If you post a link to it here so I can find it I'll answer for you ASAP.

**Comment by megamuf** [comment]
@anthonyjb 

http://stackoverflow.com/questions/39373723/content-tools-add-br-instead-of-p-when-pressing-the-enter

Question on stackoverflow
