### ISSUE TITLE
Q: what should the approach be to have separate Content Tools on one view?

### ISSUE THREAD

**Issue by mattgi** [GetmeUK/ContentTools#30]
We have a bootstrap style layout:
```
<Row>
  <Column>
    <Content id="1" />
  </Column>
  <Column>
    <Content id="2" />
  </Column>
</Row>
```

At present each Content component (we are using React) has its own editor via `new ContentTools.EditorApp.get()` and `this.state.editor.init(`#${ this.state.id } [data-editable]`, 'data-editable');`. This all works well, however, if you have the scenario above with two content editors on the one View, we are running in to a problem with the placement of the `ct-widget`s (ignition, toolbox and inspector)... ideally we would like these to all be contained within the Content wrapping DIV so we can have control over their position.. is this possible?

**Comment by mattgi** [comment]
I should add that if the correct answer is - "only provide support for one editor on the view, and allow a way to obtain the `id` of the Content that is being edited", could you suggest how this could be accomplished?

**Comment by anthonyjb** [comment]
So just to be clear here calling `ContentTools.EditorApp.get()` multiple times will always return the same instance of an app. This is function basically enables singleton behaviour. If you call `init` against the editor multiple times though, without calling `destory` in between the UI will be implemented multiple times - which is not what you want.

As you suspected the correct answer is to only `init` the editor once. My recommendation therefore would be to mark your editable components up with `<... id="1" data-editable>` as I think you are and initialize the editor like so:

**Comment by anthonyjb** [comment]
Sorry I was a bit trigger happy on the submitting the response there, I've updated it so it's complete now. Let me know if that helps or if I've misunderstood.

**Comment by mattgi** [comment]
Thanks Anthony.. it does help, but it it also means a parent needs to be aware that it has a content section and then initialize the editor accordingly... which is a bit of an anti-pattern in our app as we are trying keep each component modular and encapsulated.

Do you see issues in calling `init` more than once (other than the placement of the ct-widgets)? The query passed to `init` is specific for the content in question (e.g. `init('#some-id [data-editable], 'some-id')`... perhaps there is a way to specific the parent selector for the ct-widget (current appended to body is my guess) if this is the only real issue.

**Comment by mattgi** [comment]
I actually think I can handle things by calling init via my own buttons within my component.

```
  startEdit() {
    if (this.state.editor) {
      this.state.editor.init('[data-editable]', 'id');
      this.state.editor.bind('save', this.submit);
      this.state.editor.start();
    }
  }

  stopEdit() {
    if (this.state.editor) {
      this.state.editor.stop();
      this.state.editor.save();
    }
  }
```

in my save handler, i also have
```
this.state.editor.unbind('save', this.submit);
this.state.editor.destroy();
```

This seems pretty clean.. I just need to figure out how to not load the ignition buttons (or at worst, set them to `display : none` ).

Seem like an acceptable approach?

**Comment by anthonyjb** [comment]
So you yes if you `destroy` then `init` the editor when you switch between components that should work fine and I think that's a clean way to decouple the components.

I don't see a problem with using CSS to hide the ignition, I use CSS to hide interface buttons I don't want to show to users sometimes like I might hide the code button from a non-technical user. 

One option would be to unmount the ignition from the editor after initializing, eg:

    editor.init(...);
    editor._ignition.unmount();

This would remove ignition from the DOM but shouldn't affect the editors behaviour in any way.

To make this cleaner still you might consider modifying the editor for your application to not include the ignition switch at all, it would be pretty easy to remove (I think it's referenced about 9), if your unsure I can send you a CoffeeScript or JS version with no switch.
