### ISSUE TITLE
Glitch in Ignition UI

### ISSUE THREAD

**Issue by Hoiy** [GetmeUK/ContentTools#303]
Visit http://getcontenttools.com/demo
Double click the edit button quickly. (to change to edit mode and then back to ready mode)
Toolbox is displayed in ready mode.

Similarly, double click the "tick" sign at edit mode. (to change to ready mode and then back to edit mode)
Toolbox disappeared in edit mode.

**Comment by anthonyjb** [comment]
Thanks for reporting this @Hoiy - I'll include a fix in the next release for start of next week.
