### ISSUE TITLE
Line breaks are removed from end of paragraph when pressing enter to start a new paragraph

### ISSUE THREAD

**Issue by bcreeves** [GetmeUK/ContentTools#306]
When I'm typing in a paragraph and hold down shift and enter to add line breaks to the end of it, if I then hit enter to start a new paragraph those line breaks are removed from the end of the last paragraph. Is this a bug or by design?

**Comment by anthonyjb** [comment]
Hi @bcreeves this is by design though it's been debated back and forth - there is a patch/workaround if you want to change this behaviour but it isn't pretty, please see this issue for further information: https://github.com/GetmeUK/ContentTools/issues/113
