### ISSUE TITLE
Customizing the Edit, Save and Cancel buttons

### ISSUE THREAD

**Issue by cadilhac** [GetmeUK/ContentTools#307]
Hi,

Just discovered this script. It seems very nice.
A first question I have is this: showing the circle icon with the pen, as well as the Save and Cancel buttons, fixed in the top left corner is not suitable for my app. I would prefer to start editing by directly clicking in the editable content. Then a custom Save and Cancel buttons (with the appearance I want) would appear just on top of this area. Is such a thing possible?
Thanks

**Comment by anthonyjb** [comment]
Yes this is possible, you can use SCSS/CSS to modify the appearance of the ignition buttons or simply hide/remove them and role your own.

To hide/remove the elements either use CSS, e.g:

```css
.ct-ignition {
    display: none;
}
```

or JS, e.g:

```JavaScript
var editor = ContentTools.EditorApp.get();
editor.init('data-editable', 'data-name', null, false); // The last argument states we don't want an ignition switch
```

To manually start/stop then you can use the named methods, e.g:

```JavaScript

// Manually start the editor
editor.start();

// Manually stop the editor
editor.stop(save); // Pass true to save, false to cancel
```

Hope that helps, there's some more information on this here http://stackoverflow.com/questions/34645700/customise-edit-button-for-contenttools though the approach is slightly out dated now and the above is cleaner / more current.

**Comment by cadilhac** [comment]
Wonderful, thank you.

In the same spirit, may I ask a similar question:
Can I reposition the bottom bar inside a container instead of the bottom of the screen?

**Comment by anthonyjb** [comment]
The inspector bar can be modified in appearance using SCSS/CSS again, the class you need to look at is `ct-inspector`. By default the inspector is mounted to it's parents DOM element, in the case the editor but if you need to mount it in another element you could consider either overwriting the `mount` and having it mount the element to a parent DOM element of your choosing.

The relevant code can be found here: https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/inspector.coffee#L13

**Comment by cadilhac** [comment]
Unfortunately coffeescript won't fit in my workflow and I am against modifying the library, prefering hooks  to override stuff.
About the css, I was not able to find a non minified css file...

**Comment by anthonyjb** [comment]
ContentTools uses SCSS to generate its CSS so you need to look here: https://github.com/GetmeUK/ContentTools/tree/master/src/styles

You can use JavaScript to modify the library (though it's not as clean as using CoffeeScript given it's developed in CoffeeScript). I understand not wanting to modify the library, and whilst CT does provide events for lots of things (I removed hooks early on in favour of events) these don't provide a solution to this question as you can't use events to modify the editor adding the inspector bar some where (it would be possible technically to make this an event you can bind to a customize but I don't believe that's the correct approach).

You can go a long way with CSS to customize the appearance but if you want to modify the editor UI beyond appearance (e.g the structure) it will most likely mean modifying (either by patching or inheriting) the CT library.

**Comment by elsaroze** [comment]
window.addEventListener('load', function() {
    var editor;

	ContentTools.StylePalette.add([
    new ContentTools.Style('Author', 'author', ['p'])
]);

    editor = ContentTools.EditorApp.get();
    editor.init('*[data-editable]', 'data-name');
	
	// Add support for auto-save
editor.addEventListener('start', function (ev) {
    var _this = this;

    // Call save every 30 seconds
    function autoSave() {
        _this.save(true);
    };
    this.autoSaveTimer = setInterval(autoSave, 30 * 1000);
});

editor.addEventListener('stop', function (ev) {
    // Stop the autosave
    clearInterval(this.autoSaveTimer);
});
	
editor.addEventListener('saved', function (ev) {
    var name, onStateChange, passive, payload, regions, xhr;

    // Check if this was a passive save
    passive = ev.detail().passive;

    // Check to see if there are any changes to save
    regions = ev.detail().regions;
    if (Object.keys(regions).length == 0) {
        return;
    }

    // Set the editors state to busy while we save our changes
    this.busy(true);

    // Collect the contents of each region into a FormData instance
    payload = new FormData();
    payload.append('__page__', window.location.pathname);
    for (name in regions) {
        payload.append(name, regions[name]);
    }

    // Send the update content to the server to be saved
    onStateChange = function(ev) {
        // Check if the request is finished
        if (ev.target.readyState == 4) {
            editor.busy(false);
            if (ev.target.status == '200') {
                // Save was successful, notify the user with a flash
                if (!passive) {
                    new ContentTools.FlashUI('ok');
                }
            } else {
                // Save failed, notify the user with a flash
                new ContentTools.FlashUI('no');
            }
        }
    };

    xhr = new XMLHttpRequest();
    xhr.addEventListener('readystatechange', onStateChange);
    xhr.open('POST', '/x/save-page');
    xhr.send(payload);
});
});

Editor wont save
