### ISSUE TITLE
Getting minified html to save

### ISSUE THREAD

**Issue by cadilhac** [GetmeUK/ContentTools#308]
Another thing I noticed. In the Save handler, when I get the html from the region, I get also many unnecessary spaces and newline chars. Is it possible to get a stripped version, like minified, of the html?
Thanks

**Comment by anthonyjb** [comment]
Hi @cadilhac, 

You can modify the indentation applied using the `ContentEdit.INDENT` setting and specifying it as a blank space, e.g:

```JavaScript
ContentEdit.INDENT = '';
```

But you can't set the tool not to save with new lines after each editable element output. 

The HTMLString library CT relies outputs pretty efficient HTML for it's part, but the new lines and indentation are applied by ContentEdit.

**Comment by cadilhac** [comment]
It would be great if it was an option too. I imagine I will be able to remove the newlines by myself though...

**Comment by anthonyjb** [comment]
I'd be careful about removing them yourself as you will need to check for newlines in preformatted elements, this includes `<pre>` tags and elements styled with `white-space: nowrap;`.

If you'd like this to be a feature please post a feature request on the ContentEdit issue tracker.
