### ISSUE TITLE
Images as urls

### ISSUE THREAD

**Issue by cadilhac** [GetmeUK/ContentTools#309]
ah! It seems I met a showstopper. For my customer I need to be able to enter images by url (i.e. they exist on the web already) and it seems your tool doesn't do that, which surprises me because it seems simplier than uploading an image. Is it something you will add to your library in the short term?
I could add them by typing html code I imagine, but I'm not sure end users would like that.

**Comment by anthonyjb** [comment]
Hi @cadilhac - you can implement anything you want for image uploads, the demo includes a faked file upload but CT does not handle image uploads for you - it's a client side library, it just provides an example interface that can be used as a basis.

People have integrated kcfinder for example (and others) if you want a ready made tool for inserting images, see here: https://github.com/GetmeUK/ContentTools/issues/199

I also recommend you take a look at the tutorial on handling image uploads: http://getcontenttools.com/tutorials/handling-image-uploads in case you want to role your own.

**Comment by cadilhac** [comment]
Seems I was not clear. I don't want to upload at all. I just want a dialog to appear where I can type a url to an image. Then the tool embeds the IMG tag in the content. That's all.

**Comment by anthonyjb** [comment]
@cadilhac yes I understand and you can implement exactly that, your not restricted from doing that in anyway, after all the image upload tool example ultimately allows simply inserts a URL for the image you upload.

If you want to *ONLY* support insert an image based on an existing URL from the web (And you don't want to integrate an existing file manager) then I'd suggest creating an image dialog (no options for crop or rotate) based on the `VideoDlg` class (which does something very similar and just asks for URL before presenting a preview).

This would mean creating your own image tool and a custom image dialog, so depending on how comfortable you are with CoffeeScript/JavaScript this might be either relatively easy (if you have a fair bit of experience) or a potentially challenging (if you only have a little experience). However if you decided to give it ago and get stuck feel free to shout me on gitter and I'll gladly lend a hand whenever I can.

**Comment by cadilhac** [comment]
ok thanks for the info. Since this is a job for a customer and is budget does not allow these kind of customizations, I will have to find another tool that handles img urls natively.
