### ISSUE TITLE
Unable to stop the blinking animation around editable area

### ISSUE THREAD

**Issue by Hoiy** [GetmeUK/ContentTools#312]
To reproduce the issue, I am using a mac with chrome.
1. Visit http://getcontenttools.com/demo
2. Enter edit mode by clicking the pencil button
3. cmd + shift + 4 to trigger the blinking animation around editable area.
4. Not sure how to turn off the animation

<img width="1397" alt="screen shot 2016-09-20 at 5 51 08 pm" src="https://cloud.githubusercontent.com/assets/4758788/18665892/e2759fae-7f5b-11e6-94a0-15521aced8a7.png">

**Comment by anthonyjb** [comment]
Hi @Hoiy, just hitting the shift key again should stop it. Not sure why it stayed on, basically when you hold down shift for a couple of sections the editable regions on the page are highlighted so you can see what can be changed, if something prevents the page from registering that the shift key has been released (I'm assuming you released it) then the animation continues.

Sounds like I need to put something in to prevent the animation being triggered if `cmd` is down as well, flagging as a minor bug.

**Comment by Hoiy** [comment]
@anthonyjb aw I see. I didn't realize that I could use shift key to disable it. And yes, the animation would stay if you press cmd + shift + 4 (and release) on a mac which is used to capture screenshot.
