### ISSUE TITLE
How to configure control tool options

### ISSUE THREAD

**Issue by BruinY** [GetmeUK/ContentTools#314]
Editing tools how to implement hide some simple function.For example: don't use tables, or do not use the hyperlinks

**Comment by anthonyjb** [comment]
Hi @BruinY,

The general approach is to define sets of tools and then use attributes or classes against your regions to determine which set of tools is displayed while elements in that region have focus.

There's a discussion this here with an example in the closing comments on how to implement what your after: https://github.com/GetmeUK/ContentTools/issues/173

As an example:

```JavaScript
var TOOLS_A = [['bold', 'italic']];
var TOOLS_B = ContentTools.DEFAULT_TOOLS;

ContentEdit.Root.get().bind('focus', function (element) {
  var editor = ContentTools.EditorApp.get();
  if (element.domElement().classList.contains('tools-a')) {
    editor.toolbox().tools(TOOLS_A);
  } else {
    editor.toolbox().tools(TOOLS_B);
  }
});
```

```html
<div data-editable="region-a" class="tools-a">
    <p>This element will only support bold and italic</p>
</div>
<div data-editable="region-b" class="tools-b">
    <p>This element will support all tools</p>
</div>
```

**Comment by BruinY** [comment]
good,thanks
