### ISSUE TITLE
How to edit nested elements?

### ISSUE THREAD

**Issue by mpatelj** [GetmeUK/ContentTools#315]
Hey, we were using TinyMCE 3.4 for the longest time and wanted to switch to the ContentTools as it has more control over the layout.  It works great with the HTML body that has direct children but we ran into the issue while editing the nested elements in the HTML body.  TinyMCE creates HTML body in a different manner which makes it hard for ContentTools to go recursively and add the classess which makes the content editable.  Below is the sample HTML body that was created after the page is loaded and somehow the EDIT button doesn't allow us to edit the content as it is missing the classess obviously.  

```
<div data-editable="" data-name="main-content" data-bind="html: content().body">
<div id="table-type-0" class="ce-element ce-element--type-static ce-element--over">
<p><span style="color: #0000ff; font-family: Arial; font-size: large;"><strong>PERFORMING THE TEST</strong></span></p>
<p><span style="font-family: Arial; font-size: medium;">To perform the VOR test, a local VOR frequency is selected, a course of 000 is selected, the RMI selector is positioned to VOR, and the VOR test button on the receiver or control panel is depressed.&nbsp; </span></p>
<ul>
<li><span style="font-family: Arial; font-size: medium;">The navigation warning flag drops into view for 3-9 seconds (depending on the slew time of the RMI) and then is retracted from the view for the remainder of the 23-second test period.&nbsp; <br><br></span></li>
<li><span style="font-family: Arial; font-size: medium;">The RMI pointer rotates to 180 degrees.&nbsp; <br><br></span></li>
<li>
<div align="left"><span style="font-family: Arial; font-size: medium;">The HSI course deviation bar is centered and the TO/FROM pointed indicates FROM.<br><br><br></span></div>
<div align="center"><iframe title="vzaar video player" src="https://view.vzaar.com/1279492/player" frameborder="0" width="448" height="280"></iframe></div>
</li>
</ul>
</div><p class="ce-element--empty ce-element ce-element--type-text"></p></div>
```

We thought to open the discussion as you respond way quicker comparatively.  Let me know if you need any extra info.

**Comment by anthonyjb** [comment]
Hi @mpatelj - it's a little difficult to tell from the HTML above what is going on, some of the classes on the elements above are CE classes (e.g `ce-element ce-element--type-static ce-element--over`) which typically means there's been an issue in editing and the classes haven't been properly cleared before a re-edit and save.

Can you provide me with an example of the HTML you would like to edit with CT/CE which should help me identify what might be going on and why CT/CE is struggling here.

**Comment by mpatelj** [comment]
```<div id="table-type-0">
<p><span style="color: #0000ff; font-family: Arial; font-size: large;"><strong>PERFORMING THE TEST</strong></span></p>
<p><span style="font-family: Arial; font-size: medium;">To perform the VOR test, a local VOR frequency is selected, a course of 000 is selected, the RMI selector is positioned to VOR, and the VOR test button on the receiver or control panel is depressed.&nbsp; </span></p>
<ul>
<li><span style="font-family: Arial; font-size: medium;">The navigation warning flag drops into view for 3-9 seconds (depending on the slew time of the RMI) and then is retracted from the view for the remainder of the 23-second test period.&nbsp; <br /><br /></span></li>
<li><span style="font-family: Arial; font-size: medium;">The RMI pointer rotates to 180 degrees.&nbsp; <br /><br /></span></li>
<li>
<div align="left"><span style="font-family: Arial; font-size: medium;">The HSI course deviation bar is centered and the TO/FROM pointed indicates FROM.<br /><br /><br /></span></div>
<div align="center"><iframe title="vzaar video player" src="https://view.vzaar.com/1279492/player" frameborder="0" width="448" height="280"></iframe></div>
</li>
</ul>
</div>
```

**Comment by anthonyjb** [comment]
Hi @mpatelj,

So ContentEdit which parses the HTML content wont support this structure I'm afraid, it's designed to manage flatter structures with a focus on lean/clean HTML output. Out the box it doesn't support `div`s in a list item (or anywhere actually) because it doesn't know what type of element parse a `div` as  - people have implemented support significantly more complex structure support including column and grid layouts (@bfintal for one) - so it's possible to make ContentEdit understand this structure, but it's not a small task to do a nice job of it.

The other option is to restructure your HTML and use CSS to perform all the styling and to keep the structure inline with something CE supports, e.g (purely illustrative):

```html
<div class="test-scenario" data-editable="my-region">
    <p class="test-scenario__title">Performing the test</p>
    <p class="test-scenario__desc">
        To perform the VOR test, a local VOR frequency is selected, a course of 000 is selected, 
        the RMI selector is positioned to VOR, and the VOR test button on the receiver or control 
        panel is depressed.
    </p>
    <ul class="test-scenario__when">
        <li class="test-when">
            The navigation warning flag drops into view for 3-9 seconds (depending on the slew 
            time of the RMI) and then is retracted from the view for the remainder of the 
            23-second test period.&
        </li>
        <li class="test-when">
            The RMI pointer rotates to 180 degrees.
        </li>
    </ul>
    <ul class="test-scenario__then">
        <li class="test-then">
            The HSI course deviation bar is centered and the TO/FROM pointed indicates FROM.
        </li>
    </ul>
    <iframe
        src="https://view.vzaar.com/1279492/player" 
        class="test-scenario__visual  test-scenario__visual--video"
        frameborder="0" 
        width="448" 
        height="280"
        >
</div>
```

**Comment by tommedema** [comment]
@anthonyjb does this mean that it is not possible to use ContentTools with arbitrary HTML pages over which you have no control, e.g. HTML that is input by users or that comes from other sites? since you cannot guarantee how the dom is structured? would other editors be more suitable then?

**Comment by anthonyjb** [comment]
Hi @tommedema I can't comment on the suitability of other WYSIWIG editors for handling unauthenticated mark up, but ContentTools whilst providing support for flexible layouts does require that the HTML has a top level structure that clearly defines which areas of the page are editable (regions and fixtures). CT supports a limited set of HTML tags it handles out of the box, but this set can be extended for specific use cases. Anything not in that limited set (e.g any elements it doesn't know how to provide editing functionality for) are simply made static so that they can be edited around.
