### ISSUE TITLE
Possibility to change the background  properties ?

### ISSUE THREAD

**Issue by sahanjith** [GetmeUK/ContentTools#316]
Lets say we've put the editable tag into body tag, will it be possible to replace the background with different image by this approach ?

**Comment by anthonyjb** [comment]
Hi @sahanjith take a look at this issue which includes an example approch to doing just that: https://github.com/GetmeUK/ContentTools/issues/242

**Comment by sahanjith** [comment]
@anthonyjb Thank you! and greatly appreciated! I'm using content tools as an editor for my project and its  simply great. but, its  bit unclear for me how come i attach this background image uploader to my project ? a little explanation would do. i've converted the coffee script to js.

**Comment by sahanjith** [comment]
@anthonyjb it worked. Thanks a lot!
