### ISSUE TITLE
Placing pencil icon on different division ?

### ISSUE THREAD

**Issue by sahanjith** [GetmeUK/ContentTools#317]
How to place the pencil icon on a different place of the page? Not left corner always.

**Comment by anthonyjb** [comment]
Take a look at this question https://github.com/GetmeUK/ContentTools/issues/307 it discusses creating your own ignition button, if you simply want to place the button in a different location however I'd recommend you just modify the SASS/CSS for the ignition button class: https://github.com/GetmeUK/ContentTools/blob/master/src/styles/ui/_ignition.scss#L34

**Comment by sahanjith** [comment]
@anthonyjb Thanks..It worked! :)
