### ISSUE TITLE
Changing an Inserted Image

### ISSUE THREAD

**Issue by sahanjith** [GetmeUK/ContentTools#321]
Is it possible to change an image that has been inserted from palette  or an image which is already there in page rather than deleting and inserting new image.

**Comment by anthonyjb** [comment]
Hi @sahanjith - there's nothing in place for this at the moment but it's also something I want. My plan is to implement it so that if you have selected an image and you then attempt to upload a new one you will have the option to insert or replace (instead of just insert). On select to replace the image the existing selected image will be replaced.

I've flagged this for the next milestone some will be available sometime in the next couple of weeks.

**Comment by anthonyjb** [comment]
Hi @sahanjith I'm not sure what the benefit of @guillaumepiot's approach in this case would be, that approach specifically looks at background images and means a change to the image always switches the image out with the new one. This makes sense for background images but would be restrictive for general  image use as you might wish to add an image after the current image?

**Comment by Alex360hd** [comment]
+1 to this, it would be really great to be able to change an image.

For inspiration, look at the contentbuilder.js way to do that : http://innovastudio.com/builderdemo/example1.html

**Comment by abishekrsrikaanth** [comment]
@anthonyjb I have been having a wonderful time working on this library, but just lacking this functionality alone. Would you have updates on this feature's availability?

**Comment by anthonyjb** [comment]
Hi @abishekrsrikaanth - thanks for the kind words :D This feature is on my list I'm just very short on time currently. At the moment the best estimate I can provide is some time in the next 6-8 weeks, it's dependent on me finishing up a large release on another OS project I'm involved with (which CT is a part of).

**Comment by abishekrsrikaanth** [comment]
@anthonyjb, just checking to see if there are any updates to this request?

**Comment by anthonyjb** [comment]
@abishekrsrikaanth just wanted to let you know the ability to implement image fixtures (editable background images in effect) will be out in the next release today (1.4.0). This feature will make it possible to change the existing image in place. (It's currently available in draft within an example in the sandbox).
