### ISSUE TITLE
I get Uncaught SyntaxError: Unexpected end of JSON input at Image upload

### ISSUE THREAD

**Issue by VexareHD** [GetmeUK/ContentTools#324]
My PHP Code:
`<?php
move_uploaded_file($_FILES['image']['tmp_name'], 'uploads/'.$_FILES['image']['name']);
?>`

**Comment by anthonyjb** [comment]
Hi @VexareHD - I really can't help you based on what you've posted, at best I can say it sounds like you're not returning the `JSON` from your PHP method, or if you are that `JSON` is perhaps corrupt.

This type of question is better suited to StackOverflow than the github issues for CT as it is not specific to the library itself but your use of the library.
