### ISSUE TITLE
Having Customized Tool Boxes.

### ISSUE THREAD

**Issue by sahanjith** [GetmeUK/ContentTools#325]
Hi! i would like to know that is it possible to have customized tool boxes for different elements rather than having the default one for everything? 

In sandbox example by using data fixtures we can give users two different type of tool boxes, Default one and edited one. In similar manner can we implement something like this.
-When user clicked a text area only text editing related tools will be visible. Options like image uploading wont be there. 
-Also an another ares is made to insert images only, and there only the image tool and undo,redo options will be there in tool box. Text editing tools will not be available.

**Comment by anthonyjb** [comment]
Hi @sahanjith,

Take a look at this SO post: http://stackoverflow.com/questions/39400459/how-do-i-disable-enable-tools-based-on-content-on-contenttools I think that covers what you are looking for?

**Comment by sahanjith** [comment]
@anthonyjb Thank you for the response. I understood the way it should be implement. But only this place is bit unclear for me. 

if (element.domElement().classList.contains('plain-text'))

if (element.domElement().classList.contains('no-images')) 

if (element.domElement().classList.contains('text-only'))

do we have to set css classes for the elements in order to get them work ?

**Comment by sahanjith** [comment]
Hi @anthonyjb  Thank you for the response. This works with block level elements. If i want this to be happen with a div how to do that ? 

if (element.domElement().classList.contains('no-images')) 

how to check this condition with a div ?

**Comment by anthonyjb** [comment]
Hi @sahanjith well you can apply the same technique using a parent element if that's what you're looking for, you just need a way to find the closest parent element with a given class, e.g:

```JavaScript
if (element.domElement().closest('.no-images')) {
    ...
}
```

**Comment by sahanjith** [comment]
@anthonyjb yeah.....it worked! Thanks!
