### ISSUE TITLE
I'm not sure what this is  '/x/save-page'  file is suppose to be.

### ISSUE THREAD

**Issue by JeanPierreFig** [GetmeUK/ContentTools#329]
In the Saving strategies page you said that the recommended way to save data is with AJAX but I'm not sure what save-page is suppose to be.

**Comment by JeanPierreFig** [comment]
If it's a php file do you have any sample code for that?

**Comment by anthonyjb** [comment]
Hi @JeanPierreFig this isn't really a CT question so it should be asked on gitter or SO - I can't help you on the PHP front I'm afraid but there are other users on gitter who may be able to and there are some PHP frameworks with integrations such http://www.yiiframework.com/extension/yii2-content-tools/ you might take a look at.

The (Saving strategies tutorial)[http://getcontenttools.com/tutorials/saving-strategies] does include code for saving to a file based storage system but unfortunately it's written in Python though depending on your coding ability you maybe able to understand enough of it to implement a PHP script.
