### ISSUE TITLE
Is there a way to make a static element draggable?

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#33]
Alternatively, is there a way to make something uneditable but not technically static so it can still be dragged?

**Comment by anthonyjb** [comment]
Not currently - static elements can contain anything and so the library doesn't interfere with them (so we don't add events to them), it might be an idea to add a sort of mix up, a moveable-static option for when you know it's OK to add behaviour to the element.

**Comment by bfintal** [comment]
A moveable-static would be awesome.

Moving shouldn't be a problem I think. If the movement performed is the same thing that happens with the rest (kinda like just moving the dom around), then there shouldn't be any problem. The main parent that has the movable-static attribute would be wholly moved.

**Comment by anthonyjb** [comment]
OK I think I can add a flag that allows statics to be moveable, so you'd add something like `data-ce-moveable` to your static element and it would then allow the drag behaviour. I don't think it will take me long but I'm just shooting out for the evening - however I can have something for you for tomorrow if that will help?

**Comment by bfintal** [comment]
Tomorrow would be great!! :+1:

**Comment by anthonyjb** [comment]
@bfintal OK that should be in place now, to make a static element moveable/draggable add the following attribute to the element itself `data-ce-moveable`.

Thanks for the suggestion it's a really nice little enhancement and actually now it's in place I can think of a number of times I could/should of used it. :+1:

**Comment by bfintal** [comment]
Just tried it! and It works great! I'm doing an experimental WordPress plugin using Content Tools and I'll keep you updated on it :)

**Comment by anthonyjb** [comment]
That would be fantastic - integration with mainstream applications like WordPress are going to be the best way for the project to gain traction. If I can help in anyway let me know, once you have something to demo I'm happy to add a link from getcontenttools.com. :+1:
