### ISSUE TITLE
Upload and display pdf files 

### ISSUE THREAD

**Issue by ziguane** [GetmeUK/ContentTools#330]
Hi there !

I am discovering the ContentTools library, it is very impressive.
Is it possible to add a tool to upload a file to a server (pdf in my case) and then to generate the html code to display it (pdf.js in my case) ?

Thank in advance

**Comment by anthonyjb** [comment]
Hey @ziguane ,

There's nothing built in for uploading files and creating a link to them but this is very possible. You could either look to implement something similar to the existing image uploader (see the tutorial http://getcontenttools.com/tutorials/handling-image-uploads) but instead upload a file and from the returned file URL create a link. Or use an existing third-party file upload like [KCFinder](http://kcfinder.sunhater.com/) to handle the file uploads and again generate a link in your document once you get a return URL.
