### ISSUE TITLE
problem with <a>

### ISSUE THREAD

**Issue by k42m** [GetmeUK/ContentTools#333]
In my page I got following structure:
`<div  id="dynamicID" data-editable data-name="dynamicName">
    <a href="tel:123 456 789">
         <i class="fa fa-phone"></i>
     </a>
     <h2>Phone</h2>
     <h3>123 456 789</h3>
</div>`

Now when I go to the editing mode the a tag becomes a static element and when I wrap the` <a>` tag with a `<p>`, the `<a>` dissapears completley. Is this the normal behaviour of a "empty" `<a>`? I think it could be a problem beacuse of the fontawesome `<i>`
I need the possibility to edit the href attribute of this `<a>` tag

Thanks for your support!

**Comment by anthonyjb** [comment]
Hi @k42m,

By default you can't have an `a` tag on it's own like that simply because ContentEditable doesn't parse inline elements by default, to solve this you'd need to wrap it in a text block element, e.g:

```html
<div id="dynamicID" data-editable data-name="dynamicName">
    <p>
        <a href="tel:123 456 789">
            <i class="fa fa-phone">
                <span class="phone-label">Phone</span> 
                <span class="phone-number">123 456 789</span> 
            </i>
        </a>
    </p>
</div>
```

**Comment by k42m** [comment]
had to play around with the css (the template wasn't written to good...) but works for me now. 
Thank you so much!

PS: appreciate your work, content tools saved me hours :)
