### ISSUE TITLE
Check if some region(s) is edited

### ISSUE THREAD

**Issue by l2aelba** [GetmeUK/ContentTools#336]
_(Better if i opening new issue from #305)_

That I want is about to trigger if region(s) has been edited.

**Example :**

    User write down / add elements / edit styles .... <-- Edited
    User undo (cmd+z) until to the default  <-- Not edited

**My current code is :** 

```javascript
let CheckEditedStateTimeout;
ContentEdit.Root.get().bind('taint', function (element) {
    clearTimeout(CheckEditedStateTimeout);
    CheckEditedStateTimeout = setTimeout(function(){
        let app = ContentTools.EditorApp.get();
        let edited =  app.history && app.history.canUndo();
        console.log(edited);
    },1000);
});
```
**Demo :** https://jsfiddle.net/g6v3rxLd/

Can you please review my code ? Im not sure this is a good way to do and I will try to code a good performance as well

**Comment by l2aelba** [comment]
**Question 2 :**

Anyway can I just collect data j**ust for regions who was edited ?**
This code is collect all HTML but without checking their region is edited or not.

```
let regions = ContentTools.EditorApp.get().regions();
let data = {};
for (let name in regions) {
	let region = regions[name];
	data[name] = region.html();
}
console.log(data);

```

**Comment by anthonyjb** [comment]
Hi @l2aelba,

You can check if a region has been modified since the editor was started in the same way that the editor itself does (see here: https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/editor.coffee#L551).

So for example:

```JavaScript
let regions = ContentTools.EditorApp.get().regions();
let data = {};
for (let name in regions) {
    let region = regions[name];

    // Has the region been modified? If not skip it
    if (region.lastModified() == ContentTools.EditorApp.get()._regionsLastModified[name]) {
        continue;
    }

    data[name] = region.html();
}
console.log(data);
```

**Comment by l2aelba** [comment]
@anthonyjb Oh wow Thanks, This sloved my problem. Cheer !
