### ISSUE TITLE
Any function like "Preview mode" ?

### ISSUE THREAD

**Issue by l2aelba** [GetmeUK/ContentTools#337]
Since im using a bit custom like

```
// Start
editor.start();
editor.ignition().state('editing');
```

Any trick or function like **Preview mode**, That I tried something like
```
// Preview
editor.stop(true);
editor.ignition().state('cancel');
```

But this cannot undo (Undo tool) after I started the editor again _(When I edited something before going to preview-mode)_

Seems like all histories is gone.

**Comment by l2aelba** [comment]
Gotcha !

```
let editorPreviewHistory;
const ContentTools_Open = function() {
	editor.start();
	editor.ignition().state('editing');
	if(editorPreviewHistory) {
		editor.history = editorPreviewHistory;
	}
};
const ContentTools_Close = function() {
	editorPreviewHistory = editor.history;
	editor.stop(true);
	editor.ignition().state('cancel');
};
```

What you think ?

**Comment by anthonyjb** [comment]
@l2aelba - I think that's genius lol

**Comment by l2aelba** [comment]
So if you think all is good , im happy :D @anthonyjb Thanks

**Comment by l2aelba** [comment]
@anthonyjb I have to add `editor.history && editor.history.canUndo()` condition for preventing few bugs

**Comment by anthonyjb** [comment]
Thanks for updating the issue :+1:
