### ISSUE TITLE
upload file delay work

### ISSUE THREAD

**Issue by BruinY** [GetmeUK/ContentTools#341]
in windows 10 (IE, edge, chrome)
click upload image icon, open upload modal.
After clicking the upload button,Wait for a long time will have a response.Image upload speed is slow.
Want to ask what is the problem.Whether can improve?How to improve?

**Comment by anthonyjb** [comment]
I don't think this is ContentTools related issue. CT doesn't manage image uploads. Unless you suspect the delay is down to the code where ContentTools calls the ImageHandler function you have set up this isn't an issue I can look into.

**Comment by anthonyjb** [comment]
I'm assuming you set an image handler up and aren't relying on the default image upload code which is just an fake upload bar that progresses at a set rate until it's 100%?

**Comment by BruinY** [comment]
The mainest is click upload button, and takes a long time to react, let the user to choose photos

**Comment by anthonyjb** [comment]
How long is a long time? It's less than a second for me on Chrome. I don't believe this is CT related but if you can provide an reproducible example I'm happy to take a look.

**Comment by BruinY** [comment]
Chrome on my computer need to wait for about 5-8 seconds.The edge you need to wait for about 4 seconds.Ie11 less than a second.The operating system is Windows 10.
Chrome version 53

**Comment by BruinY** [comment]
I don't know whether I only on my computer.I tried several computers, waiting time, don't know how to optimize

**Comment by anthonyjb** [comment]
I don't believe this is CT related, it's just not something CT has any control over, especially across multiple browsers. The biggest problem is I can't replicate that behaviour on Chrome or Firefox so I can't even look for the bug.

Do you get the same issue when selecting the upload button on the demo page for the project e.g: getcontenttools.com/demo

**Comment by BruinY** [comment]
Operating on the demo page, appears as a chrome click upload button need to wait a few seconds to select the image

**Comment by BruinY** [comment]
@anthonyjb  

The default accept = "image / *" in chrome, 53 per click all need to wait a few seconds to open
Set to accept = "image/JPG, image/jpeg, image/PNG" just opened
