### ISSUE TITLE
Empty Node has no  Parent/Region on blur

### ISSUE THREAD

**Issue by Dortamur** [GetmeUK/ContentTools#342]
I'm trying to do some things to regions based on when elements gain or lose focus. For a start, I'd like to put a Class on the Region which has the focussed element.

What I'm currently trying is:

```javascript
         var root = ContentEdit.Root.get();
         root.bind('focus', function(el) {
            var region = el.closest((node)=> { return node.type() == 'Region' })
            region.domElement().classList.add('highlight')

         })
         root.bind('blur', function(el) {
            var region = el.closest((node)=> { return node.type() == 'Region' })
            region.domElement().classList.remove('highlight')
         })
```

This works fine when changing between elements which have content, but when "blur" is triggered for an empty/white-space element, the element is removed from the region before this blur event, and so it fails, and there's no way to determine which region just lost focus.

Is there any way to find that region that holds the element?

Thanks.

**Comment by anthonyjb** [comment]
Hi @Dortamur,

There's a few ways you could look to solve this I can think of, possibly the simplest I can think you might try is to set the parent region against the element whenever it's mounted and then access this on focus or blue, e.g:

```JavaScript
var root = ContentEdit.Root.get();
   
root.bind('mount', function(el) {
    el.stickyRegion = el.closest((node)=> { return node.type() == 'Region' });
});

root.bind('focus', function(el) {
    el.stickRegion.domElement().classList.add('highlight');
});

root.bind('blur', function(el) {
    el.stickRegion.domElement().classList.remove('highlight');
});
```
