### ISSUE TITLE
Disabling drag and drop option from an element

### ISSUE THREAD

**Issue by sahanjith** [GetmeUK/ContentTools#343]
Hi! i want to know is it possible to disable drag and drop option from an element ?

For example, i want an image to be pasted only to an area i reserved. once user inserted an image it should not be able to move from the place it pasted.

**Comment by anthonyjb** [comment]
Hi @sahanjith - yep you can disable behaviour against specific elements (here's a list of the behaviours you can configure: http://getcontenttools.com/api/content-edit#behaviours).

How you configure this behaviour is up to you, but for example you can set an attribute against elements you want to disable the drag behaviour for and then look for that tag when elements are mounted and disable the behaviour, e.g:

```html
<img data-no-drag src="...">
```

```JavaScript
ContentEdit.Root.get().bind('mount', function (element) {
    if (element.hasAttr('data-no-drag')) {
        element.can('drag', false);​​​​​
    }
});
```
