### ISSUE TITLE
Forcing a new snapshot

### ISSUE THREAD

**Issue by Moosheep** [GetmeUK/ContentTools#346]
I am using a bit of Jquery to dynamically insert an image into the middle of an editable region. It all works fine if, after the image in inserted, something on the page is edited (text, image, whatever) however if this does not happen, when the page is saved and reloaded, the image will not be there. 
I have had a look at the documentation and source code, and am well out of my depth!  From what I can deduce the problem lies in the fact that the process of dynamically inserting the image is not creating a new snapshot of the editable region and therefore when the save process is called ContentTools thinks that no changes have been made and so doesn't save anything.

Does this sound like the cause of the problem? If so is there any way that I can force a new snapshot to be taken once an image is dynamically inserted.

Many thanks

Jules

**Comment by anthonyjb** [comment]
Hi @Moosheep - yep this is almost certainly the case - though to be more precise basically the element you change needs to be flagged as tainted. You can do this by calling the `taint()` method against the editable element you inserted the image into.

I'm not sure how you are inserting the image but if the user selects the element then inserts the image (e.g if the image is inserted into the element that currently has focus) you can do:

```JavaScript
...inserts image...

ContentEdit.Root.get().focused().taint();
```

**Comment by Moosheep** [comment]
The image gets inserted after the selected element  $('.ce-element--focused').after(imgHtml), meaning that it does not have the focus and therefore ContentEdit.Root.get().focused().taint() is returning NULL;.  Can I taint() an element by class? or set the the focus prior to tainting?

Many many thanks for your help.

**Comment by anthonyjb** [comment]
You can't taint an element by class I'm afraid. You could use `bind` to record the last focused element:

```JavaScript
var lastFocusedElement;
ContentEdit.Root.get().bind('focus', function (element) {
    lastFocusedElement = element;
});
```

**Comment by Moosheep** [comment]
I failed to get things to work with taint() so changed my approach. After a crash course in ContentEdit I have come up with the following script:

    var image = new ContentEdit.Image({
    src:url, width:w, height:h
    });
    ContentEdit.Root.get().focused().parent().attach(image);
    image.focus();

This is working great in so much as the image is getting inserted and being saved, however I can only get it to insert at the bottom of the region. Is there a way of attaching the image to the focussed element rather than to the parent?

Thanks again

**Comment by anthonyjb** [comment]
You can attach the image after the current element, what your doing here is not attaching the image to the element but to the region, and by default attach adds the element you send it to the end. However you can send `attach` an index as the second argument, e.g `attach(image, 0)` would attach the image as the first element in the region. To attach the image after the current element then you'd need to find the index of the focused element in the region:

```JavaScript
var element = ContentEdit.Root.get().focused();
var region = element.parent();
var index = region.children.indexOf(element);
region.attach(image, index);
```

**Comment by Moosheep** [comment]
That works perfectly.
Thank you very much for your help.
