### ISSUE TITLE
Disallow new lines in region (disable return / 'Enter' key)

### ISSUE THREAD

**Issue by eightyfive** [GetmeUK/ContentTools#352]
Hi,

Thanks for the great library.

Is there a way to prevent user from inserting new paragraphs/lines/line-breaks in given Region?

I didn't find in Documentation. So here is a pretty simple use case:
```html
<div data-editable data-name="lang[pages/contact.title]" data-placeholder-type="h1">
    <h1 class="header__title">{{ trans('pages/contact.title') }}</h1>
</div>
```

I want to prevent user to add a new `<p>` in that region. Only `h1` node would be editable in that case.

Also, is there a way to "freeze" the region nodes, so user can only edit existing nodes but not add new ones:
```html
<div class="header" data-editable data-name="lang[pages/contact.header]">
    <h1 class="header__title">Sweeeet title...</h1>
    <p class="header__lead">Cool marketing lead text. BUY !</p>
</div>
```

This would allow user to edit `h1` and `p.header__lead` nodes only. Not add new ones, not delete, etc..

Am I using the library in the right way?

Thanks,
Ben

**Comment by anthonyjb** [comment]
Hi @eightyfive,

There's a couple of ways you can approach this, through [behaviours](http://getcontenttools.com/api/content-edit#behaviours) or [fixtures](http://getcontenttools.com/api/content-edit#fixture). For the examples you've given I think fixtures are probably what you want.

```
<h1 class="header__title" data-fixture data-name="lang[pages/contact.title]">
    {{ trans('pages/contact.title') }}
</h1>

<div class="header">
    <h1 class="header__title" data-fixture data-name="lang[pages/contact.header_title]>
        Sweeeet title...
    </h1>
    <p class="header__lead" data-fixture data-name="lang[pages/contact.header_lead]>
        Cool marketing lead text. BUY!
    </p>
</div>
```

There's a quick example here of how you can set up behaviours against different elements (or regions) https://github.com/GetmeUK/ContentTools/issues/343

Hope that helps :)

Ant

**Comment by eightyfive** [comment]
It sure does (help) !

Thanks a lot.
