### ISSUE TITLE
Can not insert image into table

### ISSUE THREAD

**Issue by bangtony** [GetmeUK/ContentTools#356]
Hi Anthony,

I am using getContentTool, It can not edit or add image into table
And I applied getContentTool for HTML as attached file, construct of table in HTML is changed.
I am looking at your code, but I am still not find the reason. Do you know this issue?

[getContentTool.zip](https://github.com/GetmeUK/ContentTools/files/616077/getContentTool.zip)

**Comment by anthonyjb** [comment]
The standard set of editable elements doesn't support images within tables (unless they are inline images, that is if the image is part of the HTML content of a `td` or `th` element, such images aren't managed as editable elements however just as characters in the HTML string).

**Comment by bangtony** [comment]
Thank you for your reply.

I also got other issue which the construct of table in HTML is changed when editing.
Step by step reproduce as below:
1. Run index.html in attached file (getContentTool.zip)
2. Click "Edit" icon
3. Click "Save" icon
Result: Construct of table in HTML is changed. You can see that on UI.

I am looking at your code, but I am still not find the reason. Could you please help me get reason?

**Comment by anthonyjb** [comment]
Hi @bangtony, so I think this is a similar issues, CT doesn't support nested tables in this way and will enforce a structure of `table > tbody > tr > td`

I'd recommend that you try making the contents of `td`s editable as individual regions within the table rather than trying to make the entire table structure editable in one section.

**Comment by bangtony** [comment]
Yes, I understood.

Thank you for your reply.
