### ISSUE TITLE
Click event cancelled on [data-editable] elements

### ISSUE THREAD

**Issue by eightyfive** [GetmeUK/ContentTools#357]
Why is the click event propagation cancelled/stopped on [data-editable] elements?

I'm trying know when a DOM element is being clicked (so when it is about to be "edited"...) and figured out that the click propagation is being cancelled when the Editor is active.

I'm sure there is a good reason, but how can I be notified when a [data-editable] DOM element is being clicked?

Is there a custom event for that? (Didn't find any in API doc)

Thanks a lot.

**Comment by anthonyjb** [comment]
Hi @eightyfive,

The `mouseDown` event is suppressed against empty elements that already have focus as a resolution to the following issue:  https://github.com/GetmeUK/ContentTools/issues/117

Other than that specific case I don't believe the click event is cancelled against elements, however given the behaviour you describe wanting to capture (when the element is about yo be edited) binding to the `focus` event for  might well work?

Having said that there's no click event for editable elements, you'd have to be capturing the event against the DOM element the editable element is managing, this is typically done by capturing the mount event and adding an event listenter to the the editable elements `.domElement().addEventListener('click', ...)`

**Comment by eightyfive** [comment]
I'm closing this one as you gave me hints in #358.

For reference, I wanted to update the toolbox state based on the type of the editable element being edited.

The key is to listen to the `focus` event on `ContentEdit`. This is what I was missing here (was trying to listen to the `click` event on the editable element, hence this issue...).

My specific problem was that I wanted to prevent the use of the toolbox when editing a `data-fixture` element. Here is my solution:
```js
ContentEdit.Root.get().bind('focus', function (element) {
  var isFixture = element.domElement().hasAttribute('data-fixture')

  if (isFixture) {
    editor.toolbox().hide()
  } else {
    editor.toolbox().show()
  }
})
```

_[ This solution is totally based on #173 ]_
