### ISSUE TITLE
Changing default tagNames of Heading and Subheading tools (Add receipe book?)

### ISSUE THREAD

**Issue by eightyfive** [GetmeUK/ContentTools#358]
Hi,

I've been struggling for a while doing something very simple in the end. I think that would be great to create a receipe book (github md) with simple hacks/common patterns.

For instance changing the heading tools default `tagNames` was pretty straight forward:
```
ContentTools.Tools.Heading.tagName = 'h2'
ContentTools.Tools.Subheading.tagName = 'h3'
```

But I had to dig into the source code for a while (coffee doesn't help when not used to it), tracking all the way down from `Editor.init()` method...

I would be glad to help/create/write the first couple of receipes. Maybe something very informal?

Receipes out of my head:
- How to disable 'Enter' / return line in editable elements? – A.k.a. `[data-fixtures]` (I had to ask on github for this one! I dug into the code for hours trying to achieve that, in the end, it is very straight forward)
- How to change default tag names of Heading tools?
- How to disable tools on-the-fly? (Didn't figured out this one yet, I wanted to disable all tools when `[data-fixture]` element is clicked/being edited)
- ...

**Comment by anthonyjb** [comment]
Hi @eightyfive - I agree there are a number of recurring questions that would be far better served in the form of a recipes/guides section of the website. I'll flag this as an enhancement and I'd be very happy to take submissions from pees :)

With regard to disabling tools on the fly you might find this issue helpful: https://github.com/GetmeUK/ContentTools/issues/173

**Comment by eightyfive** [comment]
Would you like me to write a raw MD document with simple recipes?

Should I contribute to this repository? Where?

**Comment by eightyfive** [comment]
By the way #173 totally did it!

My solution:
```js
ContentEdit.Root.get().bind('focus', function (element) {
  var isFixture = element.domElement().hasAttribute('data-fixture')

  if (isFixture) {
    editor.toolbox().hide()
  } else {
    editor.toolbox().show()
  }
})
```

**Comment by anthonyjb** [comment]
If you would like to post this as a pull request to a new top level directory in the project repo called `recipes` I'd be happy to accept it :+1:
