### ISSUE TITLE
apply event not firing

### ISSUE THREAD

**Issue by quiji** [GetmeUK/ContentTools#361]
Hi! I'm starting to work on CT for a project and I'm grateful for the work you have done with the editor. I'm new at this library and perhaps don't know how to use the events properly.

I'm trying to add behavior to a tool and, for some reason, can't get access to `_toolUIs['align-left']`. When I run the following console messages I get different objects:
```javascript
 var toolbox = editor.toolbox();
      console.log("editContent: toolbox", toolbox );
     // Got toolbox with _toolUIs and align-left object

      console.log("editContent: toolbox", toolbox._toolUIs );
     // Empty object with prototype

      console.log("editContent: toolbox", toolbox._toolUIs['align-left'] );
      // undefined
```

Maybe I'm setting the event in the wrong place? I'm working on AngularJs and I've been able to set stop, start, saved and revert events.

**Comment by anthonyjb** [comment]
Hi @quiji,

So the approach I'd recommend here is to listen for the event in the following way:

```JavaScript
editor.addEventListener('tool-apply', function(ev) {
    if (ev.detail().tool === ContentTools.Tools.AlignLeft) {
        ... do something here ...
    }
});
```

There's also a `tool-applied` event dispatched once the tool has been applied.

**Comment by quiji** [comment]
Thanks for the help! 

For some reason those events are not firing. Where is the right place to put that event? I just realized that when the editor is in dormant state, there are no tools in `_toolUIs`, so that explains why I couldn't access that property before.

**Comment by anthonyjb** [comment]
OK so I've just added the following code to my sandbox demo:

```JavaScript
    editor.addEventListener('tool-apply', function(ev) {
      console.log('test');
    });
```

And when I apply a tool (via the toolbox, but should work if applied using code also) I get `test` output in the console as expected? Can you try the same in your code and let me know if you the same output please.

**Comment by anthonyjb** [comment]
Sorry concerning where to put the code - anywhere really however, this is my code from the sandbox:

```JavaScript
    var editor = ContentTools.EditorApp.get();
    editor.init('[data-editable], [data-fixture]', 'data-name');

    editor.addEventListener('tool-apply', function(ev) {
      console.log('test', ev.detail().tool == ContentTools.Tools.AlignLeft);
    });
```

**Comment by quiji** [comment]
No, it doesn't show the `test` message. As I told you before, I created events for `start`, `stop` and `revert`with success.

**Comment by anthonyjb** [comment]
Just checking - are you using the latest release of the library? 1.3.1

**Comment by anthonyjb** [comment]
If you are and you still can't get it to work can you post your code so I can investigate further.

**Comment by quiji** [comment]
Sure, the version is 1.2.6 
```javascript
$scope.editor.addEventListener('start', function(ev)  {
      console.warn("start: Started editing...");

      var toolbox = $scope.editor.toolbox();

      console.log("editContent: toolbox", toolbox );
      console.log("editContent: toolbox._toolUIs", toolbox._toolUIs );
      console.log("editContent: toolbox._toolUIs['align-left']", toolbox._toolUIs['align-left'] );

      if (!toolbox._toolUIs['align-left']) return;

      toolbox._toolUIs['align-left'].addEventListener('apply', function(ev) {
          var element = ev.detail().element;
          console.log("tools - apply: About to apply align-left to ", element);
          if (element.type() == 'Image')
          {
            console.info("tools - apply: It's an image....");
            ev.preventDefault();
            element.removeCSSClass('align-right');
            element.removeCSSClass('align-center');
            element.addCSSClass('align-left');
            editor.toolbox().updateTools()
          }
      });
    });
```

I just noticed that the tools are created after the editor starts. So the console.log messages up there show the tools after I start the editor, stop it and start it again. Still couldn't make it work.

It's a lot of code, so let me see if I can dig further into it, if not I'll post it here thanks!

**Comment by anthonyjb** [comment]
The issue is the version - the new tool-apply and tool-applied events were introduced in version 1.3.0, I recommend upgrading to resolve the issue.

**Comment by quiji** [comment]
worked like a charm! 
Thanks!
I'm enjoying CT a lot :)
