### ISSUE TITLE
Validation and returning a failure?

### ISSUE THREAD

**Issue by joelmoss** [GetmeUK/ContentTools#365]
So we want to add validation on save, and when that fails, it should remain in an editable state with the changes intact, but not saved. But I can't figure out how. Can anyone help please? I am doing this validation in the `saved` event.

**Comment by anthonyjb** [comment]
Hi @joelmoss,

OK to do it from the `saved` event you will effectively need to manually start the editor again, along the lines of:

```
if (validationFailed) {
    // Manually start the editor
    editor.start();

    // Set the state of the ignition button to reflect that we've editing
    editor.ignition().state('editing');
}
``` 

If for some reason you need more control over this then you could look at capturing the `stop` event instead, manually collecting the contents of your regions and pre-validating them. If validation fails you'd then call `preventDefault` against that event which would cancel the stop request.
