### ISSUE TITLE
editor.start() won't update the buttons

### ISSUE THREAD

**Issue by Vinze** [GetmeUK/ContentTools#366]
I want to automatically start the editing mode and found issue #332 which suggests using `editor.start()`. I tried this but when calling this function the save and cancel buttons won't appear. Did I do something wrong or is it a bug?

See the following example: https://jsfiddle.net/2c42u89n/3/

**Comment by anthonyjb** [comment]
Hi @Vinze - no problem, you just need to set the state of the ignition button to match the editor state - e.g the ignition button drives the editor but not the other way around and so using your jsfiddle as a basis...

```JavaScript
// Start editing after 2 sec
setTimeout(function() {
    editor.start();
    editor.ignition().state('editing');
}, 2000);
```

**Comment by Vinze** [comment]
Great, thanks!
