### ISSUE TITLE
Shift button on demo doesn't work as described

### ISSUE THREAD

**Issue by geoidesic** [GetmeUK/ContentTools#367]
Using Chrome on Mac Yosemite... the text says "hold down shift and after a few seconds you'll see pulsing borders on editable elements"... that doesn't happen. http://getcontenttools.com/demo

**Comment by anthonyjb** [comment]
Hi @geoidesic - thanks I'll take a look into this.

**Comment by anthonyjb** [comment]
@geoidesic I've finally had chance to test this on Chrome / Mac Yosemite and it works as described and I'm unable to reproduce the issue. Closing for now but will happily reopen if someone can provide me with instructions to reproduce.
