### ISSUE TITLE
Add/Change image only section

### ISSUE THREAD

**Issue by akalonda** [GetmeUK/ContentTools#368]
First off, a brilliant library you have there. I use this library for a new project of mine.

Is there a way to make a div ‘data-editable’, but that the user can only add/change a picture in that div?
So in that div a user, cannot add text. Only change the image of the div. (but the user must also be able to add a hyperlink to that image).

Like a ‘data-editable-image’ tag would be neat.

**Comment by anthonyjb** [comment]
Hi @akalonda,

So there isn't a fixture type for images yet, as in you can have fixed regions for text currently using `Fixture`s but not images. However I once support is in place for replacing an existing image(#321) this will be possible.
