### ISSUE TITLE
Images In a row

### ISSUE THREAD

**Issue by HeroicMidge** [GetmeUK/ContentTools#37]
Is it possible to put images in a row? i.e side by side- Can't seem to do this at the moment.

**Comment by anthonyjb** [comment]
Yes this is absolutely possible, you can align images left of each other by dragging them over each other on the left hand edge which will display them in a row. However, by default the alignment will allow text to try and wrap around the images, so you'll end up with something akin to:

![image](https://cloud.githubusercontent.com/assets/3046287/10305009/7a75417a-6c15-11e5-95e7-2ab541f960d1.png)

Though you could fill the row - a better solution would potentially be to add a CSS class designed specifically for this which you apply to each image you want to appear in a row and that has a `:last-child` style to add an puedso `:after` element that will clear the last item.

If you wanted to center the images then this would be slightly more tricky as you'd ideally want to use a parent element to implement the center alignment - this would mean splitting a single editable region potentially into 3 regions, e.g.

    <div data-editable="upper">
        <p>Upper content</p>
    </div>
    <div data-editable="image-gallery" class="image-gallery">
        <img class="image-gallery__item" ...>
        <img class="image-gallery__item" ...>
    </div>
    <div data-editable="lower">
        <p>Lower content</p>
    </div>
