### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by rhedin** [GetmeUK/ContentTools#370]
Hi.  When I run the unit tests, most of them run, but two of them fail.

   ContentTools.ToolboxUI > Keyboard short-cuts
     ✓ should allow a non-content element to be removed with the delete key short-cut
     X should allow a undo to be triggered with Ctrl-z key short-cut
       Expected spy canApply to have been called. (1)
     X should allow a redo to be triggered with Ctrl-Shift-z key short-cut
       Expected spy canApply to have been called. (1)

I found the place in src/scripts/toolbox.coffee where the operating system was sniffed for, and I thought I knew how to fix it.  I put this code into src/spec/toolbox.coffee. 

            console.log('Adjusted by Rick.  On Mac, has to be metaKey, not ctrlKey.');
            # keyDownEvent.ctrlKey = true
            keyDownEvent.metaKey = true

But not only did it not fix it, my console log didn't display.  Plainly, me solving the problem is inefficient. 

           Regards, 
           Rick

**Comment by anthonyjb** [comment]
Hi @rhedin - I'm unable to reproduce this error in my set up (though I did notice I'm getting a bunch of unwanted console logs). Can I confirm what version of CT your working with?

**Comment by rhedin** [comment]
ckeditor_4.6.1_standard

Sorry to be slow to respond, Anthony.  I've been sick. 

If it can't be reproduced, oh well.  Let it go. 

        Rick

**Comment by anthonyjb** [comment]
Hi Rick, nothing to apologise for - hope you are feeling better now! Ant
