### ISSUE TITLE
Tooltip/label timeout

### ISSUE THREAD

**Issue by mpatelj** [GetmeUK/ContentTools#371]
Is it possible to change the default timeout for the toolbar labels.  It takes too long for the tooltips to show up; around 3 seconds.

**Comment by anthonyjb** [comment]
Hi @mpatelj,

Yes - the simplest option is to change the `transition-delay` here (currently 2 seconds): https://github.com/GetmeUK/ContentTools/blob/8e69ab23bbbc62d9f1cb2d6181377264d3b013e5/src/styles/_settings.scss#L74 and recompiling the SASS.

**Comment by mpatelj** [comment]
Thanks for prompt reply.
