### ISSUE TITLE
ContentTools inserts extra div before editable elements

### ISSUE THREAD

**Issue by vivex** [GetmeUK/ContentTools#375]
![screenshot from 2017-01-22 15 07 53](https://cloud.githubusercontent.com/assets/5036512/22181541/9eb3b6f6-e0b4-11e6-9045-6e0fb441e342.png)

In Edit mode contentTools is inserting an div before editable elements, which is causing style/css related issue in edit mode. 

Any workaround for this?

**Comment by anthonyjb** [comment]
Hi @vivex,

Unfortunately the inner div is required to allow the content to be editable and to support sub-list items (`<li>`s). If memory serves me correctly they are also required as one or other browser (possibly IE) doesn't allow `li` and `td` elements to be converted to `contenteditable` standalone (i.e they can be editable but only as a child of an editable element - but don't quote me on that).

Can you provide an example of the CSS that is that conflicting with this layout and I'll see if I can propose a workaround?

**Comment by vivex** [comment]
CSS Selector was `.navbar-lg .navbar-nav > li > a`   , But ContentToolJS have inserted one more div just before div, so this css selector is not working.

**Comment by anthonyjb** [comment]
Hi @vivex,

So the simple solution if it's possible is to not use `li > a` and use `li a` if that's possible to change?

--

We use the BEM for CSS (actually you can see it's used in CT) which avoids the type of CSS selector you've defined above. There's lots of strategies for CSS and BEM works for us but not for everyone, however if you get 30 minutes today I'd definitely recommend this article http://cssguidelin.es/

**Comment by vivex** [comment]
I could have use this but these classes are defined in bootstrap lib: https://github.com/twbs/bootstrap/blob/v3.3.0/dist/css/bootstrap.css#L3939


I tried removing those extra div added by contentTool by following code:

```
 var editableDivs = body.find("div.ce-element ");
          editableDivs.each(function() {
            var classes = $(this).attr('class');
            var content = $(this).contents();
            var parent = $(this).parent();
            $(this).remove();
            console.log('contents', content);
            content.addClass(classes);
            content.attr('contenteditable', '');
            parent.append(content);
          });

```

and it working fine till now,  is it good approach ?

**Comment by anthonyjb** [comment]
@vivex does that save the content correctly on save still?

**Comment by vivex** [comment]
@anthonyjb  no i havnt tried saving yet, i was just trying out contentTools, will check saving and update here.

**Comment by anthonyjb** [comment]
I don't think that will work for saving as the structure is required/expected by CT/CE. 

I'd recommend changing the CSS as the simpler approach, it's a minor change to your bootstap CSS and shouldn't cause any issues unless you have sub-navigation.
