### ISSUE TITLE
Select first element on start

### ISSUE THREAD

**Issue by doglesby** [GetmeUK/ContentTools#378]
Hello,

Is there a way, using js, to activate the first element in the container (so the cursor shows up) after calling editor.start(). I would like to avoid the user have to click 2 times to edit the text.

Thanks!

David

**Comment by anthonyjb** [comment]
Hi @doglesby - sure, there's no started event so you need to patch the `editor.start` method but it's not too bad.

```JavaScript

    var editorCls = ContentTools.EditorApp.getCls();
    var superStart = editorCls.prototype.start;

    editorCls.prototype.start = function () {
      superStart.call(this);

      // Find the first region on the page
      var region = editor.orderedRegions()[0];

      // Find the first text element on the page
      element = region.nextWithTest(function (node) { return node.type() === 'Text' });

      // Give the element focus
      element.focus();

      // Set the selection at the start of the element's content
      new ContentSelect.Range(0, 0).select(element.domElement());
    }

```

**Comment by doglesby** [comment]
Thanks, works great!

**Comment by doglesby** [comment]
Hi,

Quick (I hope) follow-up question. For some reason that I have not figured out yet, when I use editor.start() and then save the changes and try to edit again, I get a parentNode is null error message. However, if I use editor.ignition().state('editing') instead, everything works great. But..., then the patch you provided to put the cursor in the first element no longer gets called because I am not calling editor.start. Is there a way I can trigger this function to run when the state changes to editing instead of start?

Anyway, thanks for any help you can provide. Still trying to wrap my head around the inner workings of this tool, as I am customizing a bit to work with my project.

**Comment by anthonyjb** [comment]
Hi @doglesby - any chance you can send me the version of your code as I can't determine the cause of the issue from your description.

If you trigger the editor starting using the ignition then you still basically call the `start` method so the modification we made should still get called. Also you should be able to successfully save the changes using `editor.stop(true)` (this will call save and trigger `save` and `saved` events) and then use `start` to edit the page again so something odd is going on - would be good to review your code if possible.

**Comment by doglesby** [comment]
Thanks for the reply and help. I'm very impressed with the library and how responsive you are.

I apologize in advanced for the long post, but I want to try and explain what I'm trying to do in detail to hopefully make it easier to see what is going on. One note about my previous post. Since I last posted the question, I have been trying many different things to try and fix the issue. I have come to the conclusion, that using editor.start() may be a better route then using editor.ignition().state('editing'). I just wanted to point that out so it doesn't look like that is missing in the code. Also, because of this, this post is now a little off topic.

So, let me try and explain what I'm trying to do and then I will follow up with some code. 

**What I am trying to do:**
I am setting up a page that will allow the user to edit only a certain area of the site at one time. I have created my own edit button for each area. When the user clicks to edit a particular area, I lock the rest of the page and show my own save and cancel buttons for that area.

**What is happening**
When I click to edit a container, everything works great. It goes straight to edit mode and the cursor shows (I added an additional function, shown below in the code, to move the cursor to the end of the container instead of the beginning). 

If I cancel this edit, again everything appears to work correctly. I can continue to edit and cancel any container and everything works great.

Now, when I try and save, some weird things start to happen. The first time I go to edit mode and save, everything works fine. If I try and save again (for the same or any other container), everything again works, but I do get a "Busy" alert message. Then, if I try and save one more time, I will again get a "Busy" alert, but this time an error occurs (this.history is null).
  
**The Code**
//CSS - Because I have my own edit and save buttons I hide some items and edit others
.ct-ignition { display: none !important; }
.ct-inspector { display:none !important; }
.ce-element--focused, .ce-element--over { background-color: transparent !important; outline: none !important; }
.ct-anchored-dialog__target-button {display:none !important;}

//Setup global variables
var editor;

//Page Load Setup
function PageSetup()
{
      var editorCls = ContentTools.EditorApp.getCls();
      var superStart = editorCls.prototype.start;
      editorCls.prototype.start = function () {
            superStart.call(this);
            // Find the first region on the page
            var region = editor.orderedRegions()[0];
            // Find the first text element on the page
            element = region.nextWithTest(function (node) { return node.type() === 'Text' });
            // Give the element focus
            element.focus();
            // Set the selection at the start of the element's content
            new ContentSelect.Range(0, 0).select(element.domElement());
            //function that puts the cursor at the end. Let me know if you need or want to see this and I can post seperately
            cursorManager.setEndOfContenteditable(element.domElement());
      }
}

//Edit Activated Function
function Edit()
{
      editor = ContentTools.EditorApp.get();
      editor.addEventListener('saved', function (ev) {
            EditSave(myVars, ev, editor);
      });
      editor.addEventListener('stop', function (ev) {
            ev.preventDefault(); // Prevent save
           ev.stopImmediatePropagation(); // Prevent save
           this.history.stopWatching();
           this.history = null;
           this._toolbox.hide();
           this._inspector.hide();
           this._regions = {};
           this._state = 'ready';
      });
      editor.init('*[data-editable]', 'myUniqueIDOfItemBeingEdited');
      editor.start();
}

//Cancel Action
function EditCancel()
{
      editor.revert();
      editor.stop(false);
      editor.destroy();
}

function EditSave()
{
      //Run Save Script
      //Close Editor
      editor.stop(false);
      editor.destroy();
}

Sorry again for the long post. Let me know if I can clarify anything else.

Thanks!

**Comment by anthonyjb** [comment]
Hi @doglesby - so the behaviour your describing sounds like the save/saving handlers are being called multiple times because they are not unbound.

When you destroy the editor you remove it from the DOM but that doesn't itself remove existing event bindings you have against the editor - which perhaps it should do - however to test the theory can you change your code as follows:


```JavaScript
function EditCancel()
{
      editor.revert();
      editor.stop(false);
      editor.destroy();
      editor.removeEventListener();
}

function EditSave()
{
      //Run Save Script
      //Close Editor
      editor.stop(false);
      editor.destroy();
      editor.removeEventListener();
}
```

This will ensure any event bindings for the editor are removed (with `removeEventListener`) and so should I hope prevent the behaviour you are describing.

**Comment by doglesby** [comment]
That fixed it. Thanks for all your help!
