### ISSUE TITLE
Update region with any external DOM changes in table

### ISSUE THREAD

**Issue by evromalarkey** [GetmeUK/ContentTools#381]
Hello, is there any way to update regions, so when I force changing the text via JS it gets saved?

http://getcontenttools.com/demo eg. here in the demo, I change the text via browser inspector (not with the editor) and the change doesn't get saved.

I've tried adding editor.syncRegions() before saving but that is not working, did I miss something?

I have script that sums numbers in cell inside table (table is wrapped as region), but once I alter the html with my script, the result in table that I've appended doesn't get saved.

Any help appreciated!

**Comment by evromalarkey** [comment]
or is there any way to find existing tableCell I need and insert custom value into it? Let's say I know the ID of the cell in the DOM, how do I find it and replace the content with my new value? I've spent whole day in the documentation etc. and didn't find the way to do it. I'm kind of lost now

**Comment by anthonyjb** [comment]
Hi @evromalarkey,

So yes to both approaches, but in both cases you'll need to find the table cell(s) being updated so lets start there. I'm going to assume you could find the `td` elements in question using an Id but it would be relatively easy to update my code to handle some other way:

```JavaScript
function findNodeById(id) {
    // Return an editable node by its Id

    // Search each region
    var editor = ContentTools.EditorApp.get();
    var regions = editor.orderedRegions();
    for (var i = 0; i < regions.length; i++) {
        // Attempt to find a child node with the given Id
        var node = regions[i].nextWithTest(
            function (node) {return node.attr('id') === id});

        // If we found a matching child node return it
        if (node) { return node;}
    }
}
```

So using our new `findNodeById` function **Approach 1 (syncing)** becomes:

```JavaScript
var td = findNodeById('some-id');

// Trigger a content sync for the element
td.tableCellText()._syncContent();
```

Or using **Approach 2 (direct update)** we can do:

```JavaScript
var td = findNodeById('some-id');

// Update the elements content
td.tableCellText().content = new HTMLString.String('some-value');

// Update the DOM to reflect the change
td.tableCellText().updateInnerHTML();

// Flag that the element has been tainted/modified
td.tableCellText().taint();
```

Though slightly longer **Approach 2** is what I'd recommend as it's uses all public methods.

Hope that helps you out.

**Comment by evromalarkey** [comment]
That helps a lot thanks! It's working for me with the ID, but now let's say I don't know ID, can I test it also as tagName? eg.

`return node.tagName('tfoot') === id`
`tfoot.tableSection()._syncContent();`

would that work in relation to approach 1?

The thing is it has to be plain table, so I only know that my appended value is in tfoot in last td (or I need to add it there) and I guess that it could be tricky to access something so deep in the table without id.

Would be possible for example to sync the whole table, regardless if there were changes in the DOM or not?

**Comment by anthonyjb** [comment]
Hi @evromalarkey you could write a function to sync the whole table (or the whole anything really), for example (not tested):

```JavaScript
function syncAllContent(element) {
    // Sync the content of any supporting element (including its child elements)

    // If the elements support content syncing then sync the content
    if (element._syncContent) {
        element._syncContent(); 
    }

    // Does this element have children? If so sync them.
    if (element.children) {
        for (var i = 0; i < element.children; i++) {
            // Recursive call (stack approach may be better)
            syncAllContent(element.children[i]);
        }
    }
}
```

**Comment by evromalarkey** [comment]
Thanks a lot, worked nicely! There was only missing .length in the foreach. Btw the element should be the parent region right? eg. ContentTools.EditorApp.get().regions()['wsw']

**Comment by anthonyjb** [comment]
Hi @evromalarkey it should work either way, if you send it the parent element or the specific element.

**Comment by evromalarkey** [comment]
Ok, thanks once again for the help!
