### ISSUE TITLE
imageuploader.fileready fires twice in IE11

### ISSUE THREAD

**Issue by Trinitonn** [GetmeUK/ContentTools#385]
Just noticed that the variable "file":
`var file = ev.detail().file;`
is returning null first, and secondly the correct data.

Check this fiddle in IE11:
http://jsfiddle.net/lmeurs/2rEzF/

And:
https://github.com/facebook/react/issues/8793

IE bug?

**Comment by anthonyjb** [comment]
Thanks for the report @Trinitonn - I'll test on later versions of IE (Edge) and confirm if it's still a problem. If it's an IE 11 issue only I will probably document but not attempt to patch for it.

**Comment by ErixSoleil** [comment]
It seems to come from the chanve event when this value is changed - > ev.target.value = '';
I've comment this line and the event isn't triggering twice anymore. I had the same issue.

ImageDialog.prototype._addDOMEventListeners = function() {
      ImageDialog.__super__._addDOMEventListeners.call(this);
      this._domInput.addEventListener('change', (function(_this) {
        return function(ev) {
          var file;
          file = ev.target.files[0];
		  // ed change was triggering event twice
          //ev.target.value = '';
          if (ev.target.value) {
            ev.target.type = 'text';
            ev.target.type = 'file';
          }
          return _this.dispatchEvent(_this.createEvent('imageuploader.fileready', {
            file: file
          }));
        };
      })(this));
