### ISSUE TITLE
Insert problem

### ISSUE THREAD

**Issue by Tiseanu** [GetmeUK/ContentTools#386]
Hello,

After I press the Insert button, I see that in the edit zone, appears the default image : image.png , not the one that I've uploaded on the server.

var ImageUploader;

  ImageUploader = (function() {
    ImageUploader.imagePath = 'image.png';

How can I put here my uploaded file? am I doing smth wrong?

Thank you very much,
Tiseanu

**Comment by anthonyjb** [comment]
Hi @Tiseanu - you need to implement your own image handler, there's advice on how to do this is the following tutorials:

- http://getcontenttools.com/tutorials/handling-image-uploads
- http://getcontenttools.com/tutorials/image-uploads-with-cloudinary
