### ISSUE TITLE
Problem with keyboard shortcuts - multilanguage

### ISSUE THREAD

**Issue by deartify** [GetmeUK/ContentTools#390]
Hello
I have problem with keyboard shortcut. When I'm pressing right Alt+"z" which inserts polish sign "ż" it works as undo.
How can I disable this shortcut?

Btw thx for this great tool

Update:
I have found solution. Unicode 90 for me is "Z" and 89 is "Y". When i change this to 121 "y" and 122 "z" everything works.
around 6445 in content-tools.js
`case 'windows':
              if (ev.keyCode === 121 && ev.ctrlKey) {
                redo = true;
              }
              if (ev.keyCode === 122 && ev.ctrlKey) {
                undo = true;
              }`

**Comment by anthonyjb** [comment]
@deartify thanks for the update - I guess we should really make these key combos configurable so that they can be easily updated for different language requirements.
