### ISSUE TITLE
Unable to see image after upload

### ISSUE THREAD

**Issue by dirkjacobs** [GetmeUK/ContentTools#394]
Trying to integrate ContentTools in an Angular app.
When trying to add an Image, the upload dialog opens, I can select a file, but the uploaded file doesn't become visible

can't see any error or info in the console

Any suggestion ?

D.

**Comment by dirkjacobs** [comment]
Already found part of the reason. Seems I installed a new version and the event-binding has changed.
bind( xx.fileReady ) > addEventListener(xx.fileready) : events are no longer camel-case

**Comment by anthonyjb** [comment]
Yeah the event system got a complete overhaul in release 1.2.0 are you still having issues, can you provide an example of you code?
