### ISSUE TITLE
Add alternative text field to image dialog

### ISSUE THREAD

**Issue by kaliel86** [GetmeUK/ContentTools#400]
Hello, i would like to know if you plan to add the possibility of filling a 'alt' attributes for images as it is better for seo and accessibility.

I'll try some PR but i'm not confortable with coffee :)

Thanks for your great work.

**Comment by anthonyjb** [comment]
@kaliel86 you can already do this :) When you have an image selected simply select the image tag in the inspector bar and add the 'alt' attribute within the dialog that appears.

Ant

**Comment by kaliel86** [comment]
oh, didn't see that inspector bar feature yet, sorry. That's perfect !
