### ISSUE TITLE
detach() or detatch() ?

### ISSUE THREAD

**Issue by damienflament** [GetmeUK/ContentTools#404]
The [current documentation about the ComponentUI](http://getcontenttools.com/api/content-tools#component-ui) mention a _detach()_ method. But this method [is called _deta**t**ch_ in the source code](https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/ui.coffee#L59) and [in the specification](https://github.com/GetmeUK/ContentTools/blob/master/src/spec/ui/ui.coffee#L98) also.

**Comment by anthonyjb** [comment]
@damienflament should be `detach` - misspelled in the source - I'll upload a patch early this week -ty :+1:

**Comment by damienflament** [comment]
Isn't it a source of serrious bugs ? Even if you're not aware of them ?

**Comment by anthonyjb** [comment]
@damienflament the `detatch\detach` method isn't called in the ContentTools libraries, though other external libraries may use it. 

The patch I implement will retain the existing `detatch` method with a warning recommendation output in the console to switch to the correct `detach` method by the next minor update. This will mean the change has no impact on existing projects and the version change will be a patch 1.3.2 -> 1.3.3.

I don't consider this a serious bug as the modification will be backwards compatible and the existing `detatch` will remain until the next minor update (`major.minor.patch`).
