### ISSUE TITLE
Official Safari support?

### ISSUE THREAD

**Issue by jpodwys** [GetmeUK/ContentTools#406]
From reading ContentTools' documentation, I see this sentence:

> The current aim is for all the libraries to support IE9+, Chrome and Firefox.

I'm trying to pick an editor and I really like the feature set ContentTools provides. Can you tell me if the above statement from the docs is the latest list of officially supported browsers? In specific, I'm wondering if ContentTools has official support for desktop Safari.

Thank you!

**Comment by anthonyjb** [comment]
Hi @jpodwys actually that needs to be updated, currently we aim to support IE Edge, Chrome and FireFox. Safari is likely to work (given the webkit engine) and I would be happy to fix issues flagged bu Safari users but it's not part of our testing in-house.

**Comment by jpodwys** [comment]
Thank you for your response!
