### ISSUE TITLE
Extending to edit the css of the element?

### ISSUE THREAD

**Issue by KriiV** [GetmeUK/ContentTools#407]
Hi! 
Love the project. 
I'm building a form of website builder and would like to use ContentTools, do you have any advice on how I could go about editing the html elements further just like a website editor but via content tools?

Thanks

**Comment by anthonyjb** [comment]
Hi @KriiV, to extend the editable elements you need to spend some time reviewing the API docs and source code for ContentEdit:

- http://getcontenttools.com/api/content-edit
- https://github.com/GetmeUK/ContentEdit/tree/master/src/scripts

It's not overly difficult to support new types of element but a good understanding of the ContentEdit library is a prerequisite.

**Comment by KriiV** [comment]
Perfect. Appreciate your time taken to reply :)
