### ISSUE TITLE
I want to add uzbek language

### ISSUE THREAD

**Issue by ruslanmedia** [GetmeUK/ContentTools#409]
Can you add uzbek language file? It's translated by me.

[uz.json.zip](https://github.com/GetmeUK/ContentTools/files/949473/uz.json.zip)

**Comment by anthonyjb** [comment]
Hi @ruslanmedia - thanks for this I'll add it to the project this week. :+1:

**Comment by ruslanmedia** [comment]
Can I commit uzbek language to your project?

**Comment by anthonyjb** [comment]
@ruslanmedia just to quickly thank you again for the translation, it's in the next release planned for tomorrow. If you wish to contribute changes to the project in future you can submit pull requests to do this :+1:
