### ISSUE TITLE
Request for highlighting and deleting multiple lines.

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#41]
Right now you cannot highlight multiple paragraphs, or multiple items on a bullet or numbered list. This makes it hard to edit them.

I understand that this may be the case because of how CT structures the editable content into different elements, but from a user's point of view selecting across multiple lines might be needed.

This is not of a high priority though, just a convenience feature.

**Comment by anthonyjb** [comment]
This question is related to issue #11.

**Comment by MalyshevDmitry** [comment]
Amazing!

**Comment by bfintal** [comment]
Now that I've dug deeper into the code, I don't think this is at all possible.

**Comment by anthonyjb** [comment]
@bfintal agreed - the approach ContentTools takes makes this very difficult to achieve without making changes to the approach itself.

**Comment by bfintal** [comment]
Let's not tackle this :)

**Comment by iamryandrake** [comment]
@anthonyjb Thoughts on the above statement? ^

**Comment by anthonyjb** [comment]
Hi @iamryandrake,

You can't select / give focus to multiple items in a list, when you mouse over you may see 2 levels of highlight (where the list item and parent list(s) you're hovering over are selected) but that's not the same thing.
