### ISSUE TITLE
Login Panel to edit

### ISSUE THREAD

**Issue by smileyblonde1** [GetmeUK/ContentTools#411]
Hi there,

Is it possible to add a login panel to edit the content? It seems the edit function is always there, however I’m looking for only particular admins to edit the content not the users previewing the website?

Is this even possible?

Thanks

**Comment by anthonyjb** [comment]
Hi @smileyblonde1 - ContentTools provides is a client-side library, as such it has no scope to provide authentication, that's the role of the your CMS. There's some examples off different approaches to integrating content tools with a CMS here: http://getcontenttools.com/tutorials/content-tools-plus-cms
