### ISSUE TITLE
Identify DOM element by class

### ISSUE THREAD

**Issue by simonmannsfeld** [GetmeUK/ContentTools#412]
My intention is to add the bootstrap grid as elements to the Tool shelf. Here we got three divs with another class: .container .row, and .col's.

How can I decide between them?

**Comment by anthonyjb** [comment]
@simonmannsfeld if I understand your question then you typically add a tag type data attribute to the element, for example:

```
<div class="container" data-ce-tag="container">
    <div class="row" data-ce-tag="row">
        <div class="col" data-ce-tag="col">
        </div>
    </div>
</div>
```

(Worth having a read through the section on tag names: http://getcontenttools.com/api/content-edit#tag-names)
