### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by kallekanin** [GetmeUK/ContentTools#414]
I get the error: "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

When i click "Upload" button, after selecting a image.

Does anyone know what might be wrong?

**Comment by anthonyjb** [comment]
@kallekanin the image uploader is expecting a JSON payload back - my guess is you're not returning that from your server side script.

**Comment by kallekanin** [comment]
I run this: console.log(file); and that gives me a JSON, but that JSON is not valid (tested in JSONLint).

**Comment by anthonyjb** [comment]
Hi @kallekanin, CT's ImageUploader example class doesn't itself attempt to create and parse JSON, it only parses JSON that is returned to it from a call to the server. I'm not sure what `console.log(file)` is in reference to here?

**Comment by kallekanin** [comment]
I am using the code found on the homepage for this ( http://getcontenttools.com/tutorials/handling-image-uploads ), but the script gives me an error, does i need to modify/add more to it for work?

I just added console log to see if there was a JSON available, and checked that for errors. Is there somthing more that needs to be done for the script to work?

**Comment by kallekanin** [comment]
file uploaded to server, but i still get: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data.

**Comment by kallekanin** [comment]
Seams like the JSON format from the callback is formated wrong, even tho the file is uploaded to the server, it wount return valid JSON.

Select image -> upload to server -> error -> image is not visible in the frame.

**Comment by anthonyjb** [comment]
@kallekanin if the server isn't returning valid JSON then that needs to be resolved but that's beyond the scope of CT. I'll happily take a look at your server code if you post it and see if I can spot the issue but keep in mind I don't know what language or framework your using so I might be of limited help.

**Comment by kallekanin** [comment]
The image are uploaded but it wont show in the editing window (added screenshot)

JS code that trigger uploadscript:

```
$.getJSON('save.php', 'test', function(e){
	console.log(e);
});
```
save.php:

```
<?php
	move_uploaded_file($_FILES['image']['tmp_name'],"images/".$_FILES['image']['name']);
?>
```
![screenshot_1](https://user-images.githubusercontent.com/28596222/27780644-706ea914-5fca-11e7-9fa3-6bb2437b4d02.JPG)

Gives me this message in browser: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data (  editor.js:128:28 )
