### ISSUE TITLE
Do the indent/unindent buttons do anything?

### ISSUE THREAD

**Issue by tofsjonas** [GetmeUK/ContentTools#419]
I've been able to unindent a list, but that's it. I have never seen the indent-button enabled.

Lovely thingy apart from that. :-)

**Comment by anthonyjb** [comment]
Hi @tofsjonas,

You should be able to indent any item within a list provided there is more than one item in the list and you are not trying to indent the first item. If this isn't the case perhaps this is a bug, could you please provide the steps to reproduce along with information about which browser you are using?

**Comment by tofsjonas** [comment]
That was the information I was looking for. I didn't realize it was for lists only.

Thank you for taking the time to answer. :-)
