### ISSUE TITLE
ContentTools.EditorApp.get().destroy is insufficient

### ISSUE THREAD

**Issue by uncaught** [GetmeUK/ContentTools#423]
After noticing that my save-callback was triggered multiple times after a series of re-initializing the editor app, I've investigated and found that the destroy-method is not cleaning up everything.

The `_children` array is not cleaned up and none of the children are properly destroyed. Furthermore the `_bindings` are not cleaned, either.

This solved the problem for me, maybe you can implement this change in the code:

```
    editor._children.forEach((child) => child.unmount && child.unmount());
    editor._children = [];
    editor._bindings = [];
    editor.destroy();
```

Thank you

**Comment by anthonyjb** [comment]
Hi @uncaught - thank for flagging this I'll provide fix this week :+1:
