### ISSUE TITLE
Question: Is it required to unbind events on Destroy

### ISSUE THREAD

**Issue by mallikarjuna909** [GetmeUK/ContentTools#425]
Hi,
Is it required to unbind events on Destroy like `ContentEdit.Root.get().unbind('paste', this._handleClipboardPaste)`  on `_EditorApp.prototype.destroy` ?

Thanks.

**Comment by mallikarjuna909** [comment]
Hi,
I think it is required because some event handlers are being called several times if we don't  unbind events.  As per this [comment](https://github.com/GetmeUK/ContentTools/issues/378#issuecomment-277313580) i got "when you destroy the editor you remove it from the DOM but that doesn't itself remove existing event bindings you have against the editor". 

Please correct me and confirm, so that i can close this question.

**Comment by anthonyjb** [comment]
Hi @mallikarjuna909,

If you bind events to the ContentEdit element Root element then you will need to also unbind these before you re-apply them (e.g through listening to the editor start event etc).

Ant

**Comment by mallikarjuna909** [comment]
Hi @anthonyjb 

Thanks for your kind reply. My doubt is clarified. Hence closed.
