### ISSUE TITLE
Make the inspector better

### ISSUE THREAD

**Issue by b2550** [GetmeUK/ContentTools#426]
I wanted to add special styles to links (so I can make a button) but the <a> element does not show up in the inspector toolbar breadcrumb thing when editing. I don't know how difficult it would be to make this work (because I assume you must need some trickery to find out if your cursor/selection is on an <a> element only) but I thought that making a button tool for the toolshelf was more complicated then I needed to do.

**Comment by b2550** [comment]
I also need to be able to apply styles to container elements so being able to set the base level to the primary `[data-editable]` container. Right now I have no way to effectively make colored containers (I would also like image-based backgrounds but that probably would require a new tool).

**Comment by anthonyjb** [comment]
@b2550 these are really 2 different requests. 

In answer to the first one at the moment there's no plan to support inline elements (tags within the contents of text based elements) in the inspector bar, however you're not the first to mention it and I can see the appeal for some scenarios - most of the time for I tend to either add a tool for specific cases, or to explain to users (who are comfortable with HTML) that they can use the code area of the properties dialog when inspecting the parent element.

As for the second one this is coming very soon, we have a prototype extension to ContentTools call ContentFlow which we will be releasing and which allows you to dynamically build/manage the regions within a page, including support for configuring those regions (it does require additional configuration on the server side).
