### ISSUE TITLE
Custom and Embeded (Question)

### ISSUE THREAD

**Issue by tabuna** [GetmeUK/ContentTools#446]
I want to know two things:

- Can this editor embed "Embed" entries like "gist.github.com"?
- Can I change the appearance without resorting to dirty hacks?

_Thank you for your work._

**Comment by anthonyjb** [comment]
Hi @tabuna,

Short answer:

- Yes
- Yes

Slightly longer answer:

- Yes, the simplest way would be to insert them as static elements, if you want to be able to do this via the editor you'd need to write a tool to support the service you wanted to insert content for (e.g gist) or a general purpose insert static content tool (neither or which is a huge challenge).
- Yes, the easiest way is to modify the CSS, however ContentTools itself is just a base editor with a small UI library, many people have used it as a basis for their own editors but fundamentally changed all of the UI (for example https://en-gb.wordpress.org/plugins/page-builder-sandwich/).

**Comment by tabuna** [comment]
Thanks, I'll let you know if I have any new questions
