### ISSUE TITLE
Feature request: move paragraphs with drag & drop

### ISSUE THREAD

**Issue by blocknotes** [GetmeUK/ContentTools#453]
Hi - great component :)
I'm working on a Ruby on Rails plugin to use it as front-end content editor.

It would be nice to be able to reorder paragraphs using drag & drop (for example with an icon on the left of a row, outside the editing region).
Or if you can provide some info to make a Tool to move up / move down the current paragraph (better if in plain JS), it would be great.

**Comment by anthonyjb** [comment]
Hi @blocknotes - this functionality is already supported :)

To move a paragraph click and hold for a second or 2 until the drag helper appears. In addition you can move list items and table rows this way, and if you hold longer on lists or tables you can move the entire list or table.

**Comment by darksnake747** [comment]
Hey Anthony. I love this tool set. Great work! And I see you closed this, but following your instructions, I cannot seem to get tables, rows, lists, or paragraphs to work like that with drag and drop. Would be great... but all I can get to do that are images. Any thuoghts why?
