### ISSUE TITLE
Broken characters when it's in spanish

### ISSUE THREAD

**Issue by igdamico** [GetmeUK/ContentTools#459]
Every character that has an accent on load are broken.

Example: 
original: ECONOMÍA
on edition mode: ECONOMÃA.

í = Ã
á = Ã¡
ñ= Ã±

*Original text are in spanish

**Comment by anthonyjb** [comment]
@igdamico I'm not able to repeat this issue using the editor, are you able to repeat it on the demo page: http://getcontenttools.com/demo?

To test I basically inserted the 'ECONOMÍA' content into the page (using the inspector) then clicked the edit button - all worked as expected. This looks like an encoding issue but without more detail or access to an example it's difficult to pinpoint - though at this point I don't think it's an issue related to CT (happy to be proved wrong though).

**Comment by anthonyjb** [comment]
I've also just tested in a live site that I can edit content with the characters you've mentioned and I don't see the same issue.

**Comment by igdamico** [comment]
Hi anthonyjb, thanks for the very fast answer.

in demo works but it's not the same because i just had text with accents in my "data-editable" div before using the editor.

**Comment by igdamico** [comment]
this is my html that works perfect without the editor.
https://jsfiddle.net/0bac3nfb/

**Comment by igdamico** [comment]
don't worry! i add in the header
```
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
```
and now it's working! 

thanks fo the advice!
