### ISSUE TITLE
Request: ContentEdit Drag & Drop events

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#46]
I think these would be a great addition :+1:

**Comment by MalyshevDmitry** [comment]
:+1:

**Comment by anthonyjb** [comment]
I agree these would be useful additions, happy to add. So the new events will be:

- `drag`
- `drop` (only executed if content is successfully dropped on another element that accepts the drop action)

Does that offer everything needed?

**Comment by bfintal** [comment]
How about when the drop is performed in the same place?

**Comment by anthonyjb** [comment]
If it's dropped on the the element above, below, left, right in such a way as to stay in the same position on the page the `drop` event would still trigger, but it would be easy to check if it had moved by reviewing the element (if any) before it.

**Comment by anthonyjb** [comment]
Just updating the documentation for the additional events now - but feel free to use:

    ContentEdit.Root.get().bind('drag', function (element) { ... });
    ContentEdit.Root.get().bind('drop', function (element, target, placement) { ... });

**Comment by MalyshevDmitry** [comment]
You're really fast! Thank you!

**Comment by bfintal** [comment]
Thank you!

**Comment by bfintal** [comment]
Oh, and the docs in the site are already updated too :+1:

**Comment by bfintal** [comment]
Okay so I tried the new events. The drop event isn't getting triggered when the drag is cancelled - e.g. you drag it to the same place. I think it should still get triggered, since if you do something during the drag event, you can't perform the next part during the drop event since it isn't called.

Maybe you can add a `cancelled` boolean property to the object.

**Comment by anthonyjb** [comment]
Yeah drop only trigger if the element was dropped on another valid element, I could modify the call so that the `target` and `placement` values for the event are null if there is no valid target?

**Comment by anthonyjb** [comment]
@bfintal OK you should now get an event valid or invalid - hope that helps and removes the need for the workaround :)

**Comment by bfintal** [comment]
Super thanks yet again! :+1:
