### ISSUE TITLE
no image gallery?

### ISSUE THREAD

**Issue by absoluto** [GetmeUK/ContentTools#460]
title says it all. isn't there an image gallery or slideshow module? would be VERY helpful and close to reality...

**Comment by anthonyjb** [comment]
@absoluto that's not the role of ContentTools, this is something you add using ContentFlow as a snippet type typically. It's absolutely possible to build galleries, carousels, form builders, etc. using ContentFlow. 

You might think of it as ContentFlow controlling the page layout (the stack of content snippets that make up the page), and ContentTools allowing you to edit the content as a whole.

Right now ContentFlow is in it's early stages and therefore whilst it's available it really should be considered experimental (I have a set of changes to push for it this weekend - it's still changing a lot at the moment).

There's a couple of videos for ContentFlow which give you an idea of what it will do and I plan more before the end of the year:

- https://www.youtube.com/watch?v=HQaNrI3yJwo&t=24s
- https://www.youtube.com/watch?v=p8oAct-RW_0&t=11s (this is a preview of our upcoming CMS that features ContentFlow)

So right now ContentFlow probably isn't in a position where you can start using it in your own projects (unless you're prepared to get very in-depth with the source code) but come the new year I'm confident there will be sufficient documentation and examples that it might be more viable for you.

Hope that's of some help (if not a solution) Ant
