### ISSUE TITLE
Adding/Removing Rows/Columns in Tables?

### ISSUE THREAD

**Issue by cmangen** [GetmeUK/ContentTools#464]
How do I can add or remove a specific row or column in a ContentTools created table?

Thank you very much

**Comment by anthonyjb** [comment]
@cmangen you can't remove a specific column, you can change the number of columns by selecting the table tool in the toolbox when a cell in the table is focused. You can however remove a row by holiding down shift and selecting the delete icon in the toolbox, this will delete the row for the currently selected table cell.

**Comment by cmangen** [comment]
@anthonyjb Thank you very much for the explanation. This helps already a lot.
