### ISSUE TITLE
New cell after preformatted.

### ISSUE THREAD

**Issue by nsfnd** [GetmeUK/ContentTools#476]
Enter and Shift+Enter both will create a new line inside a preformatted cell.

Cant figure out howt to create new cell after preformatted.

Thanks.

**Comment by anthonyjb** [comment]
Hold down Ctrl and select the paragraph tool from the toolbox.

**Comment by nsfnd** [comment]
Oh wow, thanks a lot!
That was a waste of half hour but no matter.

Again thanks for your brilliant work.
