### ISSUE TITLE
Question: View raw HTML

### ISSUE THREAD

**Issue by bananenklops** [GetmeUK/ContentTools#477]
Is there a way or a workaround to toggle between raw and formatted HTML for the whole editable area like you can in the CKEditor?

**Comment by etal2** [comment]
There is no built-in support for raw html editing. Personally I added a tool which opens a dialog and integrated codemirror for html editing. It's part of a larger commercial project but I can separate out the relevant code if you want to use it.

**Comment by anthonyjb** [comment]
@bananenklops - @etal2 is correct, the editor doesn't provide an editor for the HTML it generates. 

You can change the HTML within some elements you edit (such as `li`, `p`, `pre`, `td`) using the tag bar (bottom left) and the code tab in the properties box.

**Comment by bananenklops** [comment]
@etal2 thank you for your reply. I would like to view the code of your solution.

**Comment by etal2** [comment]
Code uploaded to https://github.com/etal2/ContentTools-Codemirror

**Comment by ShalomR** [comment]
This sounds handy! Could I see a screen shot of how this looks in action by any chance? :D

**Comment by etal2** [comment]
Added screenshot although it's just a text editor in a dialog box nothing fancy.
