### ISSUE TITLE
Grunt build error

### ISSUE THREAD

**Issue by fernandofranca** [GetmeUK/ContentTools#48]
After an `npm install` I'm getting this error while trying to build with the provided Grunt file.

```
$ grunt build
Running "coffee:build" (coffee) task
>> 1 files created.

Running "sass:build" (sass) task
OptionParser::NeedlessArgument: needless argument: --sourcemap=none
  Use --trace for backtrace.
Warning: Exited with error code 1 Use --force to continue.

Aborted due to warnings.
```

**Comment by fernandofranca** [comment]
To keep it from crashing due Sass, I've just removed the step from the build array:
```
    # Tasks
    grunt.registerTask 'build', [
        'coffee:build'
        'concat:build'
        'uglify:build'
        'clean:build'
    ]
```

**Comment by anthonyjb** [comment]
Hi @fernandofranca the issue is your version of SASS, I've had the same problem in the past, I recommend you update SASS to the latest version, I'm running `Sass 3.4.18 (Selective Steve)` currently.

**Comment by fernandofranca** [comment]
Sure!
I'm with `Sass 3.3.0.rc.4 (Maptastic Maple)`. 
Updating right now.
Thanks, @anthonyjb !

**Comment by anthonyjb** [comment]
No problem - can you confirm that fixes just to be sure :)

**Comment by fernandofranca** [comment]
Done!
It was my outdated Sass tool.

**Comment by anthonyjb** [comment]
Thanks for confirming :+1:

**Comment by fernandofranca** [comment]
Thanks for your help!!!
