### ISSUE TITLE
can't add directly to ready webpage

### ISSUE THREAD

**Issue by shubhamtropicalcluster** [GetmeUK/ContentTools#486]
API of contenttool is not working on ready sites we need to recreate the program & and there is problem in saving the file using .js file

**Comment by anthonyjb** [comment]
@shubhamtropicalcluster it sounds like you're having a problem getting set up. There's lots of people who may be able to help you including myself but this type of bug report is completely meaningless. You must provide a detailed description of the issue you're having along with examples of the code for anyone to be able to help you.
