### ISSUE TITLE
Mistakes in tutorial for "Adding new tools"

### ISSUE THREAD

**Issue by fernandofranca** [GetmeUK/ContentTools#49]
I don't know if I should report this here, but there it goes:

Where it reads: 
- `@getDatetime(element, selection) ->` should be `@getDatetime: (element, selection) ->`
- `ContentTools.DEFAULT_SETTINGS[0].push('time')` should be `ContentTools.DEFAULT_TOOLS[0].push('time')`

**Comment by anthonyjb** [comment]
Hi @fernandofranca reporting here is fine - thanks for the info will resolve now :)

**Comment by anthonyjb** [comment]
Fixed :)
