### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Marekx3** [GetmeUK/ContentTools#498]
in this line of the event listener fileready
response = JSON.parse(ev.target.responseText);
i get a exception
Uncaught SyntaxError: Unexpected token < in JSON at position 0
Why? its copied from your tutorial.

**Comment by anthonyjb** [comment]
My guess would be that your response from the server you're uploading your file to isn't valid JSON.
