### ISSUE TITLE
Possibility to init the EditorApp with a DOMElement instead of a query

### ISSUE THREAD

**Issue by daanvanham** [GetmeUK/ContentTools#51]
I think it would be a great enhancement to also allow people to enter a DOMElement instead of only a query selector as the first parameter of the EditorApp.prototype.init function. In most cases people (like me) already have the element at hand at time of initiating the editor.

**Comment by anthonyjb** [comment]
Agreed :+1:

**Comment by anthonyjb** [comment]
Just updating the documentation for this now but basically you can now do the following, either:

    // Init with a CSS query
    editor.init('[data-editable]', 'data-editable');

...or...

    // Init with a list of DOM elements
    editor.init([regionA, ...], 'data-editable');

**Comment by daanvanham** [comment]
Thanks! Was trying to fix it myself for a PR, but ran into some trouble with CoffeeScript and Grunt, both not really my favourites... :)

**Comment by anthonyjb** [comment]
No problem, glad I could help :)
