### ISSUE TITLE
Minor issue with a spurious "Leave page" warning

### ISSUE THREAD

**Issue by cyclaero** [GetmeUK/ContentTools#510]
Please may I suggest to change line 9056 of `content-tools.js` from:

    if (_this._state === 'editing' && ContentTools.CANCEL_MESSAGE) {

to:

     if (_this._state === 'editing' && _this.history && _this.history._snapshotIndex && ContentTools.CANCEL_MESSAGE) {

This would fix the problem that I sometimes see the "Leave page" warning when the editor has been started, and nothing has been touched, though, and I leave the page. With this in place, the warning appears only if really something has been edited.

**Comment by anthonyjb** [comment]
Hey @cyclaero thank makes a lot of sense thanks for the suggestion.

**Comment by anthonyjb** [comment]
@cyclaero just wanted to thank you for raising this issue and submitting the relevant changes. The code has been pushed now and will be in the next release (later this evening).
