### ISSUE TITLE
Impossible to turn list to paragraph back (ul or ol to p)

### ISSUE THREAD

**Issue by anastasiauz** [GetmeUK/ContentTools#519]
On Demo page it's stated "Pre-formatted blocks of text can be converted back to standard text using the paragraph tool".
We can turn P to H and then H to P back, for ex. 
But it's impossible to turn a list (Ul or OL) back to paragraph (P). While focusing a LI press P on tool box - it creates new paragraph after the list. Is that a bug? Now the only way to format list back to paragraph is to delete it and add it again as a paragraph.

Also it will be cool to be able or delete a table completely - with a button in TableDialog. Now it can be done only by deleting rows, row by row. 

Thank you for an awesome plugin!

**Comment by anthonyjb** [comment]
Hi @anastasiauz, so you can turn `pre` blocks back to paragraph tags using the paragraph tool - to turn a list back to a paragraph it works more like a word processor you need to use the outdent tool, simply outdent the list item until it becomes a paragraph (the short cut is shift + tab).

Ant

**Comment by anthonyjb** [comment]
Hi @anastasiauz forgot to mention you can delete an entire table by holding down the ctrl key when clicking the delete tool :)
