### ISSUE TITLE
Request: Restricted dragging & dropping

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#52]
Sample use-case: I created a row element and column elements which can only reside inside the rows. I've allowed dragging and dropping of the columns so you can move them from side to side. I think this **may** be a good feature to add. 

I restricted the dragging to be just inside the same parent, but I think it should be extended to be a customizable restriction, not just to the same parent. This is how I did it for reference:

    DivCol.prototype._onMouseOver = function(ev) {
		DivCol.__super__._onMouseOver.call(this, ev);

		var dragging, root;
		root = ContentEdit.Root.get();
		dragging = root.dragging();

		if ( dragging !== null && this.parent() !== dragging.parent() ) {
		    this._removeCSSClass('ce-element--drop');
		    return root._dropTarget = null;
		}

	};

Perhaps it would be better to have an `Element.prototype.canDragInto` or something that would return a boolean (always true by default), then elements can just override it and customize the condition.

**Comment by anthonyjb** [comment]
I agree this is a good idea :) I'm wondering if the logic would be better moved to `_onDragOver/_onDragOut` method (called from `_onMouseOver/_onMouseOut` to separate the behaviour being customized) that you can then override for custom elements, calling the parent for the default behaviour and then applying any custom behaviour as above in the overridden method?

**Comment by anthonyjb** [comment]
@bfintal ok you could now achieve this through behaviours by overriding the `can` method (details here: http://getcontenttools.com/api/content-edit#behaviours), for example:

```JavaScript
DivCol.prototype.can = function(behaviour, allowed) {
    var result = DivCol.__super__.can.call(this, behaviour, allowed);
    if (behaviour === 'drop' && result) {     
        return this.parent() === ContentEdit.Root.get().dragging().parent();
    }
    return result;
};
```
