### ISSUE TITLE
Make Bold to able to remove <strong> tags

### ISSUE THREAD

**Issue by jnnkB** [GetmeUK/ContentTools#533]
I think this really would be helpful if you edit HTML files that use `<strong>` instead of `<b>`.

**Comment by anthonyjb** [comment]
@jnnkB I'm not sure what the request is here sorry, however, you can easily change the base tag generated by the bold tool if you need ro, for example:

    ContentTools.Tools.Bold.tagName = 'strong'

This would switch the bold tool from using `b` currently to use `strong`. This doesn't effect the native browser behaviour for modifier (e.g ctrl) + b though.
