### ISSUE TITLE
Request: PreText Return & Tab behavior

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#54]
1. When I have a PreText element, I need to hit the return key twice in order to go to the next line - as if the first return press didn't do anything.
2. It would be great if the tab key inserted a tab (or 4 spaces) for indenting pre-code. I tried doing this for a PR but I can't get it to work, somewhere there's an `\n` inserting itself and prevents be from going back to the content using arrow keys.
3. In-line with 2., if the line is indented with a tab, it would be cool if hitting the return key would also implement the same indentation on the next new line.

**Comment by anthonyjb** [comment]
@bfintal believe a fix for the issues you mentioned here are now in place, I'm moving the enhancement suggestions to a separate issue so they can be discussed further.
