### ISSUE TITLE
Fix for tiny toolbox bug

### ISSUE THREAD

**Issue by Candielope** [GetmeUK/ContentTools#541]
Hi again!
I noticed that sometimes when tried to click on the Heading element it would select lists instead. It was really annoying. Then I realized since I have a translated version and my tooltips are a bit longer and breaking into two lines, it sometimes covers the other buttons before they are visible.

**Here are some screenshots:**
Without fix, hitting the tooltip selects the toolstips element:
<img width="174" alt="Skjermbilde 2019-07-08 kl  22 18 14" src="https://user-images.githubusercontent.com/6409712/60840238-581b5800-a1cf-11e9-87ad-d22af7616f8d.png">

After fix, selecting through the tooltip.
<img width="178" alt="Skjermbilde 2019-07-08 kl  22 18 40" src="https://user-images.githubusercontent.com/6409712/60840240-581b5800-a1cf-11e9-89f4-6c756fa44be2.png">

A small fix for this is to add pointer-events: none; to the tooltips:after element :) Hope this can be in the next patch as well for others who might not have figured out why. I also added some styling to stop the wordbreak.

```
.ct-tool:after {
     pointer-events: none;

     width: initial;
     max-width: 150px;
     white-space: nowrap;
}
```

**Comment by anthonyjb** [comment]
@Candielope thank you for the report and taking the time to offer a solution :+1:

**Comment by anthonyjb** [comment]
@Candielope just wanted to thank you again for the report and suggestion this fix has been pushed and will be in the next release.
