### ISSUE TITLE
Support for tab key in pre-text elements

### ISSUE THREAD

**Issue by anthonyjb** [GetmeUK/ContentTools#55]
These enhancements were originally suggested by @bfintal in issue #54, they have been separated out as issue #54 also contained a bug report.

1. It would be great if the tab key inserted a tab (or 4 spaces) for indenting pre-code.
2. If the line is indented with a tab, it would be cool if hitting the return key would also implement the same indentation on the next new line.

---

**I agree that both of these suggestions would be useful enhancements**

**Quick question:** How should we define what is inserted on pressing the tab key? We could insert a tab (perhaps the expected behaviour), or insert whatever is defined in the `ContentEdit.INDENT` setting (I'm leaning towards this option), or we could have another setting specifically for pre-text indents, for example `ContentTools.PRE_INDENT`.

**Comment by bfintal** [comment]
I would agree about using the existing INDENT property so we won't have to add another one.

**Comment by anthonyjb** [comment]
This is now in place (at least it's ready for testing in the wild).
