### ISSUE TITLE
Crop Not Working

### ISSUE THREAD

**Issue by chud37** [GetmeUK/ContentTools#552]
I can't move the crop marks to crop the image in the image uploader. 

According to the [documentation](http://getcontenttools.com/tutorials/handling-image-uploads), There is nothing I need to do to set this up, it should work correctly.

I'm using the latest version of Chrome.

See the image for reference: [https://www.pastefile.com/6YSem1](https://www.pastefile.com/6YSem1) - The blue dots don't allow me to drag them whatsoever.

Any help would be appreciated.

**Comment by anthonyjb** [comment]
Hi @chud37,

Thanks for the report.

- Can you send me any error information within the console that  is being reported. 
- Can you send me the response you're sending back when an image is uploaded to the image upload handler.
- Can you test the demo page on the website and see if you get the same issue.

I'm using the latest version of chrome and the demo page is working for me - most likely this a problem in the size value you are returning from the server but no guarantees so let me know how you get on with that above and we'll go from there.

**Comment by chud37** [comment]
Hello Anthony, 

I'm so sorry - I missed the box that described the size array and I was simply passing filesize.

Thank you so much for your quick response and help.  I'd also like to say thank you for ContentTools, I've tried a multitude of WYSIWYG Editors and ContentTools has come out on top - Being open source and usability its just great.

(I did find the tutorials a bit confusing to work through though)

I've also modified it slightly so that the toolbar and the edit buttons are static in the page, and not draggable, it would have been nice if that was included as an option (i may have missed it, judging by my history with the size array!)

Anyway thanks once again, this can be closed.

**Comment by anthonyjb** [comment]
@chud37 no problem at all - glad I could help.

There isn't an option for the side bar to be made static but I agree that would be a nice option in a future release, and it something a number of people have (like you), implemented themselves. I think the option to drag the toolbox to the edge and have it attach statically would be really nice.

Sorry you found the tutorials confusing, image uploads in particular I find difficult to explain, if you have suggestions for sections you found less helpful I'd be grateful for the feedback so I can improve them moving forward.
