### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by FuXual** [GetmeUK/ContentTools#555]
I don't really know if anyone has asked about this before, which is to me really strange. I know there is a version for mobile, and i have used it. Though it seems like the continues work is on the "desktop version". It's great to see that you (yesterday) have made changes to the project. Im glad of that, but I was a bit surprised that the mobile changes were not present in this one. Are you planning to make it more mobile friendly in the near future or what is your thoughts on that? Thank you very much for this piece of software! Very usefull and good looking (on desktop ;p)!

**Comment by anthonyjb** [comment]
@FuXual mobile support for ContentTools was added under a fork by the talented @cubiclesoft at https://github.com/cubiclesoft/ContentTools.

We have never had a demand from clients to provide mobile/tablet support for ContentTools, the content it generates must support being responsive of course but the editing UI has always been designed with the desktop audience in mind.

Enough developers have requested that we add a responsive editing environment to CT that this will be a feature of CT 2.0, but it is now unlikely to be something we retrospectively add to this version of CT.
