### ISSUE TITLE
Class gets lost on edit of link

### ISSUE THREAD

**Issue by jnnkB** [GetmeUK/ContentTools#557]
I recently discoverd, that if I have a link with a certain class and I change the link or make it external, the class gets lost. Is this intended behavior?

**Comment by anthonyjb** [comment]
Can you provide an example please.

**Comment by jnnkB** [comment]
I created a tool to upload files like PDF's and create a link for them. The link looks like this:
```html
<a class="uploaded-file" href="/url/of/file.pdf">Name of File</a>
```
If I than edit the link by making it external, the class disappears. Unfortunately this breaks my website because I use the class to than check which documents can be deleted and which I have to keep and because the class is missing the document gets deleted.

**Comment by tokpl** [comment]
https://github.com/GetmeUK/ContentTools/blob/master/build/content-tools.js#L9740

You must change these liens

FROM

`          if (detail.href) {
            a = new HTMLString.Tag('a', detail);
            element.content = element.content.format(from, to, a);
            element.content.optimize();
          }`

TO

```

          if (detail.href) {
            a = new HTMLString.Tag('a', detail);
            a.attr("class",$(".ct--pseudo-select").parent().attr("class"))
            element.content = element.content.format(from, to, a);
            element.content.optimize();
          }
```

**Comment by anthonyjb** [comment]
This issue is addressed in the latest release: https://github.com/GetmeUK/ContentTools/releases/tag/1.6.13

**Comment by anthonyjb** [comment]
@tokpl thanks for pointing me at the code that needed addressing, I took a different approach but it was really helpful to have a starting point.

@jnnkB thanks fort the error report.
