### ISSUE TITLE
data-name should not have to be unique

### ISSUE THREAD

**Issue by Shannanigans** [GetmeUK/ContentTools#56]
I recently used ContentTools to build a dynamic site template builder. In this case I needed to use a compound key. So using multiple attributes to uniquely identify an editable area. Which meant I required regions to be populated with duplicate data-name elements. Why not return duplicates and let the implementing developer decide how to deal with it? 

I solved the issue by changing the editor initialisation to:
editor.init('*[data-editable]');

Not sure if this is the best solution. I am receiving all editable elements instead of just those that have been edited.

**Comment by anthonyjb** [comment]
Hi @Shannanigans I'm not sure I fully understand the issue you're describing, but yes `editor.init('*[data-editable]')` is a perfectly acceptable mechanism for selecting all editable content on the page.

As for unique data names often what I do is create my editable regions like so:

    <main data-editable="article-body">
        ...
    </main>
    <main data-editable="aside">
        ...
    </main>

And to select them I use the following initialisation params:

    editor.init('[data-editable]', 'data-editable');

As for dynamic unique keys - I'm currently working on an extension to the library which has a similar problem in that I don't have a key to hand at the point the region is defined (it's dynamic), my current solution is just to generate one on the fly, e.g `region-1`, `region-2`, `region-x`. This allows the data returned to be mapped specifically to an element in the DOM. What I could look to do is automatically create unique Id's for regions that don't have them in this way? For example `data-ct-id="1"` (or against whatever attribute has been specified as the naming property).

As for compound keys at the moment I'd recommend using JavaScript to update the DOM before the editor is initialized to convert your compound keys into unique Ids from, for example for the following HTML:

    <div data-editable data-key-a="1" data-key-b="1">
        ...
    </div>
    <div data-editable data-key-a="1" data-key-b="2">
        ...
    </div>

You could use something along the lines of:

    var domRegions = document.querySelectorAll('[data-editable]');
    for (var i = 0; i < domRegions.length; i++) {
        var domRegion = domRegions[i];
        domRegion.setAttribute(
            'data-compound-key',
            domRegion.getAttribute('data-key-a') + '-' + domRegion.getAttribute('data-key-b')
        )
    }

    editor.init('[data-editable]', 'data-compound-key');
    
Alternatively I could simply return a list of HTML strings against editable regions with duplicate keys - but I think we'd need a good use case to promote this behaviour and I'd probably prefer to implement automatic Ids.

I hope that's helpful, appreciate your feedback and interest in CT, I apologise if I haven't fully understood the question but I'm happy to revisit if you can shed some more light on the your specific case.

**Comment by Shannanigans** [comment]
Hi @anthonyjb 

Thanks for the quick response. I had issues with editable main regions because of divs within divs. 

I ended up coming right. I have sections of html in a database that can be treated as templates or as an instance. So the section has a unique id and every editable child element has a unique id within that section. In doing so I can "print" out the same section multiple times and still be able to edit each editable segment.

One thing that I still find frustrating is that the post object contains all editable data instead of just the segments that have been edited. Is this an implementation issue on my side?

By the way I came across this typo here.
http://getcontenttools.com/tutorials/handling-image-uploads
size: reponse.size,

**Comment by anthonyjb** [comment]
Hi @Shannanigans, thanks for pointing out the typo I've updated the docs :+1: 

The output of all regions isn't an implementation issue your end it's a bug my end :( - looking at the code there's no check to see if a region has a `lastModified` date. I'll mark this issue as a bug now and get that fixed.

**Comment by anthonyjb** [comment]
@Shannanigans OK that should now be resolved please let me know if you have any further problems with the save output :)

**Comment by Shannanigans** [comment]
Awesome, very cool of you to get to it so quickly.
