### ISSUE TITLE
Issues in IE 10 & 11 

### ISSUE THREAD

**Issue by doonetheprune** [GetmeUK/ContentTools#57]
The toolbox does not close when you save your changes in IE 10 & 11.The below error is the output from the demo page.

> SCRIPT65535: Unexpected call to method or property access.
> File: content-tools.js, Line: 4, Column: 3440

It appears IE does not like this line
```javascript
this._domElement.blur();
```
To overcome the error I initially changed it to ... 

```javascript
if(this._domElement.blur){
     this._domElement.blur();
}
```
...which allows the changes to be saved.

However when you go to edit the HTML for a second time you get the below error when you click inside anything editable.

>Unexpected call to method or property access.

The error is caused by the ```javascript this._domElement.blur(); ``` again

**Comment by anthonyjb** [comment]
Hi @doonetheprune thanks very much for the error report. It appears IE doesn't allow the `blur` method to be called using JavaScript against a `<div>` tag even if it's `contenteditable`. To resolve this I've put a try catch statement around the `blur` call with an explanation of why it's acceptable to ignore the error raised in this case.

**Comment by doonetheprune** [comment]
That works

Thanks
