### ISSUE TITLE
Convert dragging indicators into pseudo elements

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#58]
The up/down/left/right arrows that show up when dragging are currently background images. If your content has an existing background image, or when you maybe have a full sized image in the content, the arrows become hard to see and in some cases you won't see them at all.

If we convert the dragging indicators to be a pseudo element instead with:
```position: absolute;
top: 0;
left: 0;
right: 0;
bottom: 0;
opacity: .4;
background-color: #123456;
background-image: url(...);
z-index: 9999;
pointer-events: none;```
Then we can display the indicators on top of the elements. By adding `pointer-events: none;` we can still retain the mouse events on the elements too.

**Comment by anthonyjb** [comment]
This is a good idea but `pointer-events` are only supported in IE11 (http://caniuse.com/#feat=pointer-events), no IE9 or 10 support so we'd need a fall back for these.

Would be happy to look at a PR for this, I'd also love it if we could find some way to show the arrows without using images if I could remove them (and convert the video icon to a font icon) the library would be image free using only the font.

**Comment by bfintal** [comment]
On second thought I don't think we need `pointer-events: none` since you're still hovering over the same element, so the events will be all fired fine.

So I think this can be a matter of changing from the `background-image` into a pseudo element.

**Comment by bfintal** [comment]
Just tested this and it works:

	.ce-element--drop-below {
		position: relative;
		z-index: 1;
		&:before {
			position: absolute;
			content: '';
			top: 0;
			right: 0;
			left: 0;
			bottom: 0;
			z-index: 2;
			background: url(../inc/content-tools/images/ce-drop-below.png);
			background-color: rgba(25, 181, 254,1);
			opacity: .8;
		}
	}

I also tried a pure css approach but it was quite messy:

	.ce-element--drop-below {
		position: relative;
		z-index: 1;
		&:before {
			position: absolute;
			content: '';
			top: 0;
			right: 0;
			left: 0;
			bottom: 0;
			z-index: 2;
			background: -webkit-repeating-linear-gradient(45deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%), -webkit-repeating-linear-gradient(-225deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%), -webkit-repeating-linear-gradient(45deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%), -webkit-repeating-linear-gradient(-225deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%);
			background: -moz-repeating-linear-gradient(45deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%), -moz-repeating-linear-gradient(315deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%), -moz-repeating-linear-gradient(45deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%), -moz-repeating-linear-gradient(315deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%);
			background: repeating-linear-gradient(45deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%), repeating-linear-gradient(315deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%), repeating-linear-gradient(45deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%), repeating-linear-gradient(315deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 90%, rgba(255,255,255,1) 91%, rgba(255,255,255,1) 100%);
			background-color: rgba(25, 181, 254,1);
			background-position: 9px 9px, 9px 9px, 36px 36px, 36px 36px;
			-webkit-background-origin: padding-box;
			background-origin: padding-box;
			-webkit-background-clip: border-box;
			background-clip: border-box;
			-webkit-background-size: 50px 50px;
			background-size: 50px 50px;
			opacity: .8;
		}
	}

I used http://enjoycss.com/ to generate the pattern. If it's that messy though, might as well just base64 encode the image if you want it free from external assets.

**Comment by bfintal** [comment]
In the PR, I've removed also the force removal of backgrounds in tables since the background of the element isn't touched any more.
