### ISSUE TITLE
The image uploader

### ISSUE THREAD

**Issue by Minh2003** [GetmeUK/ContentTools#580]
I'm currently following this tutorial [Handling upload image](https://getcontenttools.com/tutorials/handling-image-uploads) to implement the image uploader. I have trouble with the last step, the docs said I must have to apply this line `ContentTools.IMAGE_UPLOADER = imageUploader;` into my code. But I don't know where to put this line in my code. My code refers to this post [#246 ](url). Could you show me where the line I can put my code? Thanks.

**Comment by john3parker** [comment]
Hello,
I've implemented ContentTools image uploading successfully. After you've included ContentTools, start your own <script> block and you can immediately add the code for ContentTools.IMAGE_UPLOADER. If ContentTools isn't loaded you'll get a javascript error.

**Comment by Minh2003** [comment]
Hey, I've found the problem. thanks for your help
