### ISSUE TITLE
Change color of Text

### ISSUE THREAD

**Issue by StefanTD** [GetmeUK/ContentTools#59]
Really nice work!
Is it possible to change the color of the text - without predefined properties?

**Comment by anthonyjb** [comment]
Hi @StefanTD and thanks :+1: 

There's no colour select/set tool in the base editor application, others have added support for such tools, @bfintal has integrated the WordPress colour picker for example, but it's not part of the standard tools.

My personal opinion (for what it's worth) is that CSS styles keep things consistent and easy to change globally through CSS where as colour pickers, font selectors and such tools prevent this. 

Having said that I can imagine that potentially there are instances where picking a colour from a palette - for example being able to set the background colour of a splash to something custom - is useful.
