### ISSUE TITLE
Q: Does it support custom handlers of events like 'click on image', 'click on link'?

### ISSUE THREAD

**Issue by MalyshevDmitry** [GetmeUK/ContentTools#6]
ContentTools is amazing! Thank you!

Does it support custom handlers of events like 'click on image', 'click on link'? I would like to show additional context menu when user clicked on image or link. Is it possible with actual API?

It may look like:
![08118724375a98009a6477f4e736bd95](https://cloud.githubusercontent.com/assets/1517140/9913629/83c6b678-5cb6-11e5-9034-642b9ceff48a.gif)

**Comment by MalyshevDmitry** [comment]
@anthonyjb I've added gif to show case.

**Comment by anthonyjb** [comment]
Yes (well sort of) - there is already a behaviour defined for the the click event against an image so you'd be changing that behaviour in essence. There are a couple of ways to do that you can either monkey patch the classes directly:

    # Override the specific behaviour
    ContentEdit.Image._onMouseDown = (ev) ->
        ...Perform my custom behaviour...

    # Change the DOM event bindings
    ContentEdit.Image._addDOMEventListeners = () ->
       
        @_domElement.addEventListener 'click', (ev) =>
            ...Perform my custom behaviour...

Alternatively you could inherit from the Image class and create a new class to override the behaviours:

    class MyImage extends ContentEdit.Image
        
        ...override the _onMouseDown or _addDOMEventListeners methods here...

    # Register your new class as the default class to use for images
    ContentEdit.TagNames.get().register(MyImage, 'img')

Finally you could potentially add custom events via the root node like so:

    # Capture node being mounted in the DOM event
    ContentEdit.Root().bind 'mount', (node) ->
        
        # Check the node is an image
        if node.constructor.name != 'Image'
            return

        node.domElement().addEventListener 'click', (ev) ->
            ...Perform my custom behaviour...

**Comment by MalyshevDmitry** [comment]
@anthonyjb Thanks! Will try.

**Comment by anthonyjb** [comment]
@MalyshevDmitry Let me know how you get on - this is bound to be something others want to do so if there's no an easy way potentially this is something I need to improve on.

**Comment by bfintal** [comment]
Interested in this as well.

**Comment by Pandahisham** [comment]
following
