### ISSUE TITLE
Command/Ctrl deleting whole multiple paragraph texts retains the content

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#65]
To replicate:
1. Create 2 paragraphs each with a line of text,
2. Put your cursor at the end of the last paragraph,
3. Command + delete (Ctrl + backspace in Windows) until the line is erased, keep going until the cursor moves to the previous paragraph.

Expected Result: Cursor moves to the previous paragraph with the last paragraph deleted.

What I got: Cursor moves to the previous paragraph with the last paragraph deleted, but the original contents were appended to the cursor location.

**Comment by anthonyjb** [comment]
@rosstarran I can't replicate this on Ubuntu Chrome can you try to on windows, @jonolock91 can you try on OSX.

**Comment by bfintal** [comment]
* I can replicate in Mac Chrome
* Can't in Mac Firefox
* Can't in Mac Safari

Maybe because in Mac FF & Safari the paragraph won't delete unlike in Chrome.

**Comment by bfintal** [comment]
:+1:
