### ISSUE TITLE
Images are turned into display block by default.

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#68]
Image tags are converted into blocks and centered when CT is included. From the console, this CSS is affecting image tags (this is from the compiled CSS):

    img, iframe, video, .ce-element--type-image, .ce-element--type-video {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }

I think `iframes` and `videos` here are fine, but I think images shouldn't be included in this CSS so as not to affect all images in a page.

**Comment by anthonyjb** [comment]
This is just a sensible default for me. I expect people to modify the `_content-edit.sass/css` to be appropriate for their own projects. Using `block` removes the padding from images when wrapped in a link, this is the same as default aligning the image to be central.

**Comment by bfintal** [comment]
The reason I placed this here is because I can't override the styles on the image to bring it back to their defaults. I can easily override this with `body img` but I don't know what the defaults are since the project I'm doing is going on top of sites which may have or may have not their own style rules.

**Comment by anthonyjb** [comment]
You don't need to override it you can just change it. `content-tools.min.css` is best generated separately for your projects (using Sass), so for example if a user clones the project, runs `npm install` then `grunt build-styles` they'll be able to modify the output of `content-tools.min.css` to whatever makes sense for their project. For that style they'd just need to modify `content-edit.sass`. Does that make sense?
