### ISSUE TITLE
Q: Is it possible to handle 'paste' action - any 'paste callback' function?

### ISSUE THREAD

**Issue by MalyshevDmitry** [GetmeUK/ContentTools#7]
For example, I would like to have opportunity to copy-paste formatted data (text, images with H1-5, p, iframe and others tags) from any web page. Is it possible to save data formatting and ability to handle it by my own handler?

For example:
![e5087fe5afdc52fc9f5af5fe0ddb2c2f](https://cloud.githubusercontent.com/assets/1517140/9914005/7b014f7e-5cb8-11e5-80fe-1fb4619ec36e.gif)

**Comment by anthonyjb** [comment]
Yes absolutely, the editor has a paste method which can be monkey patched for example:

# Monkey patch editors paste method
editorCls = ContentTools.EditorApp.getCls()
editorCls.paste = (element, clipboardData) ->
    ... add you custom handler here ...
element is the element being pasted into, and clipboardData is the content pasted by the user (https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData).

You will need to use the develop branch as I modified the source to ensure the clipboardData is sent to the paste event, previously only a plain text version of the content was sent.

**Comment by MalyshevDmitry** [comment]
@anthonyjb I tried to patch 'develop' version with following code, but `console.log('Paste', arguments);` doesn't shows pasted data:

```js
  window.onload = function() {
    var editor, req;
    editor = new ContentTools.EditorApp.get();
    editor.paste = function(element, clipboardData){

      console.log('Paste', arguments); // What's wrong?

    };
    editor.init('.editable', 'data-name');
    editor.bind('save', function(regions, autoSave) {
      var saved;
      editor.busy(true);
      saved = (function(_this) {
        return function() {
          editor.busy(false);
          return new ContentTools.FlashUI('ok');
        };
      })(this);
      return setTimeout(saved, 2000);
    });
    req = new XMLHttpRequest();
    req.overrideMimeType('application/json');
    req.open('GET', 'https://raw.githubusercontent.com/GetmeUK/ContentTools/master/translations/lp.json', true);
    return req.onreadystatechange = function(ev) {
      var translations;
      if (ev.target.readyState === 4) {
        translations = JSON.parse(ev.target.responseText);
        ContentEdit.addTranslations('lp', translations);
        return ContentEdit.LANGUAGE = 'lp';
      }
    };
  };
```

**Comment by anthonyjb** [comment]
So if I patch the editor as you have done and `console.log` the `clipboardData` value I get a DataTransfer object which I can use to query for pasted data (https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent).

This allows me to query the pasted data, for example: `clipboardData.getData('text/plain')`, what is the value of `clipboardData` for you?

**Comment by MalyshevDmitry** [comment]
Works great! Thank you!
