### ISSUE TITLE
ContentSelect range error for images in TextElements with image in link

### ISSUE THREAD

**Issue by anthonyjb** [GetmeUK/ContentTools#71]
@bfintal reported that if you have a text element containing only the following content:

```
<p>
    <a href="...">
        <img ...>
    </a>
</p>
```

And you (text) select the image then drag it and when you drop the element it will produce the following error. 

<img width="672" alt="screen-shot-2015-11-11-at-10 11 49-pm" src="https://cloud.githubusercontent.com/assets/3046287/11097252/4cbd35c4-8896-11e5-93c6-c93cd950a4ad.png">

**Comment by bfintal** [comment]
+1
