### ISSUE TITLE
Start and Stop other buttons.

### ISSUE THREAD

**Issue by calebelt** [GetmeUK/ContentTools#77]
Hi! How to start and stop the editor of other buttons?
http://webismy.work/cms/dnd/dnd.html
This is my open source project visual layout and editing pages for cms.
The user drags the blocks in the position of the template, and if they need to change the text starts an editor (the button with the keyboard icon). As editor will work in modal windows, which will also be a button to start and stop the editor.
How to comment on the content-tools.js standard buttons? Now I can not figure out how to stop the editor.
```
/*Editor*/
$("#cmsContentEditStart").on("click",function(){
 $(".ct-app").remove();
 if ($("div").is("[data-editable]")){
  $(".cmsButtonRow").css("display","none");
  $("#cmsContentEditCancelRow").css("display","table");
  $(".cmsPosition").sortable('disable');
  $(".cmsDraggable").css("cursor","default");
  editor.init('*[data-editable]'); <-- Init for [data-editable] only, in modal window other attribute.
  editor.start();
 } else {
  alert("А что ты собрался редактировать? And what are you going to edit?");
 }
});

$("#cmsContentEditSave").on("click",function(){
 editor.stop();
 editor.destroy();
 $(".ct-app").remove();
 $("[data-editable] *").removeClass("ce-element ce-element--type-text");
 $(".cmsButtonRow").css("display","table");
 $("#cmsContentEditCancelRow").css("display","none");
 $(".cmsPosition").sortable('enable');
 $(".cmsDraggable").css("cursor","pointer");
});

$("#cmsContentEditCancel").on("click",function(){
 editor.stop();
 editor.destroy();
 $(".ct-app").remove();
 $("[data-editable] *").removeClass("ce-element ce-element--type-text");
 $(".cmsButtonRow").css("display","table");
 $("#cmsContentEditCancelRow").css("display","none");
 $(".cmsPosition").sortable('enable');
 $(".cmsDraggable").css("cursor","pointer");
});

```

**Comment by anthonyjb** [comment]
HI @calebelt thanks for your interest in CT.

Forgive me but I'm struggling a little bit to understand what you're attempting to do here, it looks like you want to start and stop the editor using you're own code rather than ignition switch class.

Instead of calling the editor start/stop manually my advice would be to trigger the start/stop events against the ignition instance, or to look at the code [here](https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/editor.coffee#L90) to determine the action that needs to be taken when you stop editing. For example you could do,

```
// Starting the editor manually
editor.init(...);
editor._ignition.trigger('start');

// Stoping the editor manually (save)
editor._iginition.trigger('stop', true);

// Stoping the editor manually (cancel)
editor._iginition.trigger('stop', false);
```

I'd advice against manually removing `ct-app` as you and instead use `editor.destroy();` which in turn calls unmount and should remove the `ct-app` element for you.

If I've misunderstood apologies in advance.

**Comment by calebelt** [comment]
Thanks for the answer! I did not get to stop the script.
For example:
1. From the left pane, drag the "about" in the template.
2. Loading text.
3. Press the button "Start editor"
4. Edit the text.
5. Push the button "Save". And the script will continue. When you hover over the element receives a class "ce-element - over". And if you drag the text block to another position, this element takes the class "ce-element - focused".
https://github.com/calebelt/kubiki-cms/blob/master/dnd.html

I try to do as you have said, but nothing happens - editing not stop. 
I unfortunately do not understand coffee script. :(

```
/*Editor*/
$("#cmsContentEditStart").on("click",function(){
editor.destroy();
 if ($("div").is("[data-editable]")){
  $(".cmsButtonRow").css("display","none");
  $("#cmsContentEditCancelRow").css("display","table");
  $(".cmsPosition").sortable('disable');
  $(".cmsDraggable").css("cursor","default");
editor.init('*[data-editable]');
editor._ignition.trigger('start');
 } else {
  alert("А что ты собрался редактировать? And what are you going to edit?");
 }
});

$("#cmsContentEditSave").on("click",function(){
editor._iginition.trigger('stop', true);
editor.destroy();
 $(".cmsButtonRow").css("display","table");
 $("#cmsContentEditCancelRow").css("display","none");
 $(".cmsPosition").sortable('enable');
 $(".cmsDraggable").css("cursor","pointer");
});

$("#cmsContentEditCancel").on("click",function(){
editor._iginition.trigger('stop', false);
editor.destroy();
 $(".cmsButtonRow").css("display","table");
 $("#cmsContentEditCancelRow").css("display","none");
 $(".cmsPosition").sortable('enable');
 $(".cmsDraggable").css("cursor","pointer");
});

```

**Comment by calebelt** [comment]
I opened the content-tools.js and commented out the functions and Ignition.prototype.mount IgnitionUI.prototype._addDOMEventListeners.
Start editing work.
```
 editor.init('*[data-editable]');
 editor.start();
```

Save - work.
```
editor.save();
editor.destroy();
```

Cancel - not work.
```
editor.stop(); (or editor._iginition.trigger('stop', false);)
editor.destroy();
```

**Comment by calebelt** [comment]
Cancel work.
```
 editor._ignition.trigger('stop', false);
 editor.destroy();
```
Thank you very much for your answers! I will continue to develop cms frontend editor.
It is waiting for version Touch Content tools. :)

**Comment by anthonyjb** [comment]
Wonderful glad it's working for you now :+1:
