### ISSUE TITLE
Move the edit button

### ISSUE THREAD

**Issue by ahmedatya** [GetmeUK/ContentTools#78]
My question is pretty simple. How to change the position of the edit button that appears on the top left of the page.

**Comment by anthonyjb** [comment]
Hi @ahmedatya. The ignition buttons are positioned purely using CSS, you can see the code that positions them [here](https://github.com/GetmeUK/ContentTools/blob/master/src/styles/ui/_ignition.scss#L34).

The easiest way to position them elsewhere is to change the CSS (or override it) for `.ct-ignition`, depending on where you position the buttons you may also need to modify the individual `.ct-ignition__button--busy, --confirm, --cancel, --edit` buttons to.

**Comment by ahmedatya** [comment]
Thanks a lot
