### ISSUE TITLE
Q: bookmarklet?

### ISSUE THREAD

**Issue by crazy4groovy** [GetmeUK/ContentTools#8]
Is it possible to make a bookmarklet that injects this lib into the page, and a Save button that exports the modified DOM/HTML?

**Comment by anthonyjb** [comment]
Yes absolutely, the editor has a `paste` method which can be monkey patched for example:

    # Monkey patch editors paste method
    editorCls = ContentTools.EditorApp.getCls()
    editorCls.paste = (element, clipboardData) ->
        ... add you custom handler here ...

`element` is the element being pasted into, and `clipboardData` is the content pasted by the user (https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData). 

**You will need to use the develop branch as I modified the source to ensure the clipboardData is sent to the paste event, previously only a plain text version of the content was sent.**

**Comment by MalyshevDmitry** [comment]
It seems, that @anthonyjb answered #7 issue?

**Comment by anthonyjb** [comment]
@MalyshevDmitry thanks - yep I got that wrong, that's the answer for #7 will move it now.

**Comment by anthonyjb** [comment]
@crazy4groovy I don't see any reason why not - however you need some way of marking the content that your wanted to be able to change; you couldn't just start the editor, make the entire page editable and then save the HTML out. Either the page's HTML would need to have marked editable regions in a way that your bookmarklet is set to look for (e.g `data-editable="region-name"`), or you'd need to provide a mechanism by which the user could configure the bookmarklet before applying it (for example perhaps a way in which the user could click on the elements they want to be able to edit).

**Comment by crazy4groovy** [comment]
@anthonyjb Yup that's true, I was thinking something _very_ basic like a `prompt` box from the bookmarklet that asks for node(s) the used wants to edit. 

eg. which nodes: `p,div`

**Comment by anthonyjb** [comment]
test
