### ISSUE TITLE
Copy and pasting a link doesn't paste the link

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#81]

**Comment by anthonyjb** [comment]
Hi @bfintal can you explain the issue further please - ContentTools doesn't support Copy/Paste of HTML by default, it only provides plain/text C&P.

**Comment by bfintal** [comment]
To replicate, just create a link, then highlight it or the whole paragraph then paste it. The link (as well as other formatting such as bold) get removed. Is this the intended behavior?

**Comment by anthonyjb** [comment]
Ah I see what you mean, yes currently if you paste content it's has not format so if you don't paste within a formatted area but outside or at the bounds of a formatted area the formatting will be lost. I think if you paste outside of the bounds this is the correct behaviour, but agree if you paste at the bounds then we should look at applying the existing format to the paste code (e.g as if we'd pasted with it).
