### ISSUE TITLE
Table tool should be disabled when inside a table cell

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#83]
Right now the tool is enabled, but it doesn't do anything when clicked.

**Comment by anthonyjb** [comment]
Can you provide an example - using the sandbox the tool behaves as I'd expect and allows you to set the table properties.

**Comment by bfintal** [comment]
Wow my mistake, I never realized that clicking the table tool inside a table opens up it's settings. I thought it was always used for adding tables.

**Comment by anthonyjb** [comment]
np - glad it wasn't a bug :D
