### ISSUE TITLE
Saving not working when i insert youtube embed

### ISSUE THREAD

**Issue by Nisthar** [GetmeUK/ContentTools#88]
Hi, 
ContentTools is an amazing tool. 
The saving is not working when i insert a youtube video into the html. I am saving the contents to a html using laravel backend. I tried to print out the content that i am posting to my server. I am getting the full code including the iframe. But when i save it, I can't see anything in the html file. It works if i remove the youtube video.

**Comment by anthonyjb** [comment]
Hi @Nisthar - if the html being posted to your server is correct but the save is failing then this sounds like it's specific to the server-side code and not CT. My PHP is very sketchy (I'm primarily a Python developer) but if you post the save code you're using I'll take a look (or ask a few friends with more PHP experience to) and see if I can spot the issue - seems odd that iframes are causing the issue.

**Comment by Nisthar** [comment]
Sure. Here's the code:
```php
        public function post(Request $request)
	  {
		$content = $request->review;
			File::put(public_path() . '/contents/'.Session::get('file').'.html', $content);
			$file = Content::findOrFail(Session::get('Id'));
			$file->active = 0;
			if($file->save())
			{
				return "true";
			}else{
				return "false";
			}	
	}
```
I Don't know what's wrong with this code. I can't find any error. Because this only get breaks when i add the youtube iframe. if i add it the filesize of the saved file becomes 0. Otherwise it will work fine.
There are two possibilities:
1. The html is breaking when i add the iframe. So the server only saves " ".
2. There is some limit in PHP for accepting big files.

(Sorry for my bad english)

**Comment by anthonyjb** [comment]
Can I confirm that when you print the value of $content to a log/terminal you get a JSON dict contain a region name for a key and the HTML for the value, and that this is the case with or without the iframes?

**Comment by Nisthar** [comment]
Yes. I get the output with and without the iframe. But its only saving when its without iframe.
I suspect its the problem of double quotes. But I don't see any extra double quotes added for the iframe.

**Comment by anthonyjb** [comment]
@guillaumepiot any chance you could take a look at the code above and see if you can spot anything obvious - looks good to me.

**Comment by guillaumepiot** [comment]
My guess is that PHP has some limitations when it comes to saving HTML to file, and maybe the HTML need to be formatted / compiled a different way to save to a file.

After a quick look online, I found this https://laracasts.com/discuss/channels/laravel/saving-html-contents-of-view-to-disk where people are having the same issue.

I would suggest trying saving the file that way instead, and see if it works: 

```
$view = view('view.name');

$contents = (string) $view;
// or
$contents = $view->render();

file_put_contents('filename.html', $contents);
```

@alexrussell what do you think?

**Comment by guillaumepiot** [comment]
Bump. Just changed the PHP sample.

**Comment by alexrussell** [comment]
@guillaumepiot what you say about getting the HTML contents of a Laravel view in a string is indeed correct (you have to force the view to 'render' by casting to string or asking it to render). However, I don't think this is the issue in this case. In the code that @Nisthar supplied, a view is not being rendered - instead the raw HTML from CT being POSTed to the PHP script is (attempted to be) saved directly to a file.

My immediate thoughts about the specifics here 9without being able to test on the code or reproduce simply) is that either:

1. There's an HTML purifier in between the input (POST data) and the string that Laravel gets, seeing an iframe and assuming foul play. (However, as far as I know Laravel does not, by default, have anything of this nature - it has CSRF protectiton, but no XSS or other input purifying.)
2. CT itself is actually messing with the POSted data. (But as @Nisthar says, `echo`ing the string gives a proper string.)
3. PHP is imposing some limit on the size of the POST request or an individual POST variable. (PHP does have this functionality built in to an extent, and definitely has it built in if you have the Suhosin patch enabled - but again, if the variable can be `echo`ed, then no issue there.)
    - Or mod_security - it can also mess with requests.

So I'm kinda stuck.

**Comment by Nisthar** [comment]
Thanks. @guillaumepiot I think its working now.

**Comment by guillaumepiot** [comment]
@alexrussell thank you for your attention on this issue, very useful information here.

@Nisthar good stuff!

**Comment by anthonyjb** [comment]
Thanks for the help @guillaumepiot and @alexrussell :+1:

**Comment by alexrussell** [comment]
@guillaumepiot, @anthonyjb not sure I really helped in any way being as @guillaumepiot's answer seemed to help @Nisthar but hey. Presumably `$request->review` was sometimes coming as a string (if no iframe) and sometimes an object/array (if iframe present) and that's what stopped it being saved to a file without first being cast to a string. Very weird though!

**Comment by pedrordesign** [comment]
Use a simple blade tag in the view

**{!! $url !!}** THIS WILL RENDER THE VIDEO

instead of

{{ $url }} THIS WILL WRITE AS A STRING (in a input for example)
