### ISSUE TITLE
Overwrite unsaved content warning and/or invoke it manually 

### ISSUE THREAD

**Issue by Eeliya** [GetmeUK/ContentTools#89]
I want to show the unsaved content warning in some custom cases. For example when user wants to do some specific things in the editor, he/she should save the content before that or at least see a confirmation dialog about it.

I also want to be able to change the message according to the changes that user has made, or in other word I just want to overwrite the unsaved content confirmation (this is not very important but it would be nice if I can do it).

**Comment by anthonyjb** [comment]
I might be missing something but if you just want to show a confirm message  before some action is triggered you can use `window.confirm('Some message')` (that's all CT does at the moment), for example:

```coffeescript
# Ask the user if they want to save before performing this action
if window.confirm('Do you want to save before you make this change?')
    # Set up a save event that will be called when the document is saved
    _performTask = () ->
        # Remove the task from future save events
        ContentTools.EditorApp.get().unbind('save', _performTask)

        # ...perform task...

    ContentTools.EditorApp.get().bind('save', _performTask)

    # We send the `true` flag to ensure the save is passive (the DOM is not modified) 
    ContentTools.EditorApp.get().save(true)

else
    # ...perform task...
```

**Comment by Eeliya** [comment]
This answered half of my question. Thank you.
When I stop the editor or try to refresh the page with unsaved content, I see a confirmation again.

I want to overwrite that as well.

**Comment by Eeliya** [comment]
OK, I overwrite window.onbeforeunload, and removed all the unload events from it and added mine

**Comment by anthonyjb** [comment]
Cool :+1:
