### ISSUE TITLE
Spell Mistake in Site,API section

### ISSUE THREAD

**Issue by saravntbe** [GetmeUK/ContentTools#9]
There is a spell Mistake in API section.[Here is the Link](http://getcontenttools.com/api/content-edit#usage)

![Image](https://cloud.githubusercontent.com/assets/2472415/9923543/e70abf74-5d13-11e5-9cad-211da8c4f002.png)

**Comment by anthonyjb** [comment]
Thanks for the spot @saravntbe  - fixed.

**Comment by saravntbe** [comment]
@anthonyjb   Just leaving a note to say thanks for accepting this commit. This was my first ever contribution to open source. It was quite small, but it got me started. Thanks :-)

**Comment by anthonyjb** [comment]
No problem it was a valid contribution :+1:
