### ISSUE TITLE
Parsing error on `:` in tag name, stops script execution

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#90]
Elements that have a colon (or maybe other symbols too) produces an error and stops the editor. For example, this was produced by an `<fb:post>` tag.

    Uncaught Error: Error at char 3 >> Error: Transition is undefined: (:, 6)
        _Parser.parse @ content-tools.js?ver=2.3:1036
        String @ content-tools.js?ver=2.3:105
        Text @ content-tools.js?ver=2.3:3169
        ContentEdit.Text.Text.fromDOMElement @ content-tools.js?ver=2.3:3508

**Comment by anthonyjb** [comment]
@bfintal tag names can now contain colons.
