### ISSUE TITLE
Target attribute of link

### ISSUE THREAD

**Issue by shvetsovdm** [GetmeUK/ContentTools#96]
Hi @andyjbgm, I am looking for a way to add target attribute to a link and it seems like there is no way to do that. Do you plan to implement this feature or may be I missed something?

**Comment by anthonyjb** [comment]
Hi @shvetsovdm if you want to add an attribute to an inline tag (e.g a DOM element within an edtiable elements content) you can use the code editing section from the inspector (see below):

![image](https://cloud.githubusercontent.com/assets/3046287/12320148/e39db664-ba9e-11e5-8120-6b45f8b5d039.png)

We don't have any plans to add an option to manage attributes on inline tags as individuals at the moment.

**Comment by shvetsovdm** [comment]
Оh yeah of course, code editor.

What if I make PR with changes how ContentTools.LinkDialog works to add target attribute, will you accept this PR?

**Comment by MalyshevDmitry** [comment]
In my opinion it'll be amazing!15.01.2016, 03:15, "Dmitry Shvetsov" <notifications@github.com>:Оh yeah of course, code editor.What if I make PR with changes how ContentTools.LinkDialog works to add target attribute, will you accept this PR?—Reply to this email directly or view it on GitHub.￼

**Comment by anthonyjb** [comment]
Hi @shvetsovdm, it would really depend on how it was implemented, anchored popups are really only designed with a single field in mind currently and adding an extra field of almost the same size to the link popup that's (IMO) in most cases not used wouldn't feel right to me. However I agree this would be a useful short-cut so if an elegant solution can be reached then yes. 

Initial thoughts are perhaps showing a target icon right of the field that can be clicked to reveal the target field, along with a way to reveal the field using the keyboard also (such as hitting the tab key whilst in the URL field).

What do you think?

**Comment by aljopro** [comment]
@anthonyjb do you have a standard UX for modifiers like this yet? I would use whatever has been established by the tool. If not, this might be a good place to establish that UX.

**Comment by shvetsovdm** [comment]
Hi @andyjbgm I think this will work well.

I'm curious, why for anchors was not used Content Tools.DialogUE window?

**Comment by anthonyjb** [comment]
@aljopro at the moment the only action that uses the popup is the link tool so at the moment there's not UX for this. Since only the add link tool uses the anchored popup right now we probably need to think about some other scenarios where this might come to establish the UX. Adding time data to an attribute might be one (as in the tutorial http://getcontenttools.com/tutorials/adding-new-tools).

@shvetsovdm the standard dialog is not ideal for actions like this as it takes you away from the content you're editing. With anchored dialogs you remain in context (e.g you can see the section of text you're applying the link to, which would typically be hidden by a normal dialog).

**Comment by MalyshevDmitry** [comment]
Look, how it done in Imperavi Redactor (http://imperavi.com/redactor):

Click on link:
![adbcc5892a248918ff35d33c0ade6c48](https://cloud.githubusercontent.com/assets/1517140/12349674/9999c546-bb82-11e5-97e2-c6e431e3ad54.png)

Then after click on 'Edit':
![f7b57d5b9f5a817fb2e39fb03f0ff1ba](https://cloud.githubusercontent.com/assets/1517140/12349688/af540784-bb82-11e5-8453-5f2a6d81ec82.png)

**Comment by shvetsovdm** [comment]
@anthonyjb I see, this sounds reasonable.

@anthonyjb what do you think about @MalyshevDmitry example?

**Comment by anthonyjb** [comment]
@shvetsovdm I think it works but in an ideal world it wouldn't be the approach I'd take. I'm not keen on the large dialog given we're only looking at showing 2 fields (URL and target) and it doesn't keep the context. 

One other thing to note is I think target should be a field you can set, however the approach here of a simple checkbox for the most common requirement is very nice. So maybe we say if you want to set the target to something other than `_blank` you can do it in the code editor but we simply have an *open in new window* icon (replacing the target one I suggested earlier) that can be toggled?

**Comment by shvetsovdm** [comment]
@anthonyjb ok, I'll try to implement your "open in new window icon" approach.

**Comment by shvetsovdm** [comment]
@anthonyjb, looks good?

![screen shot 2016-01-22 at 10 46 07 pm](https://cloud.githubusercontent.com/assets/3574904/12511047/9eaf93f6-c151-11e5-9bc7-7d99851fae10.png)


![ct_a_target_demo](https://cloud.githubusercontent.com/assets/3574904/12511028/7c7e9070-c151-11e5-93a3-4024524aa4c3.gif)

**Comment by anthonyjb** [comment]
I think it looks awesome! Perfect to me.
